import { Roadmap } from "../types/roadmap";

export const aiEngineerRoadmap: Roadmap = {
  id: "ai-engineer",
  title: "AI Engineer",
  description: "Design, build, and deploy AI-powered applications using machine learning and LLMs.",
  introduction: "AI engineering combines software development with machine learning to build intelligent applications. You'll learn to work with LLMs, build RAG systems, and deploy models that can reason, generate, and automate.",
  icon: "🤖",
  category: "Data & AI",
  difficulty: "Expert",
  estimatedTime: "6-12 months",
  steps: [
    {
      id: "step-1",
      label: "Python for AI",
      tool: "Python",
      description: "Master Python with focus on data structures, list comprehensions, decorators, and generators. Learn NumPy for numerical computation and Pandas for data manipulation. Python is the lingua franca of AI — almost every library and framework uses it.",
      url: "https://www.python.org/doc/",
    },
    {
      id: "step-2",
      label: "Math for ML",
      tool: "Linear Algebra",
      description: "Understand vectors, matrices, eigenvalues, and gradient descent. Learn probability theory, Bayes' theorem, and statistical distributions. You don't need a PhD, but a solid grasp of these concepts is essential for understanding how models learn.",
      url: "https://www.khanacademy.org/math/linear-algebra",
    },
    {
      id: "step-3",
      label: "Classical ML",
      tool: "Scikit-learn",
      description: "Implement regression, classification, clustering, and dimensionality reduction. Learn cross-validation, hyperparameter tuning, and evaluation metrics. These algorithms are the foundation — many modern techniques are extensions of these concepts.",
      url: "https://scikit-learn.org/stable/",
    },
    {
      id: "step-4",
      label: "Data Wrangling",
      tool: "Pandas",
      description: "Clean, transform, and reshape messy real-world datasets. Handle missing values, outliers, and data type conversions. Real data is dirty — 80% of an AI engineer's time is spent on data preparation, not model building.",
      url: "https://pandas.pydata.org/docs/user_guide/",
    },
    {
      id: "step-5",
      label: "Deep Learning",
      tool: "PyTorch",
      description: "Build and train neural networks with automatic differentiation. Understand backpropagation, activation functions, loss functions, and optimizers. PyTorch's dynamic computation graph makes it the favorite for research and production alike.",
      url: "https://pytorch.org/",
    },
    {
      id: "step-6",
      label: "CNNs & Computer Vision",
      tool: "PyTorch Vision",
      description: "Build convolutional neural networks for image classification, object detection, and segmentation. Learn about convolution layers, pooling, and transfer learning with pre-trained models like ResNet.",
      url: "https://pytorch.org/vision/stable/index.html",
    },
    {
      id: "step-7",
      label: "Transformers",
      tool: "Hugging Face",
      description: "Understand the attention mechanism, positional encoding, and the transformer architecture. Load and fine-tune pre-trained models for text classification, named entity recognition, and summarization. Transformers revolutionized NLP and are now used in vision and multimodal tasks.",
      url: "https://huggingface.co/docs/transformers",
    },
    {
      id: "step-8",
      label: "LLM Fundamentals",
      tool: "OpenAI API",
      description: "Interact with large language models via APIs. Understand tokenization, temperature, top-p sampling, system prompts, and function calling. Learn the capabilities and limitations of models like GPT-4 and Claude.",
      url: "https://platform.openai.com/docs",
    },
    {
      id: "step-9",
      label: "RAG Systems",
      tool: "LangChain",
      description: "Build Retrieval-Augmented Generation systems that combine LLMs with external knowledge. Learn document chunking, vector embeddings, semantic search, and context injection. RAG is how you make LLMs answer questions about your specific data.",
      url: "https://python.langchain.com/docs/tutorials/rag",
    },
    {
      id: "step-10",
      label: "Vector Databases",
      tool: "Pinecone",
      description: "Store and query high-dimensional embeddings for similarity search. Understand vector indexing algorithms like HNSW and IVF. Vector databases are the memory layer for AI applications — they let you search by meaning, not keywords.",
      url: "https://docs.pinecone.io/",
    },
    {
      id: "step-11",
      label: "AI Agents",
      tool: "LangGraph",
      description: "Build autonomous agents that can plan, use tools, and make decisions. Implement tool use, memory, and multi-step reasoning. Agents are the frontier of AI engineering — they turn LLMs from chatbots into problem solvers.",
      url: "https://langchain-ai.github.io/langgraph/",
    },
    {
      id: "step-12",
      label: "Fine-Tuning",
      tool: "LoRA",
      description: "Adapt pre-trained models to your specific domain using parameter-efficient fine-tuning. Learn LoRA, QLoRA, and when to fine-tune vs. use RAG vs. prompt engineering. Fine-tuning gives you control over model behavior that prompting alone can't achieve.",
      url: "https://huggingface.co/docs/peft/",
    },
    {
      id: "step-13",
      label: "MLOps",
      tool: "MLflow",
      description: "Track experiments, version models, and manage the ML lifecycle. Learn about model registries, A/B testing, and monitoring model drift in production. MLOps bridges the gap between a working notebook and a reliable production system.",
      url: "https://mlflow.org/docs/latest/index.html",
    },
    {
      id: "step-14",
      label: "Deployment",
      tool: "Docker",
      description: "Containerize AI applications for consistent deployment across environments. Serve models with FastAPI, load balance inference requests, and optimize for latency. Docker ensures your model works the same way on your laptop and in production.",
      url: "https://docs.docker.com/",
    },
  ],
};
