import { Roadmap } from "../types/roadmap";

export const autonomousVehicleEngineerRoadmap: Roadmap = {
  id: "autonomous-vehicle-engineer",
  title: "Autonomous Vehicle Engineer",
  description: "Develop self-driving car systems using perception, planning, and control.",
  introduction: "Autonomous vehicle engineering builds self-driving systems using computer vision, sensor fusion, and path planning. You'll master C++, ROS, and simulation tools to develop vehicles that navigate the world independently.",
  icon: "🚗",
  category: "Engineering",
  difficulty: "Expert",
  estimatedTime: "12-18 months",
  steps: [
    {
      id: "step-1",
      label: "C++ & Python",
      tool: "C++",
      description: "C++ is the backbone of autonomous vehicle software due to its low-level memory control and real-time performance guarantees. Python serves as the primary language for prototyping, rapid experimentation, and scripting data pipelines. Together, they form the dual-language foundation that most AV development stacks rely on.",
      url: "https://isocpp.org/get-started",
    },
    {
      id: "step-2",
      label: "Computer Vision",
      tool: "OpenCV",
      description: "Computer vision enables vehicles to interpret and understand visual data from onboard cameras. Using OpenCV, engineers build pipelines for lane detection, traffic sign recognition, and pedestrian tracking in real-time video streams. Mastering image processing, feature extraction, and deep learning-based detection is essential for robust perception.",
      url: "https://docs.opencv.org/4.x/d6/d00/tutorial_py_root.html",
    },
    {
      id: "step-3",
      label: "Sensor Fusion",
      tool: "ROS",
      description: "Sensor fusion combines data from LiDAR, radar, cameras, and IMUs to create a unified and reliable model of the surrounding environment. Each sensor has unique strengths and blind spots, so fusing their outputs improves accuracy, reduces uncertainty, and enables fail-safe perception. ROS provides the middleware infrastructure to synchronize, route, and process multi-sensor data streams.",
      url: "https://docs.ros.org/",
    },
    {
      id: "step-4",
      label: "Path Planning",
      tool: "Apollo",
      description: "Path planning determines the optimal route a vehicle should follow from its current position to a destination while avoiding obstacles and obeying traffic rules. Apollo's open-source framework offers modules for routing, trajectory planning, and behavioral decision-making in complex urban scenarios. Engineers work with graph search algorithms, optimization techniques, and cost functions to generate smooth, safe, and efficient driving trajectories.",
      url: "https://apollo.auto/developer.html",
    },
    {
      id: "step-5",
      label: "Control Systems",
      tool: "PID Controllers",
      description: "Control systems translate planned trajectories into physical steering, acceleration, and braking commands. PID controllers, model predictive control, and state-space methods are used to track desired paths while compensating for disturbances and latency. A deep understanding of feedback loops, transfer functions, and vehicle dynamics is critical for achieving smooth and safe ride quality.",
      url: "https://www.piddigital.com/",
    },
    {
      id: "step-6",
      label: "Simulation",
      tool: "CARLA",
      description: "Simulation platforms like CARLA allow engineers to test autonomous driving algorithms in realistic virtual environments before deploying on real vehicles. Scenarios including adverse weather, dense traffic, and rare edge cases can be reproduced safely and at scale. Simulation accelerates development cycles, reduces costs, and provides repeatable testing conditions for validating perception and planning modules.",
      url: "https://carla.org/develop/simulators/",
    },
    {
      id: "step-7",
      label: "Safety & Testing",
      tool: "ISO 26262",
      description: "Automotive safety standards like ISO 26262 define the processes and requirements for ensuring functional safety in vehicle electronic systems. Engineers must conduct rigorous hazard analysis, risk assessment, and fault injection testing throughout the development lifecycle. Validation strategies include formal verification, coverage analysis, and systematic regression testing to achieve the required Automotive Safety Integrity Level.",
      url: "https://www.iso.org/standard/68383.html",
    },
    {
      id: "step-8",
      label: "HD Maps",
      tool: "OpenDRIVE",
      description: "High-definition maps provide centimeter-accurate representations of road geometry, lane boundaries, traffic signs, and signal positions. Unlike consumer navigation maps, HD maps encode semantic and structural details that autonomous vehicles rely on for localization and planning. OpenDRIVE and related standards define the data formats and layers that make HD maps interoperable across tools and platforms.",
      url: "https://www.opendrive.org/",
    },
    {
      id: "step-9",
      label: "LiDAR Processing",
      tool: "PCL",
      description: "LiDAR sensors generate dense 3D point clouds that represent the vehicle's surroundings with precise depth measurements. Processing these point clouds requires algorithms for segmentation, clustering, ground plane removal, and object classification using the Point Cloud Library. Efficient LiDAR data handling is essential for real-time obstacle detection, localization against HD maps, and scene understanding.",
      url: "https://pointclouds.org/",
    },
    {
      id: "step-10",
      label: "Vehicle-to-Everything (V2X)",
      tool: "V2X Communication",
      description: "V2X communication enables vehicles to exchange information with other vehicles, infrastructure, pedestrians, and cloud services. Standards like DSRC and C-V2X provide low-latency, reliable messaging for cooperative perception, intersection management, and hazard warnings. Integrating V2X data extends a vehicle's awareness beyond its line of sight and supports coordinated driving strategies.",
      url: "https://www.its.dot.gov/resources_v2x.htm",
    },
    {
      id: "step-11",
      label: "Machine Learning for AV",
      tool: "PyTorch",
      description: "Machine learning powers core perception tasks such as object detection, semantic segmentation, motion prediction, and end-to-end driving policies. PyTorch and TensorFlow provide the frameworks for training, fine-tuning, and deploying neural networks on embedded hardware. Engineers must understand dataset curation, data augmentation, transfer learning, and model optimization techniques like quantization and pruning for production deployment.",
      url: "https://pytorch.org/",
    },
    {
      id: "step-12",
      label: "Data Pipeline",
      tool: "Apache Kafka",
      description: "Autonomous vehicles generate terabytes of sensor data per hour that must be ingested, processed, stored, and labeled efficiently. A robust data pipeline handles real-time streaming from vehicle fleets, batch processing for training data, and versioned dataset management. Tools like Apache Kafka, Apache Spark, and cloud storage architectures form the backbone of scalable AV data infrastructure.",
      url: "https://kafka.apache.org/",
    },
  ],
};
