import { Roadmap } from "../types/roadmap";

export const backendDeveloperRoadmap: Roadmap = {
  id: "backend-developer",
  title: "Backend Developer",
  description: "Build server-side APIs, databases, and business logic for applications.",
  introduction: "Backend development powers the server-side logic and data layers of applications. You'll learn to build APIs with FastAPI, design databases, implement authentication, and containerize services.",
  icon: "⚙️",
  category: "Engineering",
  difficulty: "Intermediate",
  estimatedTime: "4-7 months",
  steps: [
    {
      id: "step-1",
      label: "Programming Language",
      tool: "Python",
      description: "Master a server-side language with strong ecosystem support. Learn data structures, file I/O, error handling, virtual environments, and package management. Python's readability and vast library ecosystem make it ideal for backend development.",
      url: "https://www.python.org/doc/",
    },
    {
      id: "step-2",
      label: "Linux & Command Line",
      tool: "Linux",
      description: "Navigate the file system, manage processes, configure permissions, and write shell scripts. Most servers run Linux — comfort with the terminal is essential for any backend developer, even if you deploy to managed services.",
      url: "https://linuxjourney.com/",
    },
    {
      id: "step-3",
      label: "HTTP & REST",
      tool: "HTTP",
      description: "Understand HTTP methods (GET, POST, PUT, DELETE, PATCH), status codes, headers, content types, and REST conventions. HTTP is the protocol that powers the web — deep knowledge of it makes you a better API designer.",
      url: "https://developer.mozilla.org/en-US/docs/Web/HTTP/Overview",
    },
    {
      id: "step-4",
      label: "Web Framework",
      tool: "FastAPI",
      description: "Build high-performance APIs with automatic OpenAPI documentation, request validation with Pydantic, dependency injection, and async support. FastAPI's type safety and auto-generated docs make it the fastest way to build production APIs in Python.",
      url: "https://fastapi.tiangolo.com/tutorial/",
    },
    {
      id: "step-5",
      label: "Database Design",
      tool: "PostgreSQL",
      description: "Design normalized schemas with proper relationships, constraints, and indexes. Learn about ACID transactions, isolation levels, and query optimization with EXPLAIN. Database design decisions are hard to change later — get the schema right early.",
      url: "https://www.postgresql.org/docs/",
    },
    {
      id: "step-6",
      label: "ORM",
      tool: "SQLAlchemy",
      description: "Map Python objects to database tables with relationships, lazy loading, eager loading, and migrations. SQLAlchemy protects against SQL injection and provides a Pythonic API for complex queries. Understanding both ORM and raw SQL is essential.",
      url: "https://docs.sqlalchemy.org/",
    },
    {
      id: "step-7",
      label: "Authentication",
      tool: "OAuth 2.0",
      description: "Implement JWT tokens, refresh tokens, password hashing with bcrypt, and OAuth 2.0 flows (authorization code, client credentials). Understand session vs. token auth, CSRF protection, and rate limiting. Authentication is security-critical — mistakes here are costly.",
      url: "https://oauth.net/2/",
    },
    {
      id: "step-8",
      label: "API Validation",
      tool: "Pydantic",
      description: "Validate request bodies, query parameters, and response models with strict type checking. Define schemas for input/output, handle nested objects, and serialize data correctly. Validation at the API boundary prevents bad data from entering your system.",
      url: "https://docs.pydantic.dev/",
    },
    {
      id: "step-9",
      label: "Caching",
      tool: "Redis",
      description: "Cache frequently accessed data with Redis for sub-millisecond reads. Learn caching strategies (cache-aside, write-through, write-behind), TTL, and cache invalidation. Caching is one of the highest-impact optimizations for API performance.",
      url: "https://redis.io/docs/",
    },
    {
      id: "step-10",
      label: "Background Tasks",
      tool: "Celery",
      description: "Offload long-running tasks (emails, reports, image processing) to background workers. Learn task queues, retries, rate limiting, and monitoring with Flower. Background jobs keep your API responsive by not blocking the main thread.",
      url: "https://docs.celeryq.dev/",
    },
    {
      id: "step-11",
      label: "Testing",
      tool: "pytest",
      description: "Write unit tests for business logic, integration tests for API endpoints, and test database operations with fixtures. Use mocking to isolate external dependencies. Tests give you confidence to refactor and add features without breaking existing functionality.",
      url: "https://docs.pytest.org/",
    },
    {
      id: "step-12",
      label: "Containerization",
      tool: "Docker",
      description: "Package your application with its dependencies into reproducible containers. Write Dockerfiles with multi-stage builds, manage environment variables, and use docker-compose for local development. Docker eliminates 'works on my machine' problems.",
      url: "https://docs.docker.com/",
    },
    {
      id: "step-13",
      label: "Logging & Monitoring",
      tool: "structlog",
      description: "Implement structured logging with context (request ID, user ID, timestamps). Set up health checks, metrics endpoints, and error tracking. Observability is how you debug production issues — good logging saves hours of detective work.",
      url: "https://www.structlog.org/",
    },
    {
      id: "step-14",
      label: "Deployment",
      tool: "Railway",
      description: "Deploy your API with automatic HTTPS, environment management, and database provisioning. Learn about health checks, graceful shutdowns, and zero-downtime deployments. Deployment is the final step — shipping is what matters.",
      url: "https://docs.railway.app/",
    },
  ],
};
