import { Roadmap } from "../types/roadmap";

export const biostatisticianRoadmap: Roadmap = {
  id: "biostatistician",
  title: "Biostatistician",
  description: "Design studies, analyze health data, and draw rigorous conclusions in biomedical research.",
  introduction: "Biostatistics applies statistical methods to biological and health sciences. You'll master probability theory, clinical trial design, survival analysis, and regulatory standards to support evidence-based medicine and public health decisions.",
  icon: "🧬",
  category: "Health & Science",
  difficulty: "Expert",
  estimatedTime: "8-14 months",
  steps: [
    {
      id: "step-1",
      label: "Probability & Statistics",
      tool: "R / Python",
      description: "Build a solid foundation in probability theory, discrete and continuous distributions, and the laws of large numbers. Master descriptive statistics, expectation, variance, and moment-generating functions to understand how random phenomena behave. This theoretical grounding is essential for every statistical method you will encounter in biostatistics.",
      url: "https://www.khanacademy.org/math/statistics-probability",
    },
    {
      id: "step-2",
      label: "Statistical Inference",
      tool: "R / SAS",
      description: "Learn point estimation, maximum likelihood, method of moments, and properties of estimators such as consistency and efficiency. Study hypothesis testing, p-values, confidence intervals, and the likelihood ratio test to draw conclusions from sample data. Understanding the foundations of inference prevents misinterpretation of results in published research.",
      url: "https://www.stat.cmu.edu/~larry/all-of-statistics/",
    },
    {
      id: "step-3",
      label: "Regression Analysis",
      tool: "R / SAS",
      description: "Fit linear regression models with continuous outcomes and logistic regression for binary responses. Extend to Poisson, ordinal, and multinomial models while mastering residual diagnostics, collinearity detection, and model selection criteria like AIC and BIC. Regression is the workhorse of biomedical data analysis, used in nearly every published study.",
      url: "https://cran.r-project.org/web/packages/recipes/vignettes/recipes.html",
    },
    {
      id: "step-4",
      label: "Clinical Trials Design",
      tool: "R / SAS",
      description: "Design randomized controlled trials with proper randomization schemes, stratification, and blocking to control confounding. Calculate sample size and power, and plan interim analyses using group-sequential and adaptive designs. A well-designed trial is the gold standard for evaluating treatment efficacy and is required for regulatory approval.",
      url: "https://www.fda.gov/regulatory-information/search-fda-guidance-documents",
    },
    {
      id: "step-5",
      label: "Survival Analysis",
      tool: "R (survival) / SAS",
      description: "Analyze time-to-event data with censoring using Kaplan-Meier estimators, log-rank tests, and Cox proportional hazards models. Extend to competing risks, frailty models, and accelerated failure time models for complex survival structures. Survival analysis is indispensable in oncology, cardiology, and any field where the outcome is time until an event.",
      url: "https://cran.r-project.org/web/packages/survival/vignettes/survival.pdf",
    },
    {
      id: "step-6",
      label: "Longitudinal Data Analysis",
      tool: "R (lme4) / SAS (PROC MIXED)",
      description: "Model repeated measures and clustered data using mixed-effects models with random intercepts and slopes. Account for autocorrelation, missing data mechanisms, and time-varying covariates using generalized estimating equations or linear mixed models. Longitudinal methods are critical for cohort studies, growth curve modeling, and clinical follow-up data.",
      url: "https://cran.r-project.org/web/packages/lme4/vignettes/lmer.pdf",
    },
    {
      id: "step-7",
      label: "Categorical Data Analysis",
      tool: "R (MASS) / SAS (PROC FREQ)",
      description: "Analyze contingency tables with chi-squared tests, Fisher's exact test, and measures of association such as odds ratios and relative risk. Fit log-linear models, generalized linear models for count data, and exact methods for sparse tables. Categorical data methods are essential for epidemiological studies and diagnostic test evaluation.",
      url: "https://cran.r-project.org/web/packages/MASS/",
    },
    {
      id: "step-8",
      label: "Bayesian Statistics",
      tool: "R (rstan) / Stan",
      description: "Apply Bayesian inference using prior distributions, likelihood functions, and posterior computation via MCMC sampling. Learn conjugate priors, hierarchical modeling, and model comparison with Bayes factors and posterior predictive checks. Bayesian methods offer a flexible alternative to frequentist inference, especially useful for small samples and complex hierarchical structures.",
      url: "https://mc-stan.org/users/documentation/",
    },
    {
      id: "step-9",
      label: "Statistical Computing (R/SAS)",
      tool: "R / SAS / Python",
      description: "Master R for data manipulation with dplyr and tidyr, statistical modeling, and publication-quality graphics with ggplot2. Gain proficiency in SAS for regulatory submissions using PROC LOGISTIC, PROC PHREG, and macro programming. Both R and SAS are industry standards — R dominates in academia while SAS remains mandatory for FDA submissions.",
      url: "https://www.r-project.org/",
    },
    {
      id: "step-10",
      label: "Epidemiology",
      tool: "R / SAS",
      description: "Study study design fundamentals including cohort, case-control, and cross-sectional designs along with measures of disease frequency like incidence and prevalence. Calculate risk ratios, odds ratios, attributable risk, and number needed to treat while controlling for confounders with stratification and multivariable adjustment. Epidemiological methods provide the framework for understanding disease etiology and risk factors.",
      url: "https://www.cdc.gov/ecoli/glossary.html",
    },
    {
      id: "step-11",
      label: "Meta-Analysis",
      tool: "R (metafor)",
      description: "Synthesize results across multiple studies using fixed-effects and random-effects models to estimate pooled treatment effects. Assess heterogeneity with the I-squared statistic and Q test, detect publication bias with funnel plots and Egger's test, and conduct subgroup and sensitivity analyses. Meta-analysis is the cornerstone of evidence-based medicine, turning individual study results into definitive conclusions.",
      url: "https://cran.r-project.org/web/packages/metafor/index.html",
    },
    {
      id: "step-12",
      label: "Regulatory Statistics",
      tool: "SAS / R",
      description: "Prepare statistical analysis plans, data definitions, and output for FDA and EMA submissions following ICH E9 and E6 guidelines. Understand multiplicity adjustment, missing data handling strategies, estimand frameworks, and the difference between confirmatory and exploratory analyses. Regulatory knowledge bridges the gap between statistical methodology and real-world drug approval.",
      url: "https://www.ich.org/page/efficacy-guidelines",
    },
    {
      id: "step-13",
      label: "Communication of Results",
      tool: "R Markdown / LaTeX",
      description: "Write clear statistical reports and publications that convey complex findings to diverse audiences, from clinicians to regulatory reviewers. Master R Markdown for reproducible analysis, create publication-ready tables with gtsummary, and present survival curves, forest plots, and regression summaries effectively. The ability to communicate statistical results clearly is what makes your analysis actionable in clinical and policy settings.",
      url: "https://rmarkdown.rstudio.com/",
    },
  ],
};
