import { Roadmap } from "../types/roadmap";

export const biotechDataScientistRoadmap: Roadmap = {
  id: "biotech-data-scientist",
  title: "Biotech Data Scientist",
  description: "Apply data science to genomics, drug discovery, and bioinformatics.",
  introduction: "Biotech data science applies computational methods to genomics and drug discovery. Learn bioinformatics, genomics, statistics, machine learning, and visualization.",
  icon: "🧬",
  category: "Science",
  difficulty: "Expert",
  estimatedTime: "8-12 months",
  steps: [
    {
      id: "step-1",
      label: "Bioinformatics",
      tool: "Biopython",
      description: "Biopython provides tools for biological computation including sequence parsing, alignment, and phylogenetics. Master FASTA/GenBank file handling, BLAST searches, and Entrez queries to retrieve data from NCBI databases. Use it to build pipelines that process raw sequencing data into actionable biological insights.",
      url: "https://biopython.org/wiki/Documentation",
    },
    {
      id: "step-2",
      label: "Genomics (GATK)",
      tool: "GATK",
      description: "The Genome Analysis Toolkit from the Broad Institute is the gold standard for variant calling in whole-genome and exome sequencing studies. Learn the Best Practices workflow including base quality score recalibration, indel realignment, and joint genotyping across cohorts. Apply hard filtering or VQSR to produce high-confidence call sets suitable for downstream association studies.",
      url: "https://gatk.broadinstitute.org/",
    },
    {
      id: "step-3",
      label: "Statistics (R/Bioconductor)",
      tool: "R/Bioconductor",
      description: "Bioconductor hosts over 2,000 R packages for analyzing high-throughput genomic data including microarrays, RNA-seq, and ChIP-seq. Use DESeq2 or edgeR for differential gene expression, clusterProfiler for pathway enrichment, and limma for linear modeling of complex experimental designs. R's statistical ecosystem enables rigorous hypothesis testing, multiple testing correction, and publication-ready reporting.",
      url: "https://www.bioconductor.org/",
    },
    {
      id: "step-4",
      label: "Machine Learning",
      tool: "Scikit-learn",
      description: "Scikit-learn offers a consistent API for classification, regression, clustering, and dimensionality reduction across hundreds of algorithms. Build predictive models for drug response prediction, patient stratification, and biomarker discovery using random forests, SVMs, and gradient boosting. Master cross-validation, hyperparameter tuning, and feature importance analysis to ensure generalizability on held-out clinical cohorts.",
      url: "https://scikit-learn.org/stable/",
    },
    {
      id: "step-5",
      label: "Visualization (ggplot2)",
      tool: "ggplot2",
      description: "ggplot2 implements the grammar of graphics to create layered, customizable visualizations from complex biological datasets. Generate volcano plots for differential expression, survival curves with confidence bands, and multi-panel heatmaps for gene expression profiling. Combine faceting, annotations, and custom color scales to produce figures that meet journal publication standards.",
      url: "https://ggplot2.tidyverse.org/",
    },
    {
      id: "step-6",
      label: "Drug Discovery",
      tool: "DeepChem",
      description: "DeepChem provides deep learning and machine learning models for molecular property prediction, virtual screening, and QSAR modeling. Train graph neural networks on molecular graphs to predict ADMET properties, binding affinities, and toxicity profiles. Integrate molecular docking scores with learned representations to prioritize compound libraries for experimental validation.",
      url: "https://deepchem.io/",
    },
    {
      id: "step-7",
      label: "Single-Cell Analysis",
      tool: "Scanpy",
      description: "Scanpy is a Python framework for analyzing single-cell RNA sequencing data at scale, handling datasets with millions of cells. Implement workflows for quality control, normalization, dimensionality reduction with UMAP/t-SNE, and clustering to identify cell types and states. Use trajectory inference and RNA velocity to model cellular differentiation paths and reconstruct developmental lineages.",
      url: "https://scanpy.readthedocs.io/",
    },
    {
      id: "step-8",
      label: "Proteomics",
      tool: "MaxQuant",
      description: "MaxQuant performs quantitative proteomics analysis from raw mass spectrometry data using label-free quantification and TMT/iTRAQ workflows. Identify and quantify thousands of proteins across samples, perform differential abundance analysis, and detect post-translational modifications. Integrate proteomic data with transcriptomic profiles to uncover regulatory mechanisms not visible at the mRNA level.",
      url: "https://www.maxquant.org/",
    },
    {
      id: "step-9",
      label: "Clinical Data",
      tool: "Pandas",
      description: "Pandas provides the core data manipulation toolkit for handling Electronic Health Records, clinical trial datasets, and patient registries. Clean messy clinical data, merge disparate sources, handle missing values with appropriate imputation strategies, and engineer features for predictive modeling. Ensure data integrity through validation checks that respect HIPAA constraints and clinical data standards like CDISC.",
      url: "https://pandas.pydata.org/",
    },
    {
      id: "step-10",
      label: "Literature Mining",
      tool: "PubTator",
      description: "PubTator and text mining tools extract biomedical entities and relationships from the vast PubMed literature corpus. Use named entity recognition to identify genes, diseases, chemicals, and mutations mentioned across millions of abstracts. Build knowledge graphs from extracted relations to generate hypotheses, identify drug repurposing opportunities, and discover connections between distant biological domains.",
      url: "https://www.ncbi.nlm.nih.gov/research/pubtator/",
    },
    {
      id: "step-11",
      label: "Biostatistics",
      tool: "SAS",
      description: "SAS is widely used in pharmaceutical and biotech industries for regulatory-grade statistical analysis of clinical trials. Master survival analysis with Cox proportional hazards models, interim analyses with group sequential designs, and adaptive trial designs. Understand regulatory requirements from the FDA and EMA, including ICH guidelines for statistical methodology in drug approval submissions.",
      url: "https://www.sas.com/",
    },
    {
      id: "step-12",
      label: "Reproducible Research",
      tool: "Nextflow",
      description: "Nextflow enables scalable, reproducible bioinformatics pipelines that run across local servers, HPC clusters, and cloud platforms. Package workflows with conda or Docker containers to ensure consistent software environments across analyses. Implement version-controlled pipelines with Git that can be shared with collaborators and archived alongside publications to meet data reproducibility standards.",
      url: "https://www.nextflow.io/",
    },
  ],
};
