import { Roadmap } from "../types/roadmap";

export const blockchainDeveloperRoadmap: Roadmap = {
  id: "blockchain-developer",
  title: "Blockchain Developer",
  description: "Build decentralized applications and smart contracts on blockchain networks.",
  introduction: "Blockchain development builds decentralized applications and smart contracts. You'll learn Ethereum, Solidity, Hardhat, and security auditing to create trustless systems.",
  icon: "⛓️",
  category: "Engineering",
  difficulty: "Intermediate",
  estimatedTime: "6-9 months",
  steps: [
    {
      id: "step-1",
      label: "Blockchain Basics",
      tool: "Bitcoin Whitepaper",
      description: "Understand the core concepts of distributed ledgers, consensus mechanisms, and cryptographic hashes that power blockchain technology. Study how blocks are linked together and how nodes agree on the state of the network through protocols like Proof of Work and Proof of Stake. This foundational knowledge is essential before writing any smart contract code.",
      url: "https://bitcoin.org/bitcoin.pdf",
    },
    {
      id: "step-2",
      label: "Ethereum",
      tool: "Ethereum",
      description: "Explore the Ethereum network as a global, permissionless computer capable of running arbitrary programs called smart contracts. Learn about the Ethereum Virtual Machine (EVM), how transactions are processed, and the role of gas in preventing network abuse. Understanding Ethereum's architecture will help you design efficient and scalable decentralized applications.",
      url: "https://ethereum.org/en/developers/docs/",
    },
    {
      id: "step-3",
      label: "Solidity",
      tool: "Solidity",
      description: "Master Solidity, the primary programming language for writing smart contracts on Ethereum and other EVM-compatible chains. Learn its statically-typed syntax, contract structure, inheritance patterns, and how to define state-changing functions. Practice writing contracts that handle Ether transfers, manage access control, and interact with other contracts on-chain.",
      url: "https://docs.soliditylang.org/",
    },
    {
      id: "step-4",
      label: "Smart Contracts",
      tool: "Solidity",
      description: "Design and implement smart contracts that encode business logic, enforce rules, and hold digital assets without intermediaries. Study common contract patterns such as proxies for upgradeability, multisig wallets, and time-locked vaults. Understanding how to structure contracts for maintainability and security will save you from costly bugs after deployment.",
      url: "https://docs.soliditylang.org/",
    },
    {
      id: "step-5",
      label: "Development Tools",
      tool: "Hardhat",
      description: "Set up a local development environment using Hardhat or Foundry to compile, test, and debug smart contracts before deploying them. These frameworks provide built-in networks for local testing, automated compilation, and rich debugging tools like stack traces and console logging. Learn to write deployment scripts and manage multiple network configurations for testnets and mainnet.",
      url: "https://hardhat.org/hardhat-runner/docs",
    },
    {
      id: "step-6",
      label: "DApp Frontend",
      tool: "Ethers.js",
      description: "Build responsive web interfaces that communicate with smart contracts using libraries like Ethers.js, wagmi, or viem. Connect your frontend to user wallets, read on-chain data in real-time, and submit transactions that trigger contract functions. This is where users interact with your decentralized application, so focus on clean UX and clear transaction feedback.",
      url: "https://docs.ethers.org/",
    },
    {
      id: "step-7",
      label: "Wallet Integration",
      tool: "wagmi",
      description: "Integrate cryptocurrency wallets like MetaMask, WalletConnect, and Coinbase Wallet to let users sign transactions and authenticate with your DApp. Learn how wallet providers inject providers into the browser, how to request account access, and how to handle chain switching and network detection. Proper wallet integration is critical for a seamless user experience in decentralized applications.",
      url: "https://wagmi.sh/",
    },
    {
      id: "step-8",
      label: "Security & Auditing",
      tool: "Slither",
      description: "Audit smart contracts for vulnerabilities such as reentrancy attacks, integer overflow, access control flaws, and front-running exploits. Use static analysis tools like Slither and Mythril to automatically detect common vulnerability patterns before deployment. Study famous historical hacks to understand real-world attack vectors and implement defensive coding practices to protect user funds.",
      url: "https://crytic.github.io/slither/",
    },
    {
      id: "step-9",
      label: "Testing",
      tool: "Chai",
      description: "Write comprehensive unit tests and integration tests for smart contracts using frameworks like Hardhat with Chai and ethers.js matchers. Test edge cases such as unauthorized access, insufficient balances, and boundary conditions to ensure contracts behave correctly under all scenarios. A well-tested contract is far less likely to contain exploitable bugs when deployed to mainnet.",
      url: "https://www.chaijs.com/",
    },
    {
      id: "step-10",
      label: "IPFS & Decentralized Storage",
      tool: "IPFS",
      description: "Store frontend assets, metadata, and application data on decentralized storage networks like IPFS, Arweave, or Filecoin to eliminate single points of failure. Learn how content addressing works with CIDs to ensure data integrity and how pinning services keep your files permanently available. Decentralized storage ensures your DApp's frontend and metadata remain accessible even if centralized servers go down.",
      url: "https://docs.ipfs.tech/",
    },
    {
      id: "step-11",
      label: "Token Standards",
      tool: "ERC-20/721",
      description: "Implement fungible tokens with ERC-20, non-fungible tokens with ERC-721, and multi-token standards with ERC-1155 to represent assets on-chain. Understand the interface requirements for transfers, approvals, and metadata, and learn how protocols like Uniswap and OpenSea integrate with these standards. Token standards are the building blocks of DeFi, NFTs, and the broader Web3 ecosystem.",
      url: "https://eips.ethereum.org/",
    },
    {
      id: "step-12",
      label: "Gas Optimization",
      tool: "Foundry",
      description: "Reduce transaction costs by optimizing smart contract storage layout, using efficient data types, and minimizing on-chain computation. Learn techniques like packing struct variables, using calldata instead of memory, and leveraging immutable and constant variables to save gas. Profiling gas usage with tools like Foundry's forge snapshot helps you deploy more cost-effective contracts.",
      url: "https://book.getfoundry.sh/",
    },
    {
      id: "step-13",
      label: "Deployment",
      tool: "Hardhat",
      description: "Deploy smart contracts to Ethereum testnets like Sepolia or Goerli for final validation before launching on mainnet using deployment automation tools. Verify your contract source code on block explorers like Etherscan to build user trust and enable on-chain verification. Manage deployment scripts, environment variables, and multi-signature ownership to ensure a smooth and secure production launch.",
      url: "https://hardhat.org/hardhat-runner/docs",
    },
  ],
};
