import { Roadmap } from "../types/roadmap";

export const civilEngineerRoadmap: Roadmap = {
  id: "civil-engineer",
  title: "Civil Engineer",
  description: "Design, build, and maintain infrastructure like bridges, roads, and buildings.",
  introduction: "Civil engineering designs and builds infrastructure like bridges and buildings. Master structural analysis, CAD, materials science, and project management.",
  icon: "🏗️",
  category: "Engineering",
  difficulty: "Advanced",
  estimatedTime: "8-12 months",
  steps: [
    {
      id: "step-1",
      label: "Structural Analysis",
      tool: "SAP2000",
      description: "Learn how to analyze forces, moments, and stresses within structures to ensure safety and stability. Master the principles of statics, dynamics, and mechanics of materials to evaluate how beams, columns, and frames respond to loads.",
      url: "https://www.csiamerica.com/products/sap2000",
    },
    {
      id: "step-2",
      label: "Geotechnical Engineering",
      tool: "PLAXIS",
      description: "Study soil behavior, foundation design, and earth retaining structures. Understand soil mechanics principles including compaction, consolidation, and slope stability to support safe construction on diverse terrain.",
      url: "https://www.bentley.com/software/plaxis/",
    },
    {
      id: "step-3",
      label: "Surveying",
      tool: "AutoCAD Civil 3D",
      description: "Master land measurement techniques using total stations, GPS, and laser scanning to map terrain and boundaries. Learn to create topographic maps, site plans, and construction staking layouts for project development.",
      url: "https://www.autodesk.com/products/civil-3d/",
    },
    {
      id: "step-4",
      label: "Concrete Design",
      tool: "ETABS",
      description: "Design reinforced concrete structures including beams, slabs, columns, and foundations. Learn to apply ACI 318 codes for load combinations, reinforcement detailing, and durability considerations in various exposure conditions.",
      url: "https://www.csiamerica.com/products/etabs",
    },
    {
      id: "step-5",
      label: "Steel Design",
      tool: "AISC Manual",
      description: "Analyze and design steel structures using connections, tension members, compression members, and beams. Master the AISC steel construction manual for selecting appropriate sections and detailing welds and bolted connections.",
      url: "https://www.aisc.org/",
    },
    {
      id: "step-6",
      label: "Transportation Engineering",
      tool: "HCS / Synchro",
      description: "Plan and design roadways, highways, and traffic systems to ensure safe and efficient movement of people and vehicles. Study geometric design, traffic flow theory, pavement design, and public transit planning for urban and rural networks.",
      url: "https://www.hcmsoftware.com/",
    },
    {
      id: "step-7",
      label: "Water Resources",
      tool: "HEC-RAS",
      description: "Model and manage surface water systems including rivers, reservoirs, and stormwater networks. Learn hydrology, hydraulics, floodplain analysis, and water quality management to design sustainable drainage and irrigation systems.",
      url: "https://www.hec.usace.army.mil/software/hec-ras/",
    },
    {
      id: "step-8",
      label: "Environmental Engineering",
      tool: "EPANET",
      description: "Address environmental challenges through water treatment, air pollution control, and waste management systems. Understand regulatory frameworks and design solutions for sustainable infrastructure that minimize ecological impact.",
      url: "https://www.epa.gov/water-research/epanet",
    },
    {
      id: "step-9",
      label: "Construction Management",
      tool: "Primavera P6",
      description: "Plan, schedule, and oversee construction projects from inception to completion. Master project scheduling, cost estimation, quality control, and risk management to deliver projects on time and within budget.",
      url: "https://www.oracle.com/industries/construction-engineering/primavera/",
    },
    {
      id: "step-10",
      label: "Urban Planning",
      tool: "GIS / ArcGIS",
      description: "Analyze land use patterns, zoning regulations, and community development to shape sustainable cities. Integrate transportation networks, public spaces, and infrastructure planning to create livable urban environments.",
      url: "https://www.esri.com/en-us/arcgis/products/arcgis-pro/overview",
    },
    {
      id: "step-11",
      label: "BIM & CAD",
      tool: "Revit / AutoCAD",
      description: "Create intelligent 3D models that integrate architectural, structural, and MEP disciplines for coordinated design. Learn Building Information Modeling workflows for clash detection, quantity takeoffs, and construction documentation.",
      url: "https://www.autodesk.com/products/revit/",
    },
    {
      id: "step-12",
      label: "Project Management",
      tool: "Microsoft Project",
      description: "Lead cross-functional teams to deliver complex infrastructure projects from concept through commissioning. Develop skills in stakeholder communication, procurement, contract administration, and earned value management for professional practice.",
      url: "https://www.microsoft.com/en-us/microsoft-365/project/project-management-software",
    },
  ],
};
