import { Roadmap } from "../types/roadmap";

export const cloudComputingRoadmap: Roadmap = {
  id: "cloud-computing",
  title: "Cloud Computing",
  description: "Deploy, scale, and manage applications on major cloud platforms.",
  introduction: "Cloud computing transforms how businesses deploy and scale applications. Master AWS, Terraform, and Kubernetes to build infrastructure that's resilient, scalable, and cost-efficient.",
  icon: "☁️",
  category: "Infrastructure",
  difficulty: "Advanced",
  estimatedTime: "6-9 months",
  steps: [
    {
      id: "step-1",
      label: "Cloud Fundamentals",
      tool: "AWS",
      description: "Understand the shared responsibility model, global infrastructure (regions, availability zones, edge locations), and core services like compute, storage, and networking. Cloud isn't just someone else's computer — it's a fundamentally different way of thinking about infrastructure.",
      url: "https://docs.aws.amazon.com/gettingstarted/latest/welcome/",
    },
    {
      id: "step-2",
      label: "Linux & Networking",
      tool: "Linux",
      description: "Master the Linux command line, file permissions, process management, and networking basics (DNS, HTTP, TCP/IP, ports). Almost every cloud service runs on Linux — comfort with the terminal is non-negotiable.",
      url: "https://linuxjourney.com/",
    },
    {
      id: "step-3",
      label: "Compute Services",
      tool: "EC2",
      description: "Launch and manage virtual machines with different instance types, storage options, and networking configurations. Learn auto-scaling groups, load balancers, and spot instances for cost optimization.",
      url: "https://docs.aws.amazon.com/ec2/",
    },
    {
      id: "step-4",
      label: "Storage & Databases",
      tool: "S3",
      description: "Store objects with S3 (versioning, lifecycle policies, bucket policies), use EBS for persistent block storage, and RDS for managed relational databases. Understanding storage trade-offs (performance, cost, durability) is critical for architecture decisions.",
      url: "https://docs.aws.amazon.com/s3/",
    },
    {
      id: "step-5",
      label: "Identity & Access",
      tool: "IAM",
      description: "Manage users, groups, roles, and policies with fine-grained permissions. Follow the principle of least privilege and implement MFA. IAM misconfigurations are the #1 cause of cloud security breaches — get this right first.",
      url: "https://docs.aws.amazon.com/iam/",
    },
    {
      id: "step-6",
      label: "Networking",
      tool: "VPC",
      description: "Design virtual private clouds with subnets, route tables, internet gateways, and NAT gateways. Configure security groups and network ACLs. Cloud networking is the backbone of every architecture — mistakes here affect everything.",
      url: "https://docs.aws.amazon.com/vpc/",
    },
    {
      id: "step-7",
      label: "Infrastructure as Code",
      tool: "Terraform",
      description: "Provision and manage cloud resources declaratively with HCL. Learn state management, modules, workspaces, and drift detection. IaC makes your infrastructure repeatable, version-controlled, and auditable.",
      url: "https://developer.hashicorp.com/terraform/docs",
    },
    {
      id: "step-8",
      label: "Containers",
      tool: "Docker",
      description: "Package applications with their dependencies into portable, isolated containers. Learn Dockerfiles, multi-stage builds, volumes, and networking. Containers solve the 'works on my machine' problem and are the unit of deployment in modern cloud.",
      url: "https://docs.docker.com/",
    },
    {
      id: "step-9",
      label: "Orchestration",
      tool: "Kubernetes",
      description: "Deploy and manage containerized applications at scale with pods, services, deployments, and ingress controllers. Learn about rolling updates, horizontal pod autoscaling, and self-healing. Kubernetes is the operating system of the cloud.",
      url: "https://kubernetes.io/docs/",
    },
    {
      id: "step-10",
      label: "Serverless",
      tool: "AWS Lambda",
      description: "Run code without managing servers using event-driven functions. Combine Lambda with API Gateway, DynamoDB, and S3 for fully serverless architectures. Serverless eliminates operational overhead but requires understanding cold starts and execution limits.",
      url: "https://docs.aws.amazon.com/lambda/",
    },
    {
      id: "step-11",
      label: "CI/CD Pipelines",
      tool: "GitHub Actions",
      description: "Automate building, testing, and deploying infrastructure and applications. Learn pipeline stages, caching, secrets management, and rollback strategies. CI/CD is how you ship changes safely and frequently.",
      url: "https://docs.github.com/en/actions",
    },
    {
      id: "step-12",
      label: "Monitoring & Observability",
      tool: "CloudWatch",
      description: "Collect metrics, logs, and traces to understand system behavior. Set up alarms, dashboards, and anomaly detection. You can't improve what you can't measure — observability is how you know when things go wrong before your users do.",
      url: "https://docs.aws.amazon.com/cloudwatch/",
    },
    {
      id: "step-13",
      label: "Security & Compliance",
      tool: "AWS Config",
      description: "Implement security best practices with encryption at rest and in transit, VPC flow logs, GuardDuty threat detection, and compliance auditing. Cloud security is a shared responsibility — know your side of the bargain.",
      url: "https://docs.aws.amazon.com/config/",
    },
    {
      id: "step-14",
      label: "Cost Optimization",
      tool: "AWS Cost Explorer",
      description: "Monitor spending with cost allocation tags, reserved instances, savings plans, and right-sizing recommendations. Cloud costs can spiral without governance — FinOps is a critical skill for any cloud engineer.",
      url: "https://aws.amazon.com/aws-cost-management/",
    },
  ],
};
