import { Roadmap } from "../types/roadmap";

export const cloudArchitectRoadmap: Roadmap = {
  id: "cloud-architect",
  title: "Cloud Architect",
  description: "Design scalable, secure, and cost-optimized cloud infrastructure solutions.",
  introduction: "Cloud architecture designs scalable, secure, and cost-optimized infrastructure. Learn AWS services, networking patterns, IaC with Terraform, and migration strategies.",
  icon: "☁️",
  category: "Infrastructure",
  difficulty: "Advanced",
  estimatedTime: "8-12 months",
  steps: [
    {
      id: "step-1",
      label: "Cloud Platforms",
      tool: "AWS",
      description: "Gain deep expertise in core cloud provider services across compute, storage, and databases. Understand how to select the right service for each workload by comparing pricing models, performance tiers, and managed versus self-hosted options. Mastery of platforms like AWS, Azure, or GCP is the foundation for every architectural decision you will make.",
      url: "https://docs.aws.amazon.com/gettingstarted/latest/welcome/",
    },
    {
      id: "step-2",
      label: "Networking",
      tool: "VPC",
      description: "Design secure and performant virtual networks using VPCs, subnets, route tables, and NAT gateways. Learn how to implement public and private subnet strategies, configure network ACLs and security groups, and connect on-premises environments via VPN or Direct Connect. A well-architected network is critical for isolating workloads, controlling traffic flow, and ensuring low-latency connectivity.",
      url: "https://docs.aws.amazon.com/vpc/",
    },
    {
      id: "step-3",
      label: "Architecture Patterns",
      tool: "Well-Architected",
      description: "Study and apply proven architectural patterns such as microservices, event-driven architectures, and the strangler fig pattern for modernizing monoliths. Understand trade-offs between synchronous and asynchronous communication, eventual consistency, and data partitioning strategies. These patterns form the blueprint for building systems that are resilient, performant, and maintainable at scale.",
      url: "https://aws.amazon.com/architecture/well-architected/",
    },
    {
      id: "step-4",
      label: "Cost Optimization",
      tool: "AWS Cost Explorer",
      description: "Implement strategies to monitor, analyze, and reduce cloud spending without sacrificing performance or reliability. Leverage reserved instances, savings plans, spot instances, and right-sizing recommendations to optimize compute costs. Build cost-aware architectures by implementing tagging policies, budgets, and automated alerts to prevent unexpected billing overruns.",
      url: "https://docs.aws.amazon.com/costmanagement/latest/userguide/what-is-cost-management.html",
    },
    {
      id: "step-5",
      label: "Security",
      tool: "AWS IAM",
      description: "Design and enforce identity and access management policies following the principle of least privilege. Implement multi-factor authentication, role-based access control, and service control policies to protect cloud resources. Integrate security into every layer of the architecture including encryption at rest and in transit, secrets management, and continuous compliance monitoring.",
      url: "https://docs.aws.amazon.com/iam/",
    },
    {
      id: "step-6",
      label: "IaC",
      tool: "Terraform",
      description: "Automate infrastructure provisioning and management using Infrastructure as Code tools like Terraform or CloudFormation. Write modular, reusable, and version-controlled templates that enable consistent deployments across environments. Adopt practices such as state management, drift detection, and plan/apply workflows to maintain infrastructure reliability and auditability.",
      url: "https://developer.hashicorp.com/terraform/docs",
    },
    {
      id: "step-7",
      label: "Migration",
      tool: "AWS Migration Hub",
      description: "Plan and execute cloud migration strategies using frameworks like the 7 Rs to assess legacy workloads. Evaluate the right migration approach for each application whether rehosting, replatforming, or refactoring based on complexity and business value. Coordinate large-scale migrations using tools for discovery, assessment, and progressive cutover to minimize downtime and risk.",
      url: "https://docs.aws.amazon.com/migrationhub/",
    },
    {
      id: "step-8",
      label: "Disaster Recovery",
      tool: "AWS Backup",
      description: "Design disaster recovery strategies that meet your organization's recovery time and recovery point objectives. Implement multi-region failover, cross-region replication, and automated backup restoration to ensure business continuity during outages. Choose the right DR topology from backup and restore to active-active based on cost tolerance and acceptable downtime.",
      url: "https://docs.aws.amazon.com/prescriptive-guidance/latest/defined-state-strategies-dr/dr-strategies-overview.html",
    },
    {
      id: "step-9",
      label: "Serverless Architecture",
      tool: "AWS Lambda",
      description: "Leverage serverless services like Lambda, API Gateway, DynamoDB, and Step Functions to build event-driven applications without managing servers. Understand cold start optimization, concurrency limits, and the cost model of pay-per-request to design efficient serverless systems. Serverless architectures reduce operational overhead and scale automatically, but require careful consideration of state management and vendor lock-in.",
      url: "https://docs.aws.amazon.com/lambda/latest/dg/welcome.html",
    },
    {
      id: "step-10",
      label: "Multi-Cloud Strategy",
      tool: "Terraform",
      description: "Develop strategies for operating across multiple cloud providers to avoid vendor lock-in and leverage best-of-breed services. Design cloud-agnostic architectures using abstraction layers, containers, and orchestration tools like Kubernetes to enable portability. Evaluate trade-offs of multi-cloud approaches including increased operational complexity, networking challenges, and unified identity management.",
      url: "https://www.hashicorp.com/blog/multi-cloud-strategy",
    },
    {
      id: "step-11",
      label: "Governance",
      tool: "AWS Config",
      description: "Establish organizational policies and guardrails that enforce compliance, security, and operational standards across cloud accounts. Use service control policies, resource policies, and automated compliance rules to prevent misconfigurations before they reach production. Implement cost governance, tag enforcement, and account vending processes to maintain control as your cloud footprint scales.",
      url: "https://docs.aws.amazon.com/config/latest/developerguide/WhatIsConfig.html",
    },
    {
      id: "step-12",
      label: "Well-Architected Framework",
      tool: "AWS Well-Architected",
      description: "Apply the six pillars of the Well-Architected Framework including operational excellence, security, reliability, performance efficiency, cost optimization, and sustainability to evaluate and improve workloads. Conduct regular well-architected reviews to identify risks and develop improvement plans aligned with business priorities. Use the framework as a continuous improvement tool rather than a one-time checklist to evolve your architecture as requirements change.",
      url: "https://aws.amazon.com/architecture/well-architected/",
    },
  ],
};
