import { Roadmap } from "../types/roadmap";

export const computationalBiologistRoadmap: Roadmap = {
  id: "computational-biologist",
  title: "Computational Biologist",
  description: "Bridge biology and computation to solve complex life science problems.",
  introduction: "Computational biology combines biological knowledge with programming and mathematical modeling to understand living systems. Learn molecular biology, bioinformatics, sequence analysis, structural biology, systems biology, and high-performance computing to tackle challenges in genomics, proteomics, and drug discovery.",
  icon: "🔬",
  category: "Science",
  difficulty: "Expert",
  estimatedTime: "10-14 months",
  steps: [
    {
      id: "step-1",
      label: "Molecular Biology",
      tool: "Biopython",
      description: "Molecular biology provides the foundational understanding of DNA replication, transcription, translation, and gene regulation that underpins all computational analysis. Learn the central dogma, chromatin structure, epigenetic modifications, and signaling pathways to interpret biological data in context. Use Biopython to parse FASTA, GenBank, and FASTQ files, query NCBI databases via Entrez, and build automated pipelines for sequence retrieval and annotation.",
      url: "https://biopython.org/wiki/Documentation",
    },
    {
      id: "step-2",
      label: "Bioinformatics",
      tool: "Galaxy",
      description: "Bioinformatics applies computational tools to analyze biological data at scale, from raw sequencing reads to assembled genomes. Master quality control with FastQC, read alignment with Bowtie2 or STAR, and genome assembly with SPAdes to process high-throughput sequencing experiments. Use Galaxy, a web-based platform, to build reproducible workflows without writing code and to share analyses with collaborators who lack programming expertise.",
      url: "https://galaxyproject.org/",
    },
    {
      id: "step-3",
      label: "Sequence Analysis",
      tool: "BLAST",
      description: "Sequence analysis involves comparing DNA and protein sequences to identify homologs, conserved domains, and functional elements across organisms. Learn nucleotide and protein BLAST to search local and remote databases, interpret e-values and bit scores, and construct multiple sequence alignments with Clustal Omega or MUSCLE. Analyze sequence motifs, coding potential, and evolutionary conservation to annotate newly sequenced genomes and predict gene function.",
      url: "https://blast.ncbi.nlm.nih.gov/",
    },
    {
      id: "step-4",
      label: "Structural Biology",
      tool: "PyMOL",
      description: "Structural biology focuses on the three-dimensional architecture of proteins, nucleic acids, and macromolecular complexes that determine biological function. Use PyMOL and ChimeraX to visualize crystal structures, cryo-EM maps, and NMR ensembles from the Protein Data Bank. Perform structural alignment, surface analysis, and mutation mapping to understand how sequence changes alter protein folding, ligand binding, and molecular interactions.",
      url: "https://pymol.org/",
    },
    {
      id: "step-5",
      label: "Protein Structure Prediction",
      tool: "AlphaFold",
      description: "Protein structure prediction uses machine learning and physics-based methods to determine the three-dimensional conformation of proteins from sequence alone. Run AlphaFold2 to predict structures with near-experimental accuracy for proteins lacking solved structures, and validate models with Ramachandran plots and pLDDT scores. Explore folding pathways with Rosetta and molecular dynamics simulations to understand how proteins sample conformational landscapes and misfold in disease.",
      url: "https://alphafold.ebi.ac.uk/",
    },
    {
      id: "step-6",
      label: "Phylogenetics",
      tool: "RAxML",
      description: "Phylogenetics reconstructs evolutionary relationships between organisms, genes, and proteins using sequence similarity and substitution models. Build multiple sequence alignments, select appropriate models of evolution with ModelTest-NG, and infer phylogenetic trees with RAxML or MrBayes. Interpret branch support values, identify horizontal gene transfer events, and perform molecular clock analysis to date divergence times across lineages.",
      url: "https://cme.h-its.org/exelixis/web/software/raxml/",
    },
    {
      id: "step-7",
      label: "Systems Biology",
      tool: "COPASI",
      description: "Systems biology takes a holistic approach to understanding biological networks by integrating molecular data into mathematical models of cellular processes. Learn ordinary differential equations, stochastic simulation, and constraint-based modeling to represent metabolic, signaling, and gene regulatory networks. Use COPASI to build and simulate biochemical reaction networks, perform sensitivity analyses, and fit model parameters to experimental time-course data.",
      url: "https://copasi.org/",
    },
    {
      id: "step-8",
      label: "Network Biology",
      tool: "Cytoscape",
      description: "Network biology analyzes protein-protein interactions, metabolic pathways, and gene regulatory networks to uncover emergent properties of biological systems. Construct interaction networks from high-throughput data, identify hub genes and key regulators through topological analysis, and detect densely connected modules with clustering algorithms. Use Cytoscape to visualize complex networks, overlay expression data, and integrate with pathway databases like KEGG and Reactome for functional interpretation.",
      url: "https://cytoscape.org/",
    },
    {
      id: "step-9",
      label: "Data Visualization",
      tool: "matplotlib",
      description: "Data visualization transforms complex biological datasets into interpretable figures that communicate patterns, relationships, and statistical significance. Create publication-quality plots with matplotlib and seaborn, including volcano plots for differential expression, PCA and UMAP scatter plots for dimensionality reduction, and heatmaps for expression profiling. Master color theory, annotation techniques, and multi-panel figure composition to present computational results clearly to both bioinformaticians and experimental biologists.",
      url: "https://matplotlib.org/",
    },
    {
      id: "step-10",
      label: "Drug Target Identification",
      tool: "AutoDock",
      description: "Drug target identification leverages genomic, transcriptomic, and proteomic data to discover proteins that can be therapeutically modulated by small molecules. Prioritize targets using differential expression analysis, network centrality measures, druggability assessments, and genetic evidence from genome-wide association studies. Perform molecular docking with AutoDock Vina to predict binding affinities, screen virtual compound libraries, and assess ADMET properties to advance candidates toward experimental validation.",
      url: "http://vina.scripps.edu/",
    },
    {
      id: "step-11",
      label: "High-Performance Computing",
      tool: "Slurm",
      description: "High-performance computing provides the infrastructure to run computationally intensive analyses on large-scale biological datasets that exceed the capacity of personal machines. Learn to submit and manage jobs on HPC clusters using Slurm, parallelize workflows with GNU Parallel, and optimize memory usage for whole-genome sequencing pipelines. Write efficient shell scripts and Python code using multiprocessing and vectorized operations to reduce runtime from days to hours on datasets with millions of sequences.",
      url: "https://slurm.schedmd.com/",
    },
    {
      id: "step-12",
      label: "Reproducible Research",
      tool: "Nextflow",
      description: "Reproducible research ensures that computational analyses can be independently verified, re-run, and extended by other scientists using transparent and well-documented methods. Package workflows with Nextflow or Snakemake to create portable pipelines that run identically across different computing environments using conda or Docker containers. Maintain version control with Git, document every parameter and decision in README files, and archive code and data with Zenodo DOIs to meet journal and funder reproducibility requirements.",
      url: "https://www.nextflow.io/",
    },
    {
      id: "step-13",
      label: "Machine Learning in Biology",
      tool: "PyTorch",
      description: "Machine learning applies statistical models to biological data for tasks such as classifying cell types, predicting gene expression, and identifying disease biomarkers from high-dimensional datasets. Build and train neural networks with PyTorch or TensorFlow for image classification of microscopy data, sequence-to-function models for regulatory genomics, and graph neural networks for molecular property prediction. Evaluate model performance with appropriate cross-validation strategies, interpret predictions using attention mechanisms and SHAP values, and avoid overfitting on small biological datasets.",
      url: "https://pytorch.org/",
    },
  ],
};
