import { Roadmap } from "../types/roadmap";

export const computerGraphicsProgrammerRoadmap: Roadmap = {
  id: "computer-graphics-programmer",
  title: "Computer Graphics Programmer",
  description: "Develop rendering engines, shaders, and real-time graphics pipelines.",
  introduction: "Computer graphics programming develops rendering engines and shaders. Master linear algebra, C++, Vulkan, GLSL, and real-time rendering techniques.",
  icon: "🖼️",
  category: "Engineering",
  difficulty: "Advanced",
  estimatedTime: "8-12 months",
  steps: [
    {
      id: "step-1",
      label: "Linear Algebra",
      tool: "Mathematics",
      description: "Linear algebra is the foundation of all 3D graphics. Vectors, matrices, and quaternions define how objects move, rotate, and scale in virtual space. A strong grasp of dot products, cross products, and matrix multiplication is essential for every rendering task ahead.",
      url: "https://www.khanacademy.org/math/linear-algebra",
    },
    {
      id: "step-2",
      label: "C++",
      tool: "C++",
      description: "C++ is the dominant language for building high-performance graphics engines and rendering pipelines. Its manual memory management, templates, and zero-overhead abstractions give you precise control over hardware resources. Understanding modern C++ features like smart pointers, move semantics, and compile-time computation is critical.",
      url: "https://isocpp.org/get-started",
    },
    {
      id: "step-3",
      label: "Graphics API",
      tool: "Vulkan",
      description: "Graphics APIs like Vulkan and OpenGL provide the interface between your code and the GPU hardware. Vulkan offers explicit, low-level control over the rendering pipeline, command buffers, and memory allocation, enabling maximum performance. Start with OpenGL for accessible fundamentals, then graduate to Vulkan for production-grade engines.",
      url: "https://vulkan-tutorial.com/",
    },
    {
      id: "step-4",
      label: "Shaders",
      tool: "GLSL",
      description: "Shaders are small programs that run directly on the GPU to determine how vertices and pixels are processed. GLSL (OpenGL Shading Language) is used to write vertex, fragment, and geometry shaders that control everything from geometry placement to final pixel color. Mastering shader authoring unlocks effects like lighting, reflections, and post-processing.",
      url: "https://www.khronos.org/opengl/wiki/OpenGL_Shading_Language",
    },
    {
      id: "step-5",
      label: "3D Math",
      tool: "GLM",
      description: "GLM (OpenGL Mathematics) is a header-only C++ library that provides GPU-friendly math types and functions. It implements vectors, matrices, quaternions, and transformation operations used throughout graphics programming. Using GLM simplifies tasks like constructing view and projection matrices, implementing billboard rotations, and handling interpolation.",
      url: "https://github.com/g-truc/glm",
    },
    {
      id: "step-6",
      label: "Real-Time Rendering",
      tool: "Rasterization",
      description: "Real-time rendering focuses on producing interactive frame rates through rasterization-based techniques. You will learn to manage draw calls, implement frustum culling, handle depth buffering, and optimize batched rendering for complex scenes. Understanding the GPU pipeline stages from vertex input to fragment output is crucial for building performant engines.",
      url: "https://learnopengl.com/",
    },
    {
      id: "step-7",
      label: "Ray Tracing",
      tool: "OptiX",
      description: "Ray tracing simulates the physical behavior of light by casting rays from the camera into the scene. It produces accurate reflections, refractions, soft shadows, and global illumination that are difficult to achieve with rasterization alone. NVIDIA OptiX and Vulkan Ray Tracing extensions enable hardware-accelerated ray tracing on modern GPUs.",
      url: "https://developer.nvidia.com/optix",
    },
    {
      id: "step-8",
      label: "Physics-Based Rendering",
      tool: "PBR",
      description: "Physics-based rendering (PBR) models how light interacts with surfaces using physically accurate material properties. Concepts like roughness, metallic, and albedo maps work with energy conservation principles to produce realistic materials under any lighting condition. PBR is the standard in modern game engines, film, and interactive visualization.",
      url: "https://learnopengl.com/PBR/Lighting",
    },
    {
      id: "step-9",
      label: "GPU Programming",
      tool: "CUDA",
      description: "GPU programming extends beyond graphics by using the parallel compute capabilities of modern GPUs. CUDA and compute shaders allow you to run thousands of threads simultaneously for tasks like physics simulation, particle systems, and image processing. Understanding thread hierarchies, shared memory, and synchronization is key to harnessing GPU power effectively.",
      url: "https://developer.nvidia.com/cuda-zone",
    },
    {
      id: "step-10",
      label: "Geometry Processing",
      tool: "Mesh",
      description: "Geometry processing involves creating, modifying, and optimizing 3D mesh data for rendering. Topics include mesh simplification, level-of-detail (LOD) systems, tessellation, and procedural geometry generation. Efficient geometry pipelines reduce memory bandwidth and vertex processing overhead, which is essential for rendering large-scale environments.",
      url: "https://learnopengl.com/Model-Loading",
    },
    {
      id: "step-11",
      label: "Animation Systems",
      tool: "Skeletal",
      description: "Animation systems bring characters and objects to life through keyframe interpolation, skeletal animation, and blending techniques. Skinned mesh deformation uses bone hierarchies and weight painting to create smooth, realistic motion from stored animation data. Advanced topics include inverse kinematics, motion blending, and animation state machines.",
      url: "https://www.aura-net.com/opengl-skeletal-animation-tutorial-1/",
    },
    {
      id: "step-12",
      label: "Performance Optimization",
      tool: "Profiling",
      description: "Performance optimization ensures your rendering engine maintains smooth frame rates under demanding workloads. Profiling tools like RenderDoc, NVIDIA Nsight, and GPU timers help identify bottlenecks in CPU submission, GPU execution, and memory transfer. Techniques such as occlusion culling, texture streaming, and shader precompilation are essential for production-quality applications.",
      url: "https://renderdoc.org/",
    },
  ],
};
