import { Roadmap } from "../types/roadmap";

export const contentStrategistRoadmap: Roadmap = {
  id: "content-strategist",
  title: "Content Strategist",
  description: "Plan, create, and manage content that drives audience engagement and conversions.",
  introduction: "Content strategy plans and manages content that drives engagement. Learn content marketing, SEO, writing, content planning, analytics, distribution, and more.",
  icon: "📰",
  category: "Business",
  difficulty: "Beginner",
  estimatedTime: "3-5 months",
  steps: [
    {
      id: "step-1",
      label: "Content Marketing",
      tool: "HubSpot",
      description: "Content marketing is the foundation of any successful strategy, focusing on creating valuable, relevant content to attract a clearly defined audience. Learn inbound marketing principles, understand the content funnel from awareness to conversion, and develop frameworks for aligning content with business goals. Master the art of storytelling that builds trust and positions your brand as an industry authority.",
      url: "https://academy.hubspot.com/",
    },
    {
      id: "step-2",
      label: "SEO",
      tool: "Ahrefs",
      description: "Search engine optimization ensures your content is discoverable by the right audience at the right time. Learn keyword research techniques to identify high-intent topics, understand on-page SEO fundamentals like meta tags and internal linking, and study how search algorithms evaluate content quality. Explore technical SEO concepts such as site speed, structured data, and crawlability to maximize your content's organic reach.",
      url: "https://ahrefs.com/blog/seo-basics/",
    },
    {
      id: "step-3",
      label: "Writing & Copywriting",
      tool: "Copywriting",
      description: "Strong writing skills separate good content from great content, and copywriting drives readers to take action. Practice crafting compelling headlines that demand attention, persuasive calls-to-action that convert, and long-form content that educates and engages. Study headline formulas, emotional triggers, and persuasive writing frameworks like AIDA and PAS to elevate every piece of content you produce.",
      url: "https://copyblogger.com/copywriting-101/",
    },
    {
      id: "step-4",
      label: "Content Planning",
      tool: "Notion",
      description: "Content planning transforms scattered ideas into a cohesive strategy with clear priorities and timelines. Build editorial workflows that streamline the process from ideation to publication, and create content briefs that align writers, designers, and stakeholders. Learn to balance evergreen content with trending topics, and develop topic clusters that strengthen topical authority across your content ecosystem.",
      url: "https://www.notion.so/help",
    },
    {
      id: "step-5",
      label: "Analytics",
      tool: "Google Analytics",
      description: "Data-driven decision making is what separates strategic content creators from those who publish blindly. Learn to interpret traffic sources, engagement metrics, bounce rates, and conversion paths to understand what resonates with your audience. Master tools like Google Analytics and Looker Studio to build dashboards that track KPIs, measure ROI on content initiatives, and identify opportunities for optimization.",
      url: "https://analytics.google.com/analytics/academy/",
    },
    {
      id: "step-6",
      label: "Distribution",
      tool: "Buffer",
      description: "Even the best content fails without a strategic distribution plan that puts it in front of the right people. Learn to identify which channels your audience uses most, develop platform-specific content adaptations, and build a multi-channel distribution strategy. Explore organic and paid distribution tactics, including social media scheduling, email marketing, syndication partnerships, and community engagement.",
      url: "https://buffer.com/resources/",
    },
    {
      id: "step-7",
      label: "Content Audit",
      tool: "Screaming Frog",
      description: "A content audit reveals what is working, what is outdated, and where gaps exist in your content library. Systematically inventory all existing content assets, evaluate them against performance metrics and business objectives, and categorize them into actions like update, consolidate, or remove. Use audit findings to inform future strategy, prioritize high-impact improvements, and ensure your content ecosystem remains fresh and relevant.",
      url: "https://www.screamingfrog.co.uk/",
    },
    {
      id: "step-8",
      label: "User Personas",
      tool: "Miro",
      description: "User personas ensure every piece of content speaks directly to the needs, pain points, and motivations of your target audience. Conduct audience research through surveys, interviews, and analytics to build detailed profiles that include demographics, goals, challenges, and content preferences. Use personas to guide tone, format, and topic selection so your content consistently resonates with the people who matter most.",
      url: "https://miro.com/",
    },
    {
      id: "step-9",
      label: "Content Calendar",
      tool: "Trello",
      description: "A content calendar brings structure and consistency to your publishing cadence, ensuring you never miss an opportunity. Plan content weeks or months in advance, coordinate cross-functional deadlines, and align publishing schedules with product launches, seasonal trends, and industry events. Build a calendar that balances content types and formats while remaining flexible enough to adapt to breaking news and timely opportunities.",
      url: "https://trello.com/",
    },
    {
      id: "step-10",
      label: "Brand Voice",
      tool: "Grammarly",
      description: "A consistent brand voice builds recognition, trust, and emotional connection with your audience across every touchpoint. Define your brand's personality, tone, and vocabulary guidelines, and create a style guide that writers can reference to maintain consistency. Study how leading brands differentiate through voice, and practice adapting tone for different contexts while preserving the core brand identity.",
      url: "https://www.grammarly.com/",
    },
    {
      id: "step-11",
      label: "A/B Testing",
      tool: "Optimizely",
      description: "A/B testing removes guesswork from content decisions by letting real user behavior guide your choices. Test variations of headlines, CTAs, layouts, and messaging to discover what drives the highest engagement and conversion rates. Learn to design statistically valid experiments, interpret results accurately, and implement winning variations that compound performance improvements over time.",
      url: "https://www.optimizely.com/",
    },
    {
      id: "step-12",
      label: "Content Operations",
      tool: "Asana",
      description: "Content operations establish the processes, tools, and governance that allow content teams to scale efficiently without sacrificing quality. Build workflows for content creation, review, approval, and publishing that reduce bottlenecks and improve collaboration. Implement content management systems, establish editorial standards, and create feedback loops that drive continuous improvement across your entire content operation.",
      url: "https://asana.com/",
    },
  ],
};
