import { Roadmap } from "../types/roadmap";

export const cybersecurityArchitectRoadmap: Roadmap = {
  id: "cybersecurity-architect",
  title: "Cybersecurity Architect",
  description: "Design and implement enterprise-wide security architectures and frameworks.",
  introduction: "Cybersecurity architecture designs enterprise-wide security frameworks. Master zero-trust architecture, cloud security, identity management, and threat modeling for comprehensive protection.",
  icon: "🏛️",
  category: "Security",
  difficulty: "Expert",
  estimatedTime: "10-16 months",
  steps: [
    {
      id: "step-1",
      label: "Security Fundamentals",
      tool: "CompTIA Security+",
      description: "Build a solid foundation in core security concepts including the CIA triad, defense-in-depth, and least privilege principles. Understand common attack vectors such as phishing, social engineering, malware, and denial-of-service to recognize threats early. Study cryptographic basics, network protocols, and risk management to form the bedrock of all advanced security architecture decisions.",
      url: "https://www.comptia.org/certifications/security",
    },
    {
      id: "step-2",
      label: "Network Architecture",
      tool: "Firewalls",
      description: "Design segmented network architectures using VLANs, DMZs, and microsegmentation to contain lateral movement. Configure next-generation firewalls with deep packet inspection, intrusion prevention systems, and application-layer filtering. Implement network monitoring with tools like Zeek and Suricata to maintain visibility across east-west and north-south traffic flows.",
      url: "https://www.paloaltonetworks.com/network-security",
    },
    {
      id: "step-3",
      label: "Cloud Security",
      tool: "AWS Security",
      description: "Implement cloud-native security controls across IaaS, PaaS, and SaaS environments using shared responsibility models. Configure IAM policies, security groups, encryption at rest and in transit, and logging with CloudTrail and GuardDuty. Design multi-account strategies, landing zones, and cloud security posture management to maintain governance at scale.",
      url: "https://docs.aws.amazon.com/security/",
    },
    {
      id: "step-4",
      label: "Identity & Access Management",
      tool: "Okta",
      description: "Architect centralized identity solutions with single sign-on, multi-factor authentication, and adaptive risk-based access policies. Implement the principle of least privilege using role-based and attribute-based access control models across all enterprise systems. Integrate directory services, privileged access management, and just-in-time provisioning to reduce identity sprawl and credential exposure.",
      url: "https://developer.okta.com/docs/",
    },
    {
      id: "step-5",
      label: "Threat Modeling (STRIDE)",
      tool: "STRIDE",
      description: "Apply the STRIDE framework to systematically identify Spoofing, Tampering, Repudiation, Information Disclosure, Denial of Service, and Elevation of Privilege threats. Create data flow diagrams and trust boundaries to map attack surfaces for every system component. Translate threat models into actionable mitigations and security requirements that drive architectural and design decisions.",
      url: "https://docs.microsoft.com/en-us/azure/security/threat-modeling-tool-overview",
    },
    {
      id: "step-6",
      label: "Security Frameworks (NIST)",
      tool: "NIST CSF",
      description: "Adopt the NIST Cybersecurity Framework to organize security activities across Identify, Protect, Detect, Respond, and Recover functions. Map organizational controls to NIST SP 800-53 and conduct gap analyses against mature baselines. Use framework-driven risk assessments to prioritize investments and demonstrate security posture improvement to executive leadership and auditors.",
      url: "https://www.nist.gov/cyberframework",
    },
    {
      id: "step-7",
      label: "Zero Trust Architecture",
      tool: "BeyondCorp",
      description: "Design zero-trust networks that assume no implicit trust regardless of network location, identity, or device posture. Implement continuous verification through identity-aware proxies, device attestation, and microsegmented access policies. Reference Google BeyondCorp and NIST SP 800-207 to build architectures that validate every request before granting access to any resource.",
      url: "https://cloud.google.com/beyondcorp",
    },
    {
      id: "step-8",
      label: "Security Architecture Patterns",
      tool: "Threat-informed Defense",
      description: "Apply proven architectural patterns including software-defined perimeters, secure access service edge, and defense-in-depth layering. Evaluate trade-offs between centralized and decentralized security controls based on organizational risk tolerance and operational complexity. Design resilient architectures with fail-secure mechanisms, redundancy, and graceful degradation under attack conditions.",
      url: "https://www.sans.org/white-papers/threat-informed-defense/",
    },
    {
      id: "step-9",
      label: "Cryptography",
      tool: "OpenSSL",
      description: "Design cryptographic systems using symmetric and asymmetric algorithms, hashing, digital signatures, and key exchange protocols. Implement TLS 1.3, certificate lifecycle management, and hardware security modules for root key protection. Understand post-quantum cryptography standards and plan migration strategies to resist future quantum computing threats to current algorithms.",
      url: "https://www.openssl.org/docs/",
    },
    {
      id: "step-10",
      label: "Compliance & Governance",
      tool: "GRC Platforms",
      description: "Navigate regulatory landscapes including GDPR, HIPAA, PCI DSS, SOX, and industry-specific compliance mandates. Build governance programs with risk registers, control libraries, audit trails, and continuous compliance monitoring dashboards. Translate legal and regulatory requirements into technical controls and security policies that auditors can validate and engineers can implement.",
      url: "https://www.sailpoint.com/identity-library/what-is-governance-risk-compliance",
    },
    {
      id: "step-11",
      label: "Security Automation",
      tool: "SOAR",
      description: "Orchestrate security operations using SOAR platforms to automate playbooks for alert triage, enrichment, and response. Integrate SIEM, EDR, threat intelligence, and ticketing systems into unified automated workflows that reduce mean time to respond. Build custom detection rules and automated containment actions to handle high-volume alerts without requiring manual analyst intervention.",
      url: "https://www.paloaltonetworks.com/cyberpedia/what-is-soar/",
    },
    {
      id: "step-12",
      label: "Incident Response Planning",
      tool: "TheHive",
      description: "Develop comprehensive incident response plans covering preparation, detection, containment, eradication, recovery, and lessons learned phases. Create runbooks and tabletop exercises to ensure cross-functional teams can execute response procedures under pressure. Establish communication protocols, escalation matrices, and forensic evidence preservation procedures for legal and regulatory accountability.",
      url: "https://docs.strangebee.com/thehive/",
    },
  ],
};
