import { Roadmap } from "../types/roadmap";

export const cybersecurityRoadmap: Roadmap = {
  id: "cybersecurity",
  title: "Cybersecurity",
  description: "Protect systems, networks, and data from digital attacks and vulnerabilities.",
  introduction: "Cybersecurity protects systems and data from digital threats. This roadmap covers networking, cryptography, penetration testing, and compliance to build comprehensive defense skills.",
  icon: "🛡️",
  category: "Security",
  difficulty: "Advanced",
  estimatedTime: "6-12 months",
  steps: [
    {
      id: "step-1",
      label: "Networking Fundamentals",
      tool: "TCP/IP",
      description: "Understand the OSI model, TCP/IP stack, DNS, HTTP/S, and how data flows across networks. Learn about ports, protocols, and packet structure. You can't defend what you don't understand — networking is the battlefield of cybersecurity.",
      url: "https://www.cloudflare.com/learning/networking/",
    },
    {
      id: "step-2",
      label: "Linux Administration",
      tool: "Linux",
      description: "Master the Linux command line, file system hierarchy, permissions, process management, and service configuration. Most servers run Linux — penetration testers and defenders alike need deep Linux knowledge.",
      url: "https://linuxjourney.com/",
    },
    {
      id: "step-3",
      label: "Windows Security",
      tool: "Windows",
      description: "Understand Active Directory, Group Policy, Windows Registry, event logging, and PowerShell for security automation. Enterprise environments are predominantly Windows — ignoring it leaves a massive blind spot.",
      url: "https://learn.microsoft.com/en-us/windows/security/",
    },
    {
      id: "step-4",
      label: "Cryptography",
      tool: "OpenSSL",
      description: "Learn symmetric and asymmetric encryption, hashing algorithms (SHA-256), digital certificates, TLS handshakes, and key management. Cryptography is the mathematical foundation of all security — understand it deeply.",
      url: "https://www.crypto101.io/",
    },
    {
      id: "step-5",
      label: "Web Application Security",
      tool: "OWASP",
      description: "Study the OWASP Top 10: SQL injection, XSS, CSRF, broken authentication, and more. Learn to identify and exploit web vulnerabilities using tools like Burp Suite. Web apps are the most common attack surface in modern organizations.",
      url: "https://owasp.org/www-project-top-ten/",
    },
    {
      id: "step-6",
      label: "Vulnerability Scanning",
      tool: "Nessus",
      description: "Scan networks and systems for known vulnerabilities, misconfigurations, and missing patches. Interpret scan results and prioritize remediation based on risk. Automated scanning catches the low-hanging fruit so you can focus on complex threats.",
      url: "https://www.tenable.com/products/nessus",
    },
    {
      id: "step-7",
      label: "Penetration Testing",
      tool: "Metasploit",
      description: "Simulate real-world attacks with exploitation frameworks. Learn the penetration testing methodology: reconnaissance, scanning, exploitation, post-exploitation, and reporting. Understanding offensive techniques makes you a better defender.",
      url: "https://docs.metasploit.com/",
    },
    {
      id: "step-8",
      label: "Network Analysis",
      tool: "Wireshark",
      description: "Capture and analyze network traffic to detect anomalies, malware communication, and data exfiltration. Learn packet dissection, protocol analysis, and traffic filtering. Wireshark gives you visibility into what's actually happening on the wire.",
      url: "https://www.wireshark.org/docs/",
    },
    {
      id: "step-9",
      label: "SIEM & Log Analysis",
      tool: "Splunk",
      description: "Aggregate logs from multiple sources, create correlation rules, and build detection dashboards. Learn to write SPL queries for threat hunting. SIEM is the central nervous system of a security operations center.",
      url: "https://docs.splunk.com/",
    },
    {
      id: "step-10",
      label: "Incident Response",
      tool: "SANS",
      description: "Follow structured incident response procedures: preparation, identification, containment, eradication, recovery, and lessons learned. Practice with tabletop exercises and forensic analysis. How you respond to incidents defines your security posture more than prevention alone.",
      url: "https://www.sans.org/white-papers/incident-handlers-handbook/",
    },
    {
      id: "step-11",
      label: "Cloud Security",
      tool: "AWS Security",
      description: "Secure cloud environments with IAM policies, VPC configurations, encryption, and monitoring. Understand the shared responsibility model and cloud-specific attack vectors. As workloads move to cloud, cloud security skills are in extreme demand.",
      url: "https://aws.amazon.com/security/",
    },
    {
      id: "step-12",
      label: "Compliance & Frameworks",
      tool: "NIST",
      description: "Apply security frameworks like NIST CSF, ISO 27001, SOC 2, and CIS Controls. Understand risk management, security policies, and audit procedures. Compliance isn't optional — it's how organizations demonstrate security to customers and regulators.",
      url: "https://www.nist.gov/cyberframework",
    },
    {
      id: "step-13",
      label: "Security Automation",
      tool: "Python",
      description: "Write scripts to automate security tasks: vulnerability scanning, log parsing, threat intelligence gathering, and incident response playbooks. Python is the most popular language for security automation — it turns manual chores into one-click operations.",
      url: "https://www.python.org/doc/",
    },
    {
      id: "step-14",
      label: "Certifications",
      tool: "CompTIA",
      description: "Pursue industry certifications like CompTIA Security+, CEH, or OSCP. Certifications validate your knowledge, open career doors, and provide structured learning paths. They're not a substitute for hands-on skill, but they open the first door.",
      url: "https://www.comptia.org/certifications/security",
    },
  ],
};
