import { Roadmap } from "../types/roadmap";

export const dataEngineerRoadmap: Roadmap = {
  id: "data-engineer",
  title: "Data Engineer",
  description: "Design and build data pipelines, warehouses, and infrastructure for analytics.",
  introduction: "Data engineering builds the pipelines and infrastructure that power analytics. Learn SQL, Python, Apache Airflow, Kafka, and Spark to process massive datasets efficiently.",
  icon: "🏗️",
  category: "Data & AI",
  difficulty: "Intermediate",
  estimatedTime: "5-8 months",
  steps: [
    {
      id: "step-1",
      label: "SQL & Databases",
      tool: "SQL",
      description: "Master SQL for querying, transforming, and analyzing data across relational databases like PostgreSQL, MySQL, and SQL Server. Learn to write complex joins, window functions, CTEs, and optimize query performance with proper indexing. Understand database normalization, ACID properties, and how to design efficient schemas that scale.",
      url: "https://www.postgresql.org/docs/",
    },
    {
      id: "step-2",
      label: "Python",
      tool: "Python",
      description: "Use Python as the primary language for data manipulation, scripting, and building pipeline components. Libraries like pandas, NumPy, and PySpark are essential for transforming datasets of any size. Master object-oriented patterns and virtual environments to create maintainable, production-ready data applications.",
      url: "https://www.python.org/doc/",
    },
    {
      id: "step-3",
      label: "Data Modeling",
      tool: "dbt",
      description: "Design star and snowflake schemas that optimize query performance for analytical workloads. Understand dimensional modeling with facts, dimensions, and slowly changing dimensions to maintain historical accuracy. Tools like dbt enable analytics engineers to apply software engineering practices—version control, testing, and documentation—to data transformations.",
      url: "https://docs.getdbt.com/",
    },
    {
      id: "step-4",
      label: "ETL/ELT with Airflow",
      tool: "Apache Airflow",
      description: "Build and orchestrate complex data workflows using Apache Airflow's DAG-based execution model. Define tasks as Python operators, set dependencies, handle retries, and schedule pipelines with cron expressions. Monitor runs through Airflow's UI, set up alerting for failures, and integrate with dozens of hooks and operators for external systems.",
      url: "https://airflow.apache.org/docs/",
    },
    {
      id: "step-5",
      label: "Data Warehouse",
      tool: "Snowflake",
      description: "Load structured and semi-structured data into cloud data warehouses like Snowflake or Google BigQuery for high-performance analytics. Learn to partition, cluster, and materialize views to optimize query speed and reduce costs at scale. Understand the separation of storage and compute, multi-cluster warehouses, and time-travel capabilities that modern warehouses provide.",
      url: "https://docs.snowflake.com/",
    },
    {
      id: "step-6",
      label: "Stream Processing",
      tool: "Apache Kafka",
      description: "Process real-time data streams using Apache Kafka's distributed event streaming platform. Design topics, manage consumer groups, and implement exactly-once semantics to ensure data consistency across pipelines. Complement Kafka with stream processing frameworks like Flink or ksqlDB to perform windowed aggregations and joins on live data.",
      url: "https://kafka.apache.org/documentation/",
    },
    {
      id: "step-7",
      label: "Big Data",
      tool: "Spark",
      description: "Process massive datasets that exceed single-machine memory using Apache Spark's distributed computing framework. Leverage DataFrames, Spark SQL, and Structured Streaming to handle batch and real-time workloads on clusters. Understand partitioning, shuffle operations, and caching strategies to write efficient Spark jobs that scale to petabytes of data.",
      url: "https://spark.apache.org/docs/latest/",
    },
    {
      id: "step-8",
      label: "Data Quality",
      tool: "Great Expectations",
      description: "Validate data integrity and enforce quality expectations at every stage of the pipeline using tools like Great Expectations or Soda. Define schemas, ranges, nullability rules, and statistical expectations that catch anomalies before they reach consumers. Integrate quality checks into orchestration workflows so pipelines fail fast and provide clear, actionable error messages.",
      url: "https://docs.greatexpectations.io/",
    },
    {
      id: "step-9",
      label: "Data Lake & Lakehouse",
      tool: "Delta Lake",
      description: "Build a lakehouse architecture that combines the flexibility of data lakes with the reliability of warehouses using Delta Lake or Apache Iceberg. Store raw, enriched, and curated data in open formats like Parquet on object storage while supporting ACID transactions and schema enforcement. Query lakehouse tables directly with Spark, Trino, or Databricks SQL to avoid data duplication.",
      url: "https://docs.delta.io/",
    },
    {
      id: "step-10",
      label: "Orchestration",
      tool: "Prefect",
      description: "Go beyond basic scheduling with modern orchestration tools like Prefect or Dagster that offer observability, versioning, and dependency management. Define data assets as first-class objects, track lineage automatically, and instrument pipelines with logging and metrics. Orchestration platforms bridge the gap between development and operations, enabling data teams to deploy, monitor, and debug workflows with confidence.",
      url: "https://docs.prefect.io/",
    },
    {
      id: "step-11",
      label: "Data Governance",
      tool: "DataHub",
      description: "Implement data governance policies that ensure data is discoverable, trustworthy, and compliant with regulations like GDPR and HIPAA. Use metadata catalogs like DataHub or OpenLineage to track data lineage, ownership, and freshness across the entire organization. Establish access controls, data classification schemes, and documentation standards that enable self-service analytics without sacrificing security.",
      url: "https://datahubproject.io/docs/",
    },
    {
      id: "step-12",
      label: "Cloud Data Services",
      tool: "AWS/GCP/Azure",
      description: "Leverage cloud-native services to build scalable, cost-effective data infrastructure without managing hardware. Use AWS Glue and Redshift, Google Cloud Dataflow and BigQuery, or Azure Data Factory and Synapse to accelerate pipeline development. Understand serverless options, managed Spark clusters, and object storage services that form the backbone of modern cloud data platforms.",
      url: "https://docs.aws.amazon.com/redshift/",
    },
  ],
};
