import { Roadmap } from "../types/roadmap";

export const databaseAdministratorRoadmap: Roadmap = {
  id: "database-administrator",
  title: "Database Administrator",
  description: "Install, configure, and optimize databases for performance and reliability.",
  introduction: "Database administration ensures data is stored, optimized, and protected. Master SQL, schema design, indexing, performance tuning, replication, backup strategies, and high availability patterns.",
  icon: "🗄️",
  category: "Infrastructure",
  difficulty: "Intermediate",
  estimatedTime: "6-10 months",
  steps: [
    {
      id: "step-1",
      label: "SQL",
      tool: "PostgreSQL",
      description: "Write queries, joins, and subqueries to manipulate relational data. Learn SELECT statements, aggregate functions, window functions, and CTEs to extract insights from your database.",
      url: "https://www.postgresql.org/docs/",
    },
    {
      id: "step-2",
      label: "Schema Design",
      tool: "Normalization",
      description: "Design efficient database schemas with normalization rules. Understand 1NF, 2NF, and 3NF to reduce data redundancy, and learn when denormalization improves read performance for analytics workloads.",
      url: "https://www.postgresql.org/docs/current/ddl.html",
    },
    {
      id: "step-3",
      label: "Indexing",
      tool: "B-Tree Index",
      description: "Create indexes to speed up query execution significantly. Explore B-Tree, Hash, GIN, and GiST index types to match different query patterns, and monitor index usage to drop unused ones.",
      url: "https://www.postgresql.org/docs/current/indexes-types.html",
    },
    {
      id: "step-4",
      label: "Performance Tuning",
      tool: "EXPLAIN",
      description: "Analyze query plans and optimize slow-running queries using EXPLAIN ANALYZE. Identify full table scans, missing indexes, and inefficient joins to resolve performance bottlenecks before they reach production.",
      url: "https://www.postgresql.org/docs/current/using-explain.html",
    },
    {
      id: "step-5",
      label: "Backup & Recovery",
      tool: "pg_dump",
      description: "Implement backup, point-in-time recovery, and WAL archiving strategies. Automate scheduled backups with pg_dump and pg_basebackup, and test restoration procedures regularly to ensure data durability.",
      url: "https://www.postgresql.org/docs/current/backup-dump.html",
    },
    {
      id: "step-6",
      label: "Replication",
      tool: "Streaming Replication",
      description: "Set up streaming and logical replication to distribute data across multiple servers. Use read replicas to offload reporting queries and configure failover mechanisms for uninterrupted service.",
      url: "https://www.postgresql.org/docs/current/different-replication-solutions.html",
    },
    {
      id: "step-7",
      label: "Security",
      tool: "Row-Level Security",
      description: "Enforce access controls, encrypt sensitive data, and audit database activity. Implement row-level security policies, manage roles and privileges, and use TLS encryption for connections in transit.",
      url: "https://www.postgresql.org/docs/current/ddl-rowsecurity.html",
    },
    {
      id: "step-8",
      label: "NoSQL",
      tool: "MongoDB",
      description: "Store and query document-based data for flexible schemas. Understand when document stores outperform relational databases, and learn aggregation pipelines, sharding, and replica sets in MongoDB.",
      url: "https://www.mongodb.com/docs/",
    },
    {
      id: "step-9",
      label: "Connection Pooling",
      tool: "PgBouncer",
      description: "Manage database connections efficiently with pooling middleware. Configure PgBouncer or similar tools to reduce connection overhead, prevent resource exhaustion, and maintain stable performance under heavy load.",
      url: "https://www.pgbouncer.org/config.html",
    },
    {
      id: "step-10",
      label: "Migration Strategies",
      tool: "Flyway",
      description: "Plan and execute database migrations safely using tools like Flyway or Liquibase. Version-control your schema changes, apply zero-downtime migrations, and rollback cleanly when issues arise.",
      url: "https://flywaydb.org/documentation/",
    },
    {
      id: "step-11",
      label: "Monitoring",
      tool: "pg_stat",
      description: "Track database health, query performance, and resource utilization in real time. Use pg_stat_statements, Prometheus exporters, and dashboards to detect anomalies before they impact users.",
      url: "https://www.postgresql.org/docs/current/monitoring-stats.html",
    },
    {
      id: "step-12",
      label: "High Availability",
      tool: "Patroni",
      description: "Architect fault-tolerant database clusters with automatic failover. Deploy solutions like Patroni or AWS RDS Multi-AZ to ensure your database remains available during hardware failures or maintenance windows.",
      url: "https://patroni.readthedocs.io/",
    },
  ],
};
