import { Roadmap } from "../types/roadmap";

export const dataAnalystRoadmap: Roadmap = {
  id: "data-analyst",
  title: "Data Analyst",
  description: "Analyze datasets to discover trends, create visualizations, and inform decisions.",
  introduction: "Data analysis transforms raw data into actionable business insights. Master Excel, SQL, Python, Tableau, and statistics to discover trends and communicate findings clearly.",
  icon: "📈",
  category: "Data & AI",
  difficulty: "Intermediate",
  estimatedTime: "3-6 months",
  steps: [
    {
      id: "step-1",
      label: "Excel & Spreadsheets",
      tool: "Excel",
      description: "Excel is the foundational tool for any data analyst and remains widely used across industries. Master essential functions like VLOOKUP, INDEX-MATCH, and conditional formulas to manipulate data efficiently. Learn pivot tables to summarize large datasets in seconds and use data validation to maintain data integrity across workbooks.",
      url: "https://support.microsoft.com/en-us/office/excel-video-training-9bc053dc-87d4-4146-8e93-f37e57dad873",
    },
    {
      id: "step-2",
      label: "SQL",
      tool: "SQL",
      description: "SQL is the language of databases and is essential for extracting and analyzing structured data at scale. Learn to write SELECT, JOIN, GROUP BY, and window functions to query relational databases effectively. Practice building complex queries that combine multiple tables and use subqueries to answer nuanced business questions.",
      url: "https://www.postgresql.org/docs/",
    },
    {
      id: "step-3",
      label: "Python for Analysis",
      tool: "Pandas",
      description: "Python provides powerful libraries like Pandas and NumPy for programmatic data manipulation and transformation. Automate repetitive cleaning tasks, merge datasets from multiple sources, and perform advanced calculations that go beyond spreadsheet capabilities. Build reproducible analysis scripts that can be version-controlled and shared with your team.",
      url: "https://pandas.pydata.org/docs/user_guide/",
    },
    {
      id: "step-4",
      label: "Data Visualization",
      tool: "Tableau",
      description: "Tools like Tableau and Power BI allow you to build interactive dashboards that bring data to life. Learn to choose appropriate chart types, apply effective color schemes, and design layouts that guide the viewer's attention. Create drill-down capabilities and filters so stakeholders can explore data on their own terms.",
      url: "https://help.tableau.com/current/pro/desktop/en-us/gettingstarted.htm",
    },
    {
      id: "step-5",
      label: "Statistics",
      tool: "Statistics",
      description: "A solid understanding of statistics separates a great analyst from a good one. Master descriptive statistics, probability distributions, and hypothesis testing to validate your findings rigorously. Learn when to use correlation versus causation and how to avoid common statistical pitfalls that lead to wrong conclusions.",
      url: "https://www.khanacademy.org/math/statistics-probability",
    },
    {
      id: "step-6",
      label: "A/B Testing",
      tool: "A/B Testing",
      description: "A/B testing is a critical skill for measuring the impact of changes in products, marketing campaigns, and business processes. Understand how to set up controlled experiments, determine sample sizes, and interpret results with statistical significance. Know when an experiment is valid and how to avoid common mistakes like peeking at results too early.",
      url: "https://www.optimizely.com/optimization-glossary/ab-testing/",
    },
    {
      id: "step-7",
      label: "Data Cleaning",
      tool: "Data Cleaning",
      description: "Real-world data is messy, and cleaning it often takes up the majority of an analyst's time. Learn techniques for handling missing values, detecting and removing duplicates, and standardizing inconsistent formats. Develop a systematic approach to auditing data quality before performing any analysis to ensure your results are reliable.",
      url: "https://www.kaggle.com/learn/data-cleaning",
    },
    {
      id: "step-8",
      label: "Business Acumen",
      tool: "Business Acumen",
      description: "Data analysis without business context produces numbers, not insights. Develop a deep understanding of how your organization makes money, what its key performance indicators are, and what decisions stakeholders are trying to make. Always tie your analysis back to concrete business outcomes rather than presenting data for its own sake.",
      url: "https://hbr.org/2020/01/how-to-improve-your-business-analytical-skills",
    },
    {
      id: "step-9",
      label: "Storytelling with Data",
      tool: "Storytelling",
      description: "The best analysts don't just present data — they tell a compelling story that drives action. Structure your findings using a clear narrative arc: set the context, reveal the key insight, explain its implications, and recommend next steps. Tailor your language and complexity to your audience, avoiding jargon when speaking to non-technical leaders.",
      url: "https://hbr.org/2020/04/why-data-stories-fail",
    },
    {
      id: "step-10",
      label: "Dashboard Design",
      tool: "Dashboard Design",
      description: "A well-designed dashboard is a self-service tool that answers questions without requiring analyst intervention every time. Learn principles of information hierarchy, layout design, and user experience to create dashboards that are intuitive and actionable. Balance detail with clarity by showing the most important metrics prominently and allowing users to dig deeper when needed.",
      url: "https://www.tableau.com/learn/whitepapers/tableau-dashboard-design",
    },
    {
      id: "step-11",
      label: "Presenting to Stakeholders",
      tool: "Presenting",
      description: "Presenting data findings to stakeholders requires a different skill set than the analysis itself. Learn to prepare for Q&A, anticipate objections, and frame recommendations in terms of business impact rather than methodology. Practice delivering confident presentations that translate complex analysis into clear, actionable decisions for your audience.",
      url: "https://www.coursera.org/learn/presentation-skills",
    },
  ],
};
