import { Roadmap } from "../types/roadmap";

export const dataScientistRoadmap: Roadmap = {
  id: "data-scientist",
  title: "Data Scientist",
  description: "Extract insights and build predictive models from complex datasets.",
  introduction: "Data science extracts insights and predictions from complex datasets. You'll master Python, statistics, SQL, machine learning, and data storytelling to drive data-informed decisions.",
  icon: "📊",
  category: "Data & AI",
  difficulty: "Expert",
  estimatedTime: "6-12 months",
  steps: [
    {
      id: "step-1",
      label: "Python Fundamentals",
      tool: "Python",
      description: "Master Python with focus on data structures, list comprehensions, generators, and object-oriented programming. Python is the backbone of data science — its simplicity lets you focus on the problem, not the language.",
      url: "https://www.python.org/doc/",
    },
    {
      id: "step-2",
      label: "NumPy",
      tool: "NumPy",
      description: "Perform fast numerical computation with multi-dimensional arrays and vectorized operations. Understand broadcasting, indexing, and linear algebra operations. NumPy is the foundation that Pandas, scikit-learn, and PyTorch are built on.",
      url: "https://numpy.org/doc/",
    },
    {
      id: "step-3",
      label: "Data Manipulation",
      tool: "Pandas",
      description: "Load, clean, transform, and reshape datasets with DataFrames. Handle missing values, merge datasets, group by aggregates, and time series operations. Pandas is your primary tool for exploring and preparing real-world data.",
      url: "https://pandas.pydata.org/docs/user_guide/",
    },
    {
      id: "step-4",
      label: "Statistics",
      tool: "Statistics",
      description: "Apply probability theory, hypothesis testing, confidence intervals, Bayesian inference, and statistical significance. Statistics is the scientific foundation of data science — without it, you're just pattern-matching blindly.",
      url: "https://www.khanacademy.org/math/statistics-probability",
    },
    {
      id: "step-5",
      label: "SQL",
      tool: "PostgreSQL",
      description: "Query relational databases with SELECT, JOIN, GROUP BY, window functions, and CTEs. Write efficient queries with proper indexing and query plans. SQL is how you extract data from production systems — it's the most universal data skill.",
      url: "https://www.postgresql.org/docs/",
    },
    {
      id: "step-6",
      label: "Data Visualization",
      tool: "Matplotlib",
      description: "Create static and interactive charts with Matplotlib and Seaborn. Learn when to use bar charts vs. scatter plots, how to choose color palettes, and how to tell a story with visuals. Good visualization makes insights accessible to non-technical stakeholders.",
      url: "https://matplotlib.org/stable/tutorials/index.html",
    },
    {
      id: "step-7",
      label: "Exploratory Data Analysis",
      tool: "Pandas",
      description: "Systematically explore datasets to find patterns, outliers, and anomalies. Use summary statistics, distributions, correlation matrices, and pair plots. EDA is where you form hypotheses and understand your data before modeling.",
      url: "https://pandas.pydata.org/docs/user_guide/",
    },
    {
      id: "step-8",
      label: "Machine Learning",
      tool: "Scikit-learn",
      description: "Build regression, classification, and clustering models. Learn cross-validation, hyperparameter tuning, feature engineering, and evaluation metrics (precision, recall, F1, AUC). Scikit-learn's consistent API makes it easy to experiment with many algorithms.",
      url: "https://scikit-learn.org/stable/",
    },
    {
      id: "step-9",
      label: "Feature Engineering",
      tool: "Scikit-learn",
      description: "Transform raw data into model-ready features with encoding, scaling, binning, and interaction terms. Create polynomial features, handle categorical variables, and select the most relevant features. Good features often matter more than model choice.",
      url: "https://scikit-learn.org/stable/modules/preprocessing.html",
    },
    {
      id: "step-10",
      label: "Deep Learning",
      tool: "PyTorch",
      description: "Train neural networks for complex pattern recognition. Understand layers, activation functions, loss functions, optimizers, and regularization. Deep learning excels at unstructured data (images, text, audio) where traditional ML falls short.",
      url: "https://pytorch.org/",
    },
    {
      id: "step-11",
      label: "Time Series Analysis",
      tool: "Prophet",
      description: "Analyze temporal data with trend detection, seasonality decomposition, and forecasting models. Learn ARIMA, exponential smoothing, and modern approaches like Prophet. Time series is a specialized but critical skill for business forecasting.",
      url: "https://facebook.github.io/prophet/",
    },
    {
      id: "step-12",
      label: "Big Data Tools",
      tool: "Spark",
      description: "Process datasets that don't fit in memory using Apache Spark's distributed computing. Learn PySpark, lazy evaluation, and partitioning. When Pandas isn't enough, Spark lets you scale to terabytes without rewriting your analysis logic.",
      url: "https://spark.apache.org/docs/latest/api/python/",
    },
    {
      id: "step-13",
      label: "Data Storytelling",
      tool: "Jupyter",
      description: "Present analysis with reproducible notebooks that combine code, visualizations, and narrative. Structure your findings with a clear beginning (question), middle (analysis), and end (recommendation). Data storytelling is how you turn analysis into action.",
      url: "https://jupyter.readthedocs.io/",
    },
    {
      id: "step-14",
      label: "MLOps Basics",
      tool: "MLflow",
      description: "Track experiments, version models, and deploy predictions with MLflow. Learn model serialization, environment management, and monitoring. MLOps bridges the gap between a working notebook and a production system that delivers value.",
      url: "https://mlflow.org/docs/latest/index.html",
    },
  ],
};
