import { Roadmap } from "../types/roadmap";

export const dataPrivacyOfficerRoadmap: Roadmap = {
  id: "data-privacy-officer",
  title: "Data Privacy Officer",
  description: "Protect personal data, ensure regulatory compliance, and build trust through responsible data stewardship.",
  introduction: "Data Privacy Officers safeguard personal information and ensure organizations handle data responsibly. This roadmap covers privacy laws, data protection principles, compliance frameworks, and emerging technologies to build comprehensive privacy expertise.",
  icon: "🔐",
  category: "Compliance",
  difficulty: "Intermediate",
  estimatedTime: "6-9 months",
  steps: [
    {
      id: "step-1",
      label: "Privacy Laws & Regulations",
      tool: "GDPR",
      description: "Understand the General Data Protection Regulation (GDPR) in the European Union, the California Consumer Privacy Act (CCPA/CPRA), and other foundational privacy statutes. Study their scope, territorial reach, penalties, and the legal bases for processing personal data. These laws form the bedrock of modern privacy practice — non-compliance can result in fines up to 4% of global annual revenue.",
      url: "https://gdpr-info.eu/",
    },
    {
      id: "step-2",
      label: "Data Protection Principles",
      tool: "Privacy Frameworks",
      description: "Master core data protection principles including purpose limitation, data minimization, accuracy, storage limitation, integrity, confidentiality, and accountability. Understand how these principles translate into practical obligations for data controllers and processors. Every privacy decision you make should trace back to these foundational principles.",
      url: "https://edpb.europa.eu/our-work-tools/general-guidance/data-protection-principles_en",
    },
    {
      id: "step-3",
      label: "Privacy by Design",
      tool: "PbD",
      description: "Learn to embed privacy into the design and architecture of systems, processes, and products from the outset rather than bolting it on as an afterthought. Study the seven foundational principles of Privacy by Design and how to conduct privacy engineering reviews. Organizations that adopt PbD reduce compliance costs and build stronger customer trust.",
      url: "https://www.ipc.on.ca/english/privacy/topical-privacy-topics/privacy-by-design/",
    },
    {
      id: "step-4",
      label: "Data Processing Agreements",
      tool: "DPA",
      description: "Draft, review, and negotiate Data Processing Agreements (DPAs) that define the roles and responsibilities between controllers and processors. Ensure agreements include required clauses such as sub-processor disclosure, audit rights, breach notification timelines, and international transfer mechanisms. A well-crafted DPA is your first line of defense in third-party data risk management.",
      url: "https://gdpr-info.eu/art-28-gdpr/",
    },
    {
      id: "step-5",
      label: "Consent Management",
      tool: "CMPs",
      description: "Implement consent management platforms and processes that capture, store, and honor user consent preferences in compliance with legal requirements. Understand the difference between consent, legitimate interest, and other lawful bases for processing. Transparent and granular consent mechanisms are essential for maintaining user autonomy and avoiding regulatory action.",
      url: "https://gdpr-info.eu/chapter/3/",
    },
    {
      id: "step-6",
      label: "Data Subject Rights",
      tool: "DSR Workflows",
      description: "Build operational workflows to handle data subject access requests (DSARs), deletion requests, portability requests, and objection mechanisms within the mandated response times. Learn identity verification techniques, data inventory methods, and exceptions to fulfillment. Timely and accurate responses to data subject requests are a core compliance obligation under most privacy laws.",
      url: "https://gdpr-info.eu/chapter/3/",
    },
    {
      id: "step-7",
      label: "Privacy Impact Assessments",
      tool: "PIA",
      description: "Conduct Data Protection Impact Assessments (DPIAs) and Privacy Impact Assessments (PIAs) to evaluate the privacy risks of new projects, technologies, or data processing activities. Learn to document risks, propose mitigations, and present findings to leadership and regulators. PIAs are mandatory under GDPR for high-risk processing and serve as critical governance tools for proactive risk management.",
      url: "https://gdpr-info.eu/art-35-gdpr/",
    },
    {
      id: "step-8",
      label: "Incident Response for Data Breaches",
      tool: "Breach Protocols",
      description: "Develop and rehearse data breach response plans that include detection, containment, root cause analysis, regulatory notification within 72 hours, and affected individual communication. Coordinate with legal, IT, and communications teams during breach events. The speed and transparency of your breach response directly determines regulatory outcomes and reputational damage.",
      url: "https://gdpr-info.eu/art-33-gdpr/",
    },
    {
      id: "step-9",
      label: "Vendor & Third-Party Management",
      tool: "Vendor Risk",
      description: "Establish vendor assessment frameworks to evaluate the privacy posture of third-party processors and sub-processors before onboarding and throughout the relationship. Conduct regular due diligence reviews, assess cross-border data transfer mechanisms like Standard Contractual Clauses, and monitor compliance continuously. Your organization is only as private as its weakest vendor.",
      url: "https://gdpr-info.eu/art-26-gdpr/",
    },
    {
      id: "step-10",
      label: "Privacy Audits & Compliance Monitoring",
      tool: "Audit Frameworks",
      description: "Design and execute internal privacy audits to assess compliance with applicable laws, internal policies, and contractual commitments. Learn to use checklists, evidence collection techniques, and reporting templates aligned with frameworks like ISO 27701. Regular audits transform privacy from a one-time project into an ongoing, measurable organizational discipline.",
      url: "https://www.iso.org/standard/80547.html",
    },
    {
      id: "step-11",
      label: "Employee Training & Awareness",
      tool: "Training Programs",
      description: "Develop and deliver privacy awareness training programs tailored to different roles — from executives to front-line staff handling personal data. Cover topics like phishing, social engineering, data handling procedures, and reporting obligations. A privacy-aware workforce is the most effective and cost-efficient control any organization can deploy.",
      url: "https://iapp.org/certifications/",
    },
    {
      id: "step-12",
      label: "Global Privacy Frameworks",
      tool: "Cross-Border",
      description: "Navigate the complex landscape of international data transfer mechanisms, adequacy decisions, and cross-border regulatory cooperation. Understand how frameworks like the EU-U.S. Data Privacy Framework, APEC CBPR, and binding corporate rules enable lawful international data flows. Global organizations must harmonize compliance across dozens of jurisdictions simultaneously.",
      url: "https://www.dataprivacyframework.gov/",
    },
    {
      id: "step-13",
      label: "Emerging Privacy Technologies",
      tool: "PETs",
      description: "Explore privacy-enhancing technologies (PETs) such as differential privacy, homomorphic encryption, secure multi-party computation, and federated learning. Understand how these technologies enable data utility while preserving individual privacy. Staying ahead of PETs adoption positions you at the forefront of the evolving privacy landscape.",
      url: "https://www.enisa.europa.eu/topics/privacy-enhancing-technologies",
    },
  ],
};
