import { Roadmap } from "../types/roadmap";

export const devopsEngineerRoadmap: Roadmap = {
  id: "devops-engineer",
  title: "DevOps Engineer",
  description: "Automate infrastructure, CI/CD pipelines, and streamline software delivery.",
  introduction: "DevOps engineering bridges development and operations through automation. Master CI/CD pipelines, containerization with Docker, Kubernetes orchestration, and infrastructure as code.",
  icon: "🔄",
  category: "Infrastructure",
  difficulty: "Intermediate",
  estimatedTime: "5-8 months",
  steps: [
    {
      id: "step-1",
      label: "Linux & Shell",
      tool: "Bash",
      description: "Master the Linux command line, file system navigation, process management, and shell scripting. Write scripts to automate system administration tasks, parse logs, and manage services. Linux is the foundation of most cloud infrastructure — scripting saves hours of manual work.",
      url: "https://www.gnu.org/software/bash/manual/",
    },
    {
      id: "step-2",
      label: "Networking",
      tool: "TCP/IP",
      description: "Understand DNS, HTTP/S, TCP/UDP, load balancing, firewalls, and SSL/TLS certificates. Learn how services discover and communicate with each other. Networking issues are the hardest to debug — deep understanding prevents days of troubleshooting.",
      url: "https://www.cloudflare.com/learning/networking/",
    },
    {
      id: "step-3",
      label: "Version Control",
      tool: "Git",
      description: "Master branching strategies (Git Flow, trunk-based), rebasing, cherry-picking, and bisecting. Configure Git hooks for pre-commit checks and use GitHub/GitLab for code review. Version control is the backbone of collaborative development.",
      url: "https://git-scm.com/doc",
    },
    {
      id: "step-4",
      label: "CI/CD Pipelines",
      tool: "GitHub Actions",
      description: "Automate build, test, and deployment workflows triggered by commits, PRs, or schedules. Learn workflow syntax, caching, secrets management, matrix builds, and artifact publishing. CI/CD is the engine that ships code safely and frequently.",
      url: "https://docs.github.com/en/actions",
    },
    {
      id: "step-5",
      label: "Containers",
      tool: "Docker",
      description: "Package applications with dependencies into portable, isolated containers. Write Dockerfiles with multi-stage builds, manage volumes and networks, and use docker-compose for local development. Containers solve deployment consistency across environments.",
      url: "https://docs.docker.com/",
    },
    {
      id: "step-6",
      label: "Container Orchestration",
      tool: "Kubernetes",
      description: "Deploy and manage containerized applications at scale with pods, services, deployments, configmaps, and secrets. Learn rolling updates, horizontal pod autoscaling, and self-healing. Kubernetes is the industry standard for container orchestration.",
      url: "https://kubernetes.io/docs/",
    },
    {
      id: "step-7",
      label: "Infrastructure as Code",
      tool: "Terraform",
      description: "Provision and manage cloud resources declaratively with HCL. Learn state management, modules, workspaces, and drift detection. IaC makes infrastructure repeatable, version-controlled, and auditable — no more clicking in consoles.",
      url: "https://developer.hashicorp.com/terraform/docs",
    },
    {
      id: "step-8",
      label: "Cloud Platform",
      tool: "AWS",
      description: "Navigate core AWS services: EC2, S3, RDS, VPC, IAM, and Lambda. Understand the shared responsibility model, pricing, and best practices. AWS is the largest cloud provider — understanding it prepares you for any cloud environment.",
      url: "https://docs.aws.amazon.com/gettingstarted/latest/welcome/",
    },
    {
      id: "step-9",
      label: "Monitoring",
      tool: "Prometheus",
      description: "Collect metrics with Prometheus, visualize with Grafana, and alert on thresholds. Learn about time-series data, label-based querying, and recording rules. Monitoring is how you know about problems before your users do.",
      url: "https://prometheus.io/docs/",
    },
    {
      id: "step-10",
      label: "Log Management",
      tool: "ELK Stack",
      description: "Aggregate logs with Elasticsearch, process with Logstash, and visualize with Kibana. Centralized logging is essential for debugging distributed systems — you can't SSH into every server to read logs.",
      url: "https://www.elastic.co/guide/en/elastic-stack/current/index.html",
    },
    {
      id: "step-11",
      label: "Secret Management",
      tool: "Vault",
      description: "Manage secrets, API keys, and certificates with HashiCorp Vault. Implement dynamic secrets, encryption as a service, and secret rotation. Hardcoded secrets are a security nightmare — proper secret management is non-negotiable.",
      url: "https://developer.hashicorp.com/vault/docs",
    },
    {
      id: "step-12",
      label: "GitOps",
      tool: "ArgoCD",
      description: "Manage Kubernetes deployments declaratively using Git as the source of truth. Learn about GitOps principles, reconciliation loops, and multi-cluster management. GitOps provides audit trails and rollback capabilities for infrastructure changes.",
      url: "https://argo-cd.readthedocs.io/",
    },
    {
      id: "step-13",
      label: "Security",
      tool: "SAST/DAST",
      description: "Integrate security scanning into CI/CD pipelines with SAST (static analysis), DAST (dynamic analysis), and dependency scanning. Learn about container image scanning and compliance checks. DevSecOps means security is everyone's responsibility.",
      url: "https://owasp.org/www-community/Source_Code_Analysis_Tools",
    },
    {
      id: "step-14",
      label: "SRE Practices",
      tool: "SLI/SLO",
      description: "Define service level indicators (SLIs), objectives (SLOs), and error budgets. Implement incident response, post-mortems, and chaos engineering. SRE applies software engineering to operations — it's how you scale reliability.",
      url: "https://sre.google/sre-book/table-of-contents/",
    },
  ],
};
