import { Roadmap } from "../types/roadmap";

export const devSecOpsEngineerRoadmap: Roadmap = {
  id: "devsecops-engineer",
  title: "DevSecOps Engineer",
  description: "Integrate security practices into every stage of the software delivery pipeline.",
  introduction: "DevSecOps integrates security into every stage of software delivery. Learn SAST, SCA, container security, IaC scanning, and secrets management.",
  icon: "🔐",
  category: "Security",
  difficulty: "Advanced",
  estimatedTime: "6-10 months",
  steps: [
    {
      id: "step-1",
      label: "Security Fundamentals",
      tool: "OWASP",
      description: "Master the OWASP Top 10 and understand the most critical web application security risks. Learn secure coding principles including input validation, output encoding, and authentication best practices. Study attack vectors like injection, broken authentication, and cross-site scripting to build a strong security mindset.",
      url: "https://owasp.org/www-project-top-ten/",
    },
    {
      id: "step-2",
      label: "SAST",
      tool: "SonarQube",
      description: "Static Application Security Testing analyzes source code without executing it to find vulnerabilities early in the development cycle. SonarQube integrates directly into IDEs and CI pipelines to provide real-time feedback on code quality and security flaws. Use it to detect SQL injection, buffer overflows, and insecure cryptography before code is merged.",
      url: "https://docs.sonarqube.org/latest/",
    },
    {
      id: "step-3",
      label: "SCA",
      tool: "Snyk",
      description: "Software Composition Analysis identifies known vulnerabilities in open-source dependencies and transitive libraries. Snyk scans your dependency manifests, pinpoints vulnerable packages, and suggests patched versions or safe alternatives. Integrate SCA into your pipeline to prevent vulnerable dependencies from reaching production.",
      url: "https://docs.snyk.io/",
    },
    {
      id: "step-4",
      label: "Container Security",
      tool: "Trivy",
      description: "Container images often contain outdated OS packages and libraries with known CVEs that attackers can exploit. Trivy scans container images, file systems, and Git repositories for OS and application-level vulnerabilities in seconds. Use it in your CI pipeline to block deployment of images that fail your security threshold.",
      url: "https://aquasecurity.github.io/trivy/",
    },
    {
      id: "step-5",
      label: "IaC Scanning",
      tool: "Checkov",
      description: "Infrastructure as Code misconfigurations are a leading cause of cloud breaches, from open S3 buckets to overly permissive IAM roles. Checkov scans Terraform, CloudFormation, Kubernetes manifests, and ARM templates against built-in policy libraries. Catch drift from security baselines before infrastructure is provisioned to reduce remediation costs dramatically.",
      url: "https://www.checkov.io/",
    },
    {
      id: "step-6",
      label: "Secrets Management",
      tool: "HashiCorp Vault",
      description: "Hardcoded secrets in source code and config files are a top attack vector for credential leakage. HashiCorp Vault provides dynamic secrets, encryption as a service, and fine-grained access control with automatic rotation. Centralize all credentials, API keys, and certificates in Vault to eliminate secrets sprawl across environments.",
      url: "https://developer.hashicorp.com/vault/docs",
    },
    {
      id: "step-7",
      label: "Compliance",
      tool: "Open Policy Agent",
      description: "Organizations must enforce regulatory and internal security policies consistently across all deployments. Open Policy Agent (OPA) lets you write policies as code using Rego and apply them at any point in the stack. Use OPA with Kubernetes admission controllers and CI gates to prevent non-compliant resources from being created.",
      url: "https://www.openpolicyagent.org/docs/",
    },
    {
      id: "step-8",
      label: "DAST",
      tool: "OWASP ZAP",
      description: "Dynamic Application Security Testing probes running applications from the outside to find vulnerabilities that static analysis cannot detect. OWASP ZAP automatically crawls your web application and attacks it with a library of known exploit payloads. Run ZAP scans against staging environments to uncover authentication flaws, misconfigurations, and business logic vulnerabilities.",
      url: "https://www.zaproxy.org/docs/",
    },
    {
      id: "step-9",
      label: "CI/CD Security",
      tool: "GitHub Advanced Security",
      description: "The CI/CD pipeline itself is a high-value target where secrets, permissions, and build artifacts flow. GitHub Advanced Security provides secret scanning, code scanning, and dependency review directly within pull requests. Secure your pipeline by enforcing branch protection rules, signed commits, and artifact provenance to prevent supply chain attacks.",
      url: "https://docs.github.com/en/actions/security-guides",
    },
    {
      id: "step-10",
      label: "Runtime Protection",
      tool: "Falco",
      description: "Runtime protection monitors running containers and workloads for suspicious behavior in real time. Falco uses kernel-level event streaming to detect unexpected process execution, network connections, and file access. Deploy Falco with Kubernetes to trigger alerts or block actions when container behavior deviates from the defined baseline.",
      url: "https://falco.org/docs/",
    },
    {
      id: "step-11",
      label: "Security Monitoring",
      tool: "Elastic Security",
      description: "Continuous security monitoring aggregates logs, metrics, and traces to detect threats across your entire infrastructure. Elastic Security provides SIEM capabilities with detection rules, threat hunting, and anomaly detection powered by machine learning. Build dashboards and alerting rules to correlate events and reduce mean time to detection for security incidents.",
      url: "https://www.elastic.co/guide/en/security/current/index.html",
    },
    {
      id: "step-12",
      label: "Incident Response",
      tool: "TheHive",
      description: "A structured incident response process ensures you can contain, eradicate, and recover from security incidents quickly and effectively. TheHive provides a collaborative platform for security analysts to triage alerts, investigate cases, and coordinate response activities with integrated threat intelligence. Document post-incident reviews and playbooks to continuously improve your detection and response capabilities.",
      url: "https://docs.strangebee.com/thehive/",
    },
  ],
};
