import { Roadmap } from "../types/roadmap";

export const dietitianRoadmap: Roadmap = {
  id: "dietitian",
  title: "Dietitian",
  description: "Design evidence-based nutrition plans to promote health and manage disease.",
  introduction: "Dietetics applies the science of nutrition to human health. Master biochemistry, medical nutrition therapy, clinical assessment, counseling, and food safety to become a registered dietitian.",
  icon: "🥗",
  category: "Science",
  difficulty: "Expert",
  estimatedTime: "8-14 months",
  steps: [
    {
      id: "step-1",
      label: "Nutrition Science",
      tool: "Nutrient Analysis",
      description: "Build a comprehensive understanding of macronutrients, micronutrients, water, and their roles in sustaining human physiological function. Study energy metabolism, nutrient bioavailability, and the Recommended Dietary Allowances that guide population-level intake standards. A strong foundation in nutrition science enables you to translate complex research into practical dietary recommendations for individuals and communities.",
      url: "https://www.nutrition.org/",
    },
    {
      id: "step-2",
      label: "Biochemistry",
      tool: "Molecular Biology",
      description: "Explore the chemical processes within living organisms, focusing on carbohydrate, lipid, and protein metabolism at the cellular level. Understand enzyme kinetics, metabolic pathways such as glycolysis and the Krebs cycle, and how nutritional deficiencies disrupt biochemical homeostasis. Biochemical literacy allows dietitians to connect dietary intake with metabolic outcomes and tailor interventions for specific health conditions.",
      url: "https://www.asbmb.org/",
    },
    {
      id: "step-3",
      label: "Medical Nutrition Therapy",
      tool: "Clinical Protocols",
      description: "Apply evidence-based nutrition interventions to treat and manage diseases including diabetes, cardiovascular disease, renal failure, and gastrointestinal disorders. Learn to develop individualized care plans, calculate nutrient needs for patients with altered metabolism, and collaborate with interdisciplinary healthcare teams. Medical nutrition therapy is the cornerstone of dietetic practice, bridging clinical knowledge with direct patient care.",
      url: "https://www.eatright.org/health/healthcare-providers/medical-nutrition-therapy",
    },
    {
      id: "step-4",
      label: "Community Nutrition",
      tool: "Public Health",
      description: "Design and deliver nutrition education programs targeting underserved populations, schools, and community organizations. Address food insecurity, cultural dietary practices, and health disparities through targeted outreach and policy advocacy. Community nutrition professionals drive systemic change by developing sustainable programs that improve public health outcomes at scale.",
      url: "https://www.cdc.gov/nutrition/",
    },
    {
      id: "step-5",
      label: "Food Service Management",
      tool: "Operations",
      description: "Manage food service operations in hospitals, schools, and long-term care facilities with a focus on quality, nutrition, and regulatory compliance. Master menu planning, food procurement, budgeting, and staff supervision while ensuring meals meet therapeutic and cultural dietary requirements. Effective food service management combines business acumen with nutritional expertise to deliver safe, nutritious meals to diverse patient populations.",
      url: "https://www.ashtag.org/",
    },
    {
      id: "step-6",
      label: "Diet Assessment Methods",
      tool: "Dietary Analysis",
      description: "Utilize food frequency questionnaires, 24-hour dietary recalls, food records, and biomarkers to accurately assess individual and population dietary intake. Learn to analyze dietary data using software tools and interpret findings in the context of clinical guidelines and nutritional adequacy. Accurate diet assessment is essential for identifying nutritional deficiencies, monitoring intervention effectiveness, and guiding evidence-based practice.",
      url: "https://www.ars.usda.gov/northeast-area/beltsville-md-bhnrc/beltsville-human-nutrition-research-center/",
    },
    {
      id: "step-7",
      label: "Clinical Nutrition",
      tool: "Patient Care",
      description: "Provide specialized nutritional care for hospitalized patients, including enteral and parenteral nutrition support, wound healing optimization, and critical care nutrition. Interpret laboratory values, assess nutritional status using validated tools, and modify nutrition plans based on clinical changes. Clinical dietitians work alongside physicians, nurses, and pharmacists to ensure patients receive optimal nutrition throughout their treatment journey.",
      url: "https://www.nutritioncare.org/",
    },
    {
      id: "step-8",
      label: "Sports Nutrition",
      tool: "Performance Nutrition",
      description: "Design nutrition strategies that enhance athletic performance, support recovery, and prevent injuries across recreational and elite athletes. Study nutrient timing, hydration protocols, ergogenic aids, and periodized nutrition plans tailored to specific sports and training cycles. Sports nutrition integrates exercise physiology with dietetics to optimize fuel utilization and maximize physiological adaptations to training.",
      url: "https://www.sportsnutritionsociety.org/",
    },
    {
      id: "step-9",
      label: "Pediatric Nutrition",
      tool: "Child Health",
      description: "Address the unique nutritional needs of infants, children, and adolescents through evidence-based feeding guidance and growth monitoring. Understand breastfeeding support, complementary feeding introduction, prevention of childhood obesity, and management of pediatric food allergies and intolerances. Proper nutrition during critical growth windows establishes lifelong eating patterns and significantly influences cognitive development and chronic disease risk later in life.",
      url: "https://www.healthychildren.org/",
    },
    {
      id: "step-10",
      label: "Geriatric Nutrition",
      tool: "Aging & Diet",
      description: "Manage nutritional challenges associated with aging, including sarcopenia, dysphagia, cognitive decline, polypharmacy interactions, and diminished appetite. Develop texture-modified diets, nutrient-dense meal plans, and hydration strategies that address the complex needs of older adults in both community and institutional settings. Geriatric nutrition plays a vital role in maintaining functional independence, preventing malnutrition-related complications, and improving quality of life in the aging population.",
      url: "https://www.aging.org/",
    },
    {
      id: "step-11",
      label: "Nutrition Counseling",
      tool: "Behavioral Change",
      description: "Apply motivational interviewing, cognitive-behavioral strategies, and the stages of change model to facilitate lasting dietary behavior modifications. Build therapeutic rapport, set collaborative goals, and address psychosocial barriers to healthy eating such as emotional eating, stress, and disordered eating patterns. Effective nutrition counseling transcends information delivery by empowering patients to take ownership of their dietary choices through empathy and evidence-based communication techniques.",
      url: "https://www.todaysdietitian.com/",
    },
    {
      id: "step-12",
      label: "Food Safety & Regulations",
      tool: "HACCP",
      description: "Ensure food safety through knowledge of Hazard Analysis and Critical Control Points systems, sanitation standards, and regulatory frameworks governing food production and service. Understand pathogen control, allergen management, cross-contamination prevention, and adherence to FDA, USDA, and local health department regulations. Food safety expertise protects public health and is a legal and ethical responsibility that underpins every aspect of dietetic practice.",
      url: "https://www.fda.gov/food/food-safety-modernization-act-fsma",
    },
    {
      id: "step-13",
      label: "Research Methods",
      tool: "Evidence-Based Practice",
      description: "Critically appraise scientific literature, design nutrition research studies, and apply statistical analysis to evaluate dietary interventions and their health outcomes. Understand study designs including randomized controlled trials, cohort studies, and meta-analyses, and learn to translate research findings into clinical practice. Research competency enables dietitians to contribute to the growing evidence base, challenge outdated practices, and advance the profession through rigorous scientific inquiry.",
      url: "https://www.ncbi.nlm.nih.gov/pmc/",
    },
  ],
};
