import { Roadmap } from "../types/roadmap";

export const digitalMarketerRoadmap: Roadmap = {
  id: "digital-marketer",
  title: "Digital Marketer",
  description: "Run online campaigns across search, social, and email to drive growth.",
  introduction: "Digital marketing runs online campaigns across search, social, and email. Master SEO, paid ads, social media, email marketing, and analytics.",
  icon: "📣",
  category: "Business",
  difficulty: "Beginner",
  estimatedTime: "3-5 months",
  steps: [
    {
      id: "step-1",
      label: "Marketing Fundamentals",
      tool: "Marketing Mix",
      description: "Understand the 4Ps of marketing — Product, Price, Place, and Promotion — and how they shape every campaign decision. Learn about buyer personas, the customer journey, and how to position a product effectively in a crowded market. These core principles form the foundation for every channel and tactic you will use as a digital marketer.",
      url: "https://www.investopedia.com/terms/f/four-ps.asp",
    },
    {
      id: "step-2",
      label: "SEO",
      tool: "Google Search Console",
      description: "Search Engine Optimization is the practice of improving your website's visibility in organic search results. Master keyword research, on-page optimization, technical SEO, and link-building strategies to rank higher on Google. Use Google Search Console to monitor indexing status, fix crawl issues, and track which queries bring visitors to your site.",
      url: "https://search.google.com/search-console",
    },
    {
      id: "step-3",
      label: "Paid Ads",
      tool: "Google Ads",
      description: "Google Ads lets you reach customers at the exact moment they are searching for your product or service. Learn to set up Search, Display, Shopping, and Video campaigns, and master bidding strategies, quality score optimization, and ad copywriting. Track conversions and calculate cost-per-acquisition to ensure every dollar spent drives measurable ROI.",
      url: "https://ads.google.com/intl/en/home/",
    },
    {
      id: "step-4",
      label: "Social Media Marketing",
      tool: "Meta Business Suite",
      description: "Social media platforms offer powerful ways to build brand awareness, engage communities, and drive direct sales. Learn to create platform-specific content strategies for Facebook, Instagram, LinkedIn, and TikTok while using Meta Business Suite to schedule posts, manage ads, and analyze audience insights. Develop skills in community management and social listening to stay ahead of trends.",
      url: "https://business.facebook.com/",
    },
    {
      id: "step-5",
      label: "Email Marketing",
      tool: "Mailchimp",
      description: "Email remains one of the highest-ROI channels in digital marketing, delivering an average of $36 for every $1 spent. Build subscriber lists using lead magnets and opt-in forms, then segment your audience to send personalized, relevant content. Automate welcome sequences, abandoned cart reminders, and re-engagement campaigns to nurture leads and retain customers over time.",
      url: "https://mailchimp.com/help/",
    },
    {
      id: "step-6",
      label: "Analytics",
      tool: "Google Analytics",
      description: "Data-driven decisions separate great marketers from average ones, and Google Analytics is the industry standard for web measurement. Learn to set up goals, track UTM parameters, build custom dashboards, and interpret user behavior reports to understand what works and what does not. Use these insights to optimize campaigns, improve user experience, and prove marketing ROI to stakeholders.",
      url: "https://analytics.google.com/analytics/academy/",
    },
    {
      id: "step-7",
      label: "Content Marketing",
      tool: "WordPress",
      description: "Content marketing attracts and retains customers by creating valuable, relevant content that solves their problems. Develop skills in blogging, video production, podcasting, and infographic design while learning editorial planning and content distribution strategies. Use WordPress or similar CMS platforms to publish, optimize, and promote content that ranks in search engines and gets shared across social channels.",
      url: "https://wordpress.org/",
    },
    {
      id: "step-8",
      label: "Conversion Rate Optimization",
      tool: "Google Optimize",
      description: "Conversion Rate Optimization is the systematic process of increasing the percentage of visitors who take a desired action on your website. Learn to run A/B tests, analyze heatmaps, conduct user surveys, and apply psychological principles like urgency and social proof to improve landing pages. Even small improvements in conversion rate can dramatically increase revenue without spending more on traffic acquisition.",
      url: "https://optimize.google.com/",
    },
    {
      id: "step-9",
      label: "Marketing Automation",
      tool: "HubSpot",
      description: "Marketing automation tools streamline repetitive tasks and deliver the right message to the right person at the right time. Set up automated workflows for lead scoring, email nurturing, social posting, and CRM updates to free up time for strategic work. Platforms like HubSpot and ActiveCampaign help you align marketing and sales while scaling personalized customer experiences.",
      url: "https://www.hubspot.com/products/marketing",
    },
    {
      id: "step-10",
      label: "Affiliate Marketing",
      tool: "ShareASale",
      description: "Affiliate marketing is a performance-based channel where partners promote your product in exchange for a commission on each sale they generate. Learn to set up an affiliate program, recruit and manage affiliates, track referrals, and prevent fraud using platforms like ShareASale or Impact. This channel can scale revenue rapidly since you only pay for actual results, making it one of the most cost-effective strategies available.",
      url: "https://www.shareasale.com/",
    },
    {
      id: "step-11",
      label: "Influencer Marketing",
      tool: "Aspire",
      description: "Influencer marketing leverages trusted voices on social media to reach niche audiences that traditional ads cannot easily access. Learn to identify authentic influencers, negotiate partnerships, define clear deliverables, and measure campaign impact beyond vanity metrics. Platforms like Aspire and CreatorIQ help you manage influencer relationships at scale while ensuring brand safety and compliance with disclosure regulations.",
      url: "https://www.aspire.io/",
    },
    {
      id: "step-12",
      label: "Brand Strategy",
      tool: "Canva",
      description: "Brand strategy defines how your company is perceived in the market, covering your mission, values, visual identity, tone of voice, and overall positioning. Develop a brand style guide, craft compelling brand stories, and ensure consistency across every customer touchpoint from your website to your social media to your packaging. A strong brand strategy builds long-term loyalty and differentiates you from competitors in ways that are difficult to replicate.",
      url: "https://www.canva.com/",
    },
  ],
};
