import { Roadmap } from "../types/roadmap";

export const ecommerceSpecialistRoadmap: Roadmap = {
  id: "ecommerce-specialist",
  title: "E-Commerce Specialist",
  description: "Build, optimize, and scale online stores for revenue growth.",
  introduction: "E-commerce specialization builds and optimizes online stores. Learn Shopify, product SEO, payment integration, conversion optimization, and analytics.",
  icon: "🛒",
  category: "Business",
  difficulty: "Beginner",
  estimatedTime: "3-5 months",
  steps: [
    {
      id: "step-1",
      label: "E-Commerce Platforms",
      tool: "Shopify",
      description: "Choose and configure the right e-commerce platform for your business needs. Platforms like Shopify, WooCommerce, and BigCommerce offer different strengths in customization, scalability, and ease of use. Master store setup, theme customization, and app integrations to create a professional storefront.",
      url: "https://shopify.dev/",
    },
    {
      id: "step-2",
      label: "Product Listings",
      tool: "SEO",
      description: "Create compelling product pages that rank and convert. Write detailed product descriptions, optimize titles and meta tags for search engines, and use high-quality images with proper alt text. Implement structured data markup to enhance visibility in search results.",
      url: "https://ahrefs.com/blog/ecommerce-seo/",
    },
    {
      id: "step-3",
      label: "Payment Processing",
      tool: "Stripe",
      description: "Integrate secure payment gateways to accept multiple payment methods safely. Configure Stripe, PayPal, or other processors to handle credit cards, digital wallets, and buy-now-pay-later options. Ensure PCI compliance and implement fraud prevention measures to protect your business and customers.",
      url: "https://stripe.com/docs",
    },
    {
      id: "step-4",
      label: "Conversion Optimization",
      tool: "A/B Testing",
      description: "Systematically improve your store's ability to turn visitors into buyers. Run A/B tests on landing pages, product layouts, call-to-action buttons, and checkout flows to identify what drives purchases. Use heatmaps and session recordings to understand user behavior and eliminate friction points in the buying journey.",
      url: "https://www.optimizely.com/optimization-glossary/ab-testing/",
    },
    {
      id: "step-5",
      label: "Analytics",
      tool: "Google Analytics",
      description: "Track and analyze every aspect of your store's performance with data-driven insights. Set up conversion funnels, monitor traffic sources, measure average order value, and identify cart abandonment patterns. Use custom dashboards to visualize key metrics and make informed decisions about pricing, inventory, and marketing spend.",
      url: "https://analytics.google.com/analytics/academy/",
    },
    {
      id: "step-6",
      label: "Marketing",
      tool: "Facebook Ads",
      description: "Drive qualified traffic to your store through strategic paid advertising campaigns. Create targeted campaigns on Google Shopping, Facebook, and Instagram to reach your ideal customers at every stage of the funnel. Develop retargeting strategies to re-engage visitors who didn't complete their purchase.",
      url: "https://www.facebook.com/business/ads",
    },
    {
      id: "step-7",
      label: "Inventory Management",
      tool: "TradeGecko",
      description: "Keep your stock levels optimized to prevent both shortages and overstock situations. Implement inventory tracking systems that sync across all sales channels and provide real-time visibility into stock levels. Set up automated reorder points and demand forecasting to maintain healthy cash flow while meeting customer demand.",
      url: "https://www.quickbooks.com/inventory/",
    },
    {
      id: "step-8",
      label: "Customer Service",
      tool: "Zendesk",
      description: "Build a responsive support system that turns first-time buyers into loyal advocates. Configure live chat, email ticketing, and self-service knowledge bases to handle inquiries efficiently. Train on common issues like order status, returns, and product questions, and use feedback data to improve your store experience.",
      url: "https://www.zendesk.com/",
    },
    {
      id: "step-9",
      label: "Shipping & Fulfillment",
      tool: "ShipStation",
      description: "Design a reliable shipping operation that meets customer expectations for speed and cost. Integrate fulfillment services like ShipStation, Shippo, or 3PL partners to automate label creation and order processing. Offer multiple shipping options including free shipping thresholds, local delivery, and real-time tracking to reduce cart abandonment.",
      url: "https://www.shipstation.com/",
    },
    {
      id: "step-10",
      label: "Email Marketing",
      tool: "Klaviyo",
      description: "Nurture customer relationships and drive repeat purchases through targeted email campaigns. Set up automated flows for welcome sequences, abandoned cart recovery, post-purchase follow-ups, and win-back campaigns. Segment your email list based on purchase behavior, browsing history, and customer lifetime value to deliver personalized content that converts.",
      url: "https://www.klaviyo.com/",
    },
    {
      id: "step-11",
      label: "Social Commerce",
      tool: "Instagram Shopping",
      description: "Sell directly where your customers spend time on social media platforms. Set up Instagram Shopping, Facebook Marketplace, and Pinterest product pins to create seamless purchasing experiences without leaving the app. Leverage user-generated content, influencer partnerships, and live shopping events to build community and drive social sales.",
      url: "https://business.instagram.com/shopping",
    },
    {
      id: "step-12",
      label: "Retention Strategies",
      tool: "LoyaltyLion",
      description: "Implement programs that keep customers coming back and increase their lifetime value. Launch loyalty reward programs, referral incentives, and subscription models that create recurring revenue streams. Analyze customer cohorts, track retention metrics, and personalize outreach to reduce churn and maximize long-term profitability.",
      url: "https://loyaltylion.com/",
    },
  ],
};
