import { Roadmap } from "../types/roadmap";

export const financialAnalystRoadmap: Roadmap = {
  id: "financial-analyst",
  title: "Financial Analyst",
  description: "Analyze financial data to guide investment and business decisions.",
  introduction: "Financial analysts transform raw data into actionable investment insights. Master financial statements, valuation techniques, data modeling, and analytical tools to drive smarter capital allocation and business strategy.",
  icon: "💰",
  category: "Business",
  difficulty: "Intermediate",
  estimatedTime: "3-6 months",
  steps: [
    {
      id: "step-1",
      label: "Financial Statements",
      tool: "Accounting",
      description: "Learn to read and interpret the three core financial statements: income statement, balance sheet, and cash flow statement. Understand how revenues, expenses, assets, liabilities, and cash flows interconnect across periods. Financial statements are the language of business — without fluency here, every other skill falls apart.",
      url: "https://www.investopedia.com/terms/i/income-statement.asp",
    },
    {
      id: "step-2",
      label: "Excel Modeling",
      tool: "Excel",
      description: "Build dynamic financial models using formulas, pivot tables, data validation, and conditional formatting. Master VLOOKUP, INDEX-MATCH, scenario analysis, and sensitivity tables to stress-test assumptions. Excel is the analyst's workbench — speed and accuracy here separate competent analysts from exceptional ones.",
      url: "https://support.microsoft.com/en-us/office/excel-video-training-9bc053dc-87d4-4146-8e93-f37e57dad873",
    },
    {
      id: "step-3",
      label: "Valuation (DCF)",
      tool: "DCF",
      description: "Value companies using discounted cash flow analysis, comparable company analysis, and precedent transactions. Learn to project free cash flows, select appropriate discount rates (WACC), and calculate terminal value. Valuation is the crown jewel of financial analysis — it determines whether deals get done and investments get made.",
      url: "https://www.investopedia.com/terms/d/dcf.asp",
    },
    {
      id: "step-4",
      label: "Data Analysis (Python)",
      tool: "Python",
      description: "Automate repetitive financial tasks and perform advanced analytics with Pandas, NumPy, and SciPy. Write scripts to clean messy datasets, backtest trading strategies, and run Monte Carlo simulations. Python scales your analytical capability far beyond what spreadsheets can handle — essential for large datasets and reproducible workflows.",
      url: "https://www.python.org/doc/",
    },
    {
      id: "step-5",
      label: "Visualization (Tableau)",
      tool: "Tableau",
      description: "Build interactive dashboards that communicate financial performance at a glance. Combine revenue trends, margin analysis, and KPI tracking into visual stories executives can act on. Good visualization turns numbers into narratives — it's how you influence decisions without presenting a single spreadsheet.",
      url: "https://help.tableau.com/",
    },
    {
      id: "step-6",
      label: "Financial Modeling",
      tool: "Excel",
      description: "Construct integrated three-statement models that link income statement, balance sheet, and cash flow projections dynamically. Model revenue build-ups, cost structures, working capital cycles, and capital expenditure plans. A robust financial model is the backbone of any investment recommendation or strategic plan.",
      url: "https://corporatefinanceinstitute.com/resources/financial-modeling/",
    },
    {
      id: "step-7",
      label: "Risk Assessment",
      tool: "Statistics",
      description: "Quantify investment risk using standard deviation, beta, value at risk (VaR), and scenario analysis. Evaluate how macroeconomic shocks, interest rate changes, and currency fluctuations impact portfolios and business lines. Risk assessment ensures you're not just chasing returns — you understand what you're giving up to get them.",
      url: "https://www.investopedia.com/terms/r/riskmanagement.asp",
    },
    {
      id: "step-8",
      label: "Industry Analysis",
      tool: "Research",
      description: "Apply Porter's Five Forces, SWOT analysis, and competitive benchmarking to evaluate industry dynamics. Assess market size, growth rates, regulatory environments, and competitive moats before making investment theses. Understanding the industry context separates shallow analysis from the kind that actually predicts winners and losers.",
      url: "https://www.investopedia.com/terms/p/porter.asp",
    },
    {
      id: "step-9",
      label: "Forecasting",
      tool: "Statistics",
      description: "Project future financials using trend analysis, regression models, and time series techniques like moving averages and exponential smoothing. Build bottom-up and top-down forecasts that reconcile with historical patterns. Forecasting is where analytical rigor meets business intuition — your projections will be challenged, so they must be defensible.",
      url: "https://www.investopedia.com/terms/f/forecasting.asp",
    },
    {
      id: "step-10",
      label: "Presentation Skills",
      tool: "Communication",
      description: "Translate complex financial analysis into clear, persuasive recommendations for executives and stakeholders. Structure decks with a logical narrative arc: context, analysis, insight, and action. The best analyst in the room means nothing if they can't convince the decision-maker — presentation is where your analysis earns its impact.",
      url: "https://www.investopedia.com/articles/professionaleducation/111015/how-create-financial-presentation-executives.asp",
    },
    {
      id: "step-11",
      label: "Certifications (CFA)",
      tool: "CFA",
      description: "Pursue the Chartered Financial Analyst designation to validate deep expertise in investment analysis, portfolio management, and ethics. The CFA curriculum covers quantitative methods, economics, financial reporting, equity, and fixed income across three rigorous levels. The CFA charter is the gold standard in investment management — it opens doors and signals credibility to employers and clients.",
      url: "https://www.cfainstitute.org/",
    },
    {
      id: "step-12",
      label: "Financial Software (Bloomberg)",
      tool: "Bloomberg",
      description: "Navigate the Bloomberg Terminal to pull real-time market data, analyze securities, and screen investment opportunities. Master functions like COMP, DES, and GP to build screens, compare peers, and monitor positions. Bloomberg proficiency is table stakes in institutional finance — it's the interface through which billions of dollars move every day.",
      url: "https://www.bloomberg.com/professional/support/",
    },
  ],
};
