import { Roadmap } from "../types/roadmap";

export const frontendDeveloperRoadmap: Roadmap = {
  id: "frontend-developer",
  title: "Frontend Developer",
  description: "Build responsive, accessible user interfaces for web applications.",
  introduction: "Frontend development focuses on creating responsive, accessible user interfaces. Master HTML, CSS, JavaScript, and React to build interfaces that work beautifully across all devices.",
  icon: "🎨",
  category: "Engineering",
  difficulty: "Beginner",
  estimatedTime: "3-5 months",
  steps: [
    {
      id: "step-1",
      label: "HTML",
      tool: "HTML5",
      description: "Learn semantic HTML elements: header, nav, main, article, section, footer. Understand forms with validation, tables, images with srcset for responsive images, and accessibility attributes like aria-labels. HTML is the structure that everything else hangs on.",
      url: "https://developer.mozilla.org/en-US/docs/Learn/HTML",
    },
    {
      id: "step-2",
      label: "CSS",
      tool: "CSS3",
      description: "Master the box model, Flexbox for one-dimensional layouts, and CSS Grid for two-dimensional layouts. Learn responsive design with media queries, CSS custom properties for theming, transitions, and keyframe animations. CSS is where design becomes reality.",
      url: "https://developer.mozilla.org/en-US/docs/Learn/CSS",
    },
    {
      id: "step-3",
      label: "JavaScript",
      tool: "JavaScript",
      description: "Understand variables, scope, closures, promises, async/await, and the event loop. Learn DOM manipulation, event delegation, and ES6+ features (arrow functions, destructuring, modules, spread operator). JavaScript is the language of the web — mastering it unlocks everything.",
      url: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide",
    },
    {
      id: "step-4",
      label: "Responsive Design",
      tool: "Media Queries",
      description: "Build layouts that adapt to any screen size using mobile-first approach, fluid typography with clamp(), CSS Grid with auto-fit/auto-fill, and responsive images. Mobile traffic is over 50% of the web — responsive design isn't optional.",
      url: "https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Responsive_Design",
    },
    {
      id: "step-5",
      label: "CSS Framework",
      tool: "Tailwind CSS",
      description: "Rapidly build consistent UIs with utility-first CSS classes. Learn the design system constraints, responsive prefixes, dark mode, and component patterns. Tailwind eliminates repetitive CSS and enforces visual consistency across your entire application.",
      url: "https://tailwindcss.com/docs/installation",
    },
    {
      id: "step-6",
      label: "React",
      tool: "React",
      description: "Build component-based UIs with JSX, hooks (useState, useEffect, useRef, useCallback, useMemo, useContext), and composition patterns. Understand the virtual DOM, reconciliation, and when to re-render. React is the most in-demand frontend skill in the industry.",
      url: "https://react.dev/learn",
    },
    {
      id: "step-7",
      label: "TypeScript",
      tool: "TypeScript",
      description: "Add static types with interfaces, generics, unions, intersections, and type guards. TypeScript catches bugs at compile time, enables better refactoring, and makes large codebases navigable. Most new React projects use TypeScript by default.",
      url: "https://www.typescriptlang.org/docs/",
    },
    {
      id: "step-8",
      label: "State Management",
      tool: "Zustand",
      description: "Manage client-side state with a minimal, scalable store. Learn when to use local state, context, or global state. Understand derived state, selectors, and middleware. State management is where most frontend complexity lives — getting it right matters.",
      url: "https://zustand-demo.pmnd.rs/",
    },
    {
      id: "step-9",
      label: "Data Fetching",
      tool: "TanStack Query",
      description: "Fetch, cache, and update server state with automatic background refetching, deduplication, and optimistic updates. Understand the difference between client state and server state — they have fundamentally different needs.",
      url: "https://tanstack.com/query/latest",
    },
    {
      id: "step-10",
      label: "Routing",
      tool: "React Router",
      description: "Implement client-side navigation with nested routes, dynamic parameters, lazy loading, and route guards. Learn URL patterns, query parameters, and history management. Routing is how users navigate your single-page application.",
      url: "https://reactrouter.com/en/main",
    },
    {
      id: "step-11",
      label: "Forms",
      tool: "React Hook Form",
      description: "Build performant forms with minimal re-renders, validation with Zod, and controlled/uncontrolled inputs. Handle complex scenarios like multi-step forms, dynamic fields, and file uploads. Forms are the primary way users interact with your application.",
      url: "https://react-hook-form.com/",
    },
    {
      id: "step-12",
      label: "Testing",
      tool: "Vitest",
      description: "Write unit tests for utilities, component tests with React Testing Library, and end-to-end tests with Playwright. Test user interactions, not implementation details. Good tests let you refactor fearlessly and ship features faster.",
      url: "https://vitest.dev/guide/",
    },
    {
      id: "step-13",
      label: "Performance",
      tool: "Lighthouse",
      description: "Optimize Core Web Vitals (LCP, FID, CLS) with code splitting, lazy loading, image optimization, and bundle analysis. Learn React.memo, useMemo, and useCallback for avoiding unnecessary re-renders. Performance is a feature — slow sites lose users.",
      url: "https://developer.chrome.com/docs/lighthouse/overview",
    },
    {
      id: "step-14",
      label: "Deployment",
      tool: "Vercel",
      description: "Deploy with zero-config hosting, preview deployments on every PR, and automatic CI/CD. Configure environment variables, custom domains, and edge functions. Vercel is built for frontend — it handles the infrastructure so you can focus on the UI.",
      url: "https://vercel.com/docs",
    },
  ],
};
