import { Roadmap } from "../types/roadmap";

export const fullStackDeveloperRoadmap: Roadmap = {
  id: "full-stack-developer",
  title: "Full-Stack Developer",
  description: "Build complete web applications across the entire technology stack.",
  introduction: "Full-stack development spans both frontend interfaces and backend systems. You'll learn React, Node.js, databases, and deployment to build complete web applications from scratch.",
  icon: "🔧",
  category: "Engineering",
  difficulty: "Intermediate",
  estimatedTime: "4-8 months",
  steps: [
    {
      id: "step-1",
      label: "HTML & CSS",
      tool: "HTML5",
      description: "Build semantic, accessible page structures with HTML5 elements. Style them with Flexbox, CSS Grid, and responsive design using media queries. These two technologies are the unshakable foundation of everything on the web.",
      url: "https://developer.mozilla.org/en-US/docs/Learn",
    },
    {
      id: "step-2",
      label: "JavaScript",
      tool: "JavaScript",
      description: "Master ES6+ syntax, async/await, Promises, array methods (map, filter, reduce), and DOM manipulation. JavaScript is the only language that runs natively in browsers — it's the core of frontend interactivity.",
      url: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide",
    },
    {
      id: "step-3",
      label: "Version Control",
      tool: "Git",
      description: "Use Git for branching, merging, rebasing, and collaborative workflows. Host repositories on GitHub and use pull requests for code review. Git isn't optional — every professional developer uses it daily.",
      url: "https://git-scm.com/doc",
    },
    {
      id: "step-4",
      label: "React",
      tool: "React",
      description: "Build component-based UIs with JSX, hooks (useState, useEffect, useCallback, useMemo), and composition patterns. React's mental model of declarative UI is the industry standard for frontend development.",
      url: "https://react.dev/learn",
    },
    {
      id: "step-5",
      label: "Styling",
      tool: "Tailwind CSS",
      description: "Design consistent interfaces with utility-first CSS. Learn design tokens, component variants, and responsive prefixes. Tailwind eliminates CSS bloat and keeps your styling consistent across the entire application.",
      url: "https://tailwindcss.com/docs/installation",
    },
    {
      id: "step-6",
      label: "TypeScript",
      tool: "TypeScript",
      description: "Add static types to JavaScript with interfaces, generics, enums, and type guards. TypeScript catches bugs at compile time, improves IDE support, and makes large codebases maintainable. It's now the default for serious projects.",
      url: "https://www.typescriptlang.org/docs/",
    },
    {
      id: "step-7",
      label: "Node.js",
      tool: "Node.js",
      description: "Run JavaScript on the server with the V8 engine. Understand the event loop, streams, buffers, and the module system. Node.js unifies your language across frontend and backend — one team, one language.",
      url: "https://nodejs.org/en/docs",
    },
    {
      id: "step-8",
      label: "REST APIs",
      tool: "Express",
      description: "Design RESTful endpoints with proper HTTP methods, status codes, and response formats. Implement middleware for auth, logging, and error handling. REST is the most common API paradigm — understanding it well makes learning GraphQL or gRPC easier.",
      url: "https://expressjs.com/en/guide/routing.html",
    },
    {
      id: "step-9",
      label: "Databases",
      tool: "PostgreSQL",
      description: "Design relational schemas with normalization, foreign keys, and indexes. Write SQL with JOINs, subqueries, aggregations, and transactions. PostgreSQL is the most advanced open-source relational database — it handles everything from simple apps to enterprise systems.",
      url: "https://www.postgresql.org/docs/",
    },
    {
      id: "step-10",
      label: "ORM",
      tool: "Prisma",
      description: "Define your database schema in code and generate type-safe client queries. Prisma handles migrations, relations, and query optimization. ORMs accelerate development but understanding SQL underneath is still essential.",
      url: "https://www.prisma.io/docs",
    },
    {
      id: "step-11",
      label: "Authentication",
      tool: "NextAuth.js",
      description: "Implement secure login with email/password, OAuth providers (Google, GitHub), and session management. Handle password hashing with bcrypt, CSRF protection, and secure cookie settings. Authentication is a security-critical feature — don't roll your own crypto.",
      url: "https://next-auth.js.org/",
    },
    {
      id: "step-12",
      label: "Testing",
      tool: "Vitest",
      description: "Write unit tests for functions, integration tests for APIs, and component tests for UI. Use mocking to isolate dependencies and test edge cases. Tests are your safety net — they let you refactor with confidence and ship features faster.",
      url: "https://vitest.dev/guide/",
    },
    {
      id: "step-13",
      label: "State Management",
      tool: "Zustand",
      description: "Manage client-side state with a minimal, scalable store. Learn when to use local state, context, or a global store. State management is where junior developers struggle most — getting it right separates clean apps from spaghetti code.",
      url: "https://zustand-demo.pmnd.rs/",
    },
    {
      id: "step-14",
      label: "Deployment",
      tool: "Vercel",
      description: "Deploy full-stack applications with zero-config hosting, preview deployments, and automatic CI/CD. Configure environment variables, custom domains, and serverless functions. Deployment is the final step — shipping is what matters.",
      url: "https://vercel.com/docs",
    },
  ],
};
