import { Roadmap } from "../types/roadmap";

export const gameDeveloperRoadmap: Roadmap = {
  id: "game-developer",
  title: "Game Developer",
  description: "Design and build interactive 2D and 3D games with real-time engines.",
  introduction: "Game development combines programming, art, and design to create interactive experiences. Learn C#, Unity, 2D and 3D graphics, physics, and publishing to Steam.",
  icon: "🎮",
  category: "Engineering",
  difficulty: "Intermediate",
  estimatedTime: "6-10 months",
  steps: [
    {
      id: "step-1",
      label: "Programming",
      tool: "C#",
      description: "Learn object-oriented programming, LINQ, async/await, and Unity's API patterns. C# is Unity's scripting language — master its type system, generics, and delegates to write clean, performant game logic.",
      url: "https://learn.microsoft.com/en-us/dotnet/csharp/",
    },
    {
      id: "step-2",
      label: "Game Engine",
      tool: "Unity",
      description: "Build games using a component-based architecture with GameObjects, MonoBehaviours, and prefabs. Learn the editor interface, scene management, and the Unity lifecycle (Awake, Start, Update, FixedUpdate). Unity powers over 50% of all mobile games.",
      url: "https://learn.unity.com/pathway/unity-basics",
    },
    {
      id: "step-3",
      label: "2D Graphics",
      tool: "Sprite Rendering",
      description: "Create sprite sheets, tilemaps, and 2D animations with the Animator and Animation windows. Learn sprite sorting, pivot points, and 2D lighting. 2D games are accessible to make — start here before tackling 3D complexity.",
      url: "https://learn.unity.com/tutorials/2d-game-creation/creating-a-basic-2d-game",
    },
    {
      id: "step-4",
      label: "3D Graphics",
      tool: "Shaders",
      description: "Write vertex and fragment shaders in ShaderLab/HLSL for visual effects like water, fog, and cel-shading. Understand render pipelines (URP, HDRP), materials, and lighting. Shaders are what make games visually distinctive.",
      url: "https://learn.unity.com/pathway/scripting",
    },
    {
      id: "step-5",
      label: "Physics",
      tool: "Box2D/PhysX",
      description: "Implement realistic collisions, forces, rigid body dynamics, and raycasting. Learn the difference between 2D and 3D physics, collision layers, and trigger colliders. Physics makes games feel real — getting it wrong makes games feel wrong.",
      url: "https://docs.unity3d.com/Manual/PhysicsOverview.html",
    },
    {
      id: "step-6",
      label: "Input & Controls",
      tool: "Input System",
      description: "Handle keyboard, mouse, gamepad, and touch input with Unity's new Input System. Implement control schemes, input actions, and responsive camera controls. Good controls are invisible — bad controls ruin any game.",
      url: "https://docs.unity3d.com/Packages/com.unity.inputsystem@1.0/manual/index.html",
    },
    {
      id: "step-7",
      label: "Audio",
      tool: "FMOD",
      description: "Implement spatial audio, music transitions, sound effects, and adaptive soundtracks. Learn audio mixing, bus routing, and real-time parameter control. Audio is 50% of the game experience — it's the most underinvested area in indie games.",
      url: "https://fmod.com/",
    },
    {
      id: "step-8",
      label: "Game Design",
      tool: "GDD",
      description: "Write game design documents (GDDs) covering mechanics, levels, progression, and economy. Learn about game loops, player motivation, difficulty curves, and feedback systems. Great games are designed before they're coded.",
      url: "https://www.gamedesigning.org/learn/game-design-document/",
    },
    {
      id: "step-9",
      label: "AI & Pathfinding",
      tool: "NavMesh",
      description: "Implement enemy AI with state machines, behavior trees, and Unity's NavMesh for pathfinding. Learn obstacle avoidance, patrol routes, and decision-making logic. AI is what makes game worlds feel alive.",
      url: "https://docs.unity3d.com/Manual/NavMeshOverview.html",
    },
    {
      id: "step-10",
      label: "UI & HUD",
      tool: "UI Toolkit",
      description: "Build in-game menus, health bars, minimaps, and inventory systems with Unity UI Toolkit or UGUI. Learn event systems, layout groups, and responsive scaling. UI is the player's window into your game's systems.",
      url: "https://docs.unity3d.com/Manual/UIElements.html",
    },
    {
      id: "step-11",
      label: "Optimization",
      tool: "Profiler",
      description: "Profile CPU, GPU, and memory usage. Optimize draw calls with batching, reduce polygon count, implement LOD (Level of Detail), and use object pooling. Mobile and console games have strict performance budgets — optimization is a core skill.",
      url: "https://docs.unity3d.com/Manual/Profiler.html",
    },
    {
      id: "step-12",
      label: "Version Control",
      tool: "Git LFS",
      description: "Manage game projects with Git and Large File Storage for binary assets. Learn branching strategies for game development and how to handle merge conflicts with scene files. Game projects have huge binary files — proper Git setup is critical.",
      url: "https://git-lfs.com/",
    },
    {
      id: "step-13",
      label: "Publishing",
      tool: "Steam",
      description: "Package, distribute, and market your game on Steam, Google Play, or App Store. Learn about store pages, wishlists, launch strategies, and post-launch updates. Publishing is where your game meets the market — marketing is as important as quality.",
      url: "https://partner.steamgames.com/doc/marketing",
    },
  ],
};
