import { Roadmap } from "../types/roadmap";

export const iotEngineerRoadmap: Roadmap = {
  id: "iot-engineer",
  title: "IoT Engineer",
  description: "Connect physical devices to the cloud for monitoring and control.",
  introduction: "IoT engineering bridges the physical and digital worlds by connecting sensors, actuators, and intelligent devices to cloud infrastructure. Master embedded systems, wireless protocols, edge computing, and cloud platforms to build reliable, scalable, and secure connected systems that transform raw sensor data into actionable insights.",
  icon: "📡",
  category: "Engineering",
  difficulty: "Intermediate",
  estimatedTime: "6-9 months",
  steps: [
    {
      id: "step-1",
      label: "Embedded Systems",
      tool: "Arduino / ESP32",
      description: "Program microcontrollers to interface with sensors, actuators, and communication peripherals. Arduino and ESP32 provide accessible entry points for learning digital I/O, analog sensing, PWM control, and real-time firmware execution on resource-constrained hardware. Develop proficiency in C/C++ for bare-metal programming, understand memory management on microcontrollers, and learn how hardware abstraction layers simplify cross-platform embedded development.",
      url: "https://www.arduino.cc/en/Tutorial/HomePage",
    },
    {
      id: "step-2",
      label: "IoT Protocols",
      tool: "MQTT / CoAP",
      description: "Choose lightweight messaging protocols optimized for constrained devices and unreliable networks. MQTT provides a publish-subscribe model with three quality-of-service levels, topic hierarchies, and retained messages, making it ideal for telemetry ingestion and remote command delivery. CoAP offers REST semantics over UDP with built-in observe patterns and block-wise transfers, excelling in battery-efficient environments where HTTP overhead is prohibitive.",
      url: "https://mqtt.org/documentation/",
    },
    {
      id: "step-3",
      label: "Sensor Integration",
      tool: "I2C / SPI",
      description: "Interface with temperature, humidity, motion, and environmental sensors using standard serial buses. I2C and SPI are the dominant sensor interfaces, each offering trade-offs in pin count, speed, and multi-device addressing for connecting accelerometers, gyroscopes, barometers, and气体 sensors. Learn signal conditioning, calibration techniques, and noise filtering to produce accurate readings from raw ADC values and digital registers.",
      url: "https://learn.sparkfun.com/tutorials/i2c",
    },
    {
      id: "step-4",
      label: "Connectivity",
      tool: "WiFi / BLE / LoRa",
      description: "Select wireless technologies based on range, power consumption, and data throughput requirements. WiFi offers high-bandwidth local connectivity suitable for video and bulk data transfer but consumes significant power. Bluetooth Low Energy provides short-range, low-power communication ideal for wearable and proximity-based applications, while LoRaWAN enables kilometers-range, low-data-rate connectivity for agricultural, industrial, and rural deployments without cellular infrastructure.",
      url: "https://lora-alliance.org/about-lorawan/",
    },
    {
      id: "step-5",
      label: "Edge Computing",
      tool: "Edge Gateway",
      description: "Process, filter, and aggregate sensor data locally before transmitting to the cloud. Edge computing reduces latency for time-critical decisions, minimizes bandwidth costs by sending only meaningful data, and maintains functionality during intermittent cloud connectivity. Explore edge runtimes such as AWS Greengrass, Azure IoT Edge, or lightweight container orchestration with K3s to deploy analytics, inference, and protocol translation on gateway devices.",
      url: "https://aws.amazon.com/iot/iot-edge/",
    },
    {
      id: "step-6",
      label: "Cloud IoT Platforms",
      tool: "AWS IoT / Azure IoT Hub",
      description: "Register, authenticate, and manage fleets of connected devices through managed cloud services. Platform features include device shadow synchronization for offline state management, rule engines for routing telemetry to storage and analytics services, and fine-grained authorization using X.509 certificates or IoT policies. Learn to orchestrate device lifecycles, build real-time dashboards, and integrate with serverless functions and databases for scalable IoT backends.",
      url: "https://docs.aws.amazon.com/iot/",
    },
    {
      id: "step-7",
      label: "Data Processing",
      tool: "Apache Kafka",
      description: "Ingest, transform, and route high-throughput sensor data streams in real time. Kafka serves as a durable, distributed commit log that decouples device producers from analytics consumers, enabling replay and exactly-once processing semantics. Design stream processing topologies with Kafka Streams, Apache Flink, or AWS Kinesis to perform windowed aggregations, anomaly detection, and complex event processing across thousands of concurrent device feeds.",
      url: "https://kafka.apache.org/documentation/",
    },
    {
      id: "step-8",
      label: "Security",
      tool: "TLS / X.509",
      description: "Encrypt device communications and authenticate endpoints to protect against eavesdropping, tampering, and impersonation. TLS 1.3 secures MQTT and HTTPS traffic, while DTLS provides equivalent protection for CoAP over UDP on constrained networks. Implement mutual TLS with X.509 client certificates, rotate credentials securely through provisioning workflows, and harden firmware against physical attacks, side-channel leakage, and unauthorized firmware extraction.",
      url: "https://www.rfc-editor.org/rfc/rfc8446",
    },
    {
      id: "step-9",
      label: "Firmware Development",
      tool: "ESP-IDF / Zephyr",
      description: "Write production-grade firmware using professional SDKs and real-time operating systems. ESP-IDF provides a comprehensive framework for ESP32 development with Wi-Fi, Bluetooth, and OTA capabilities, while Zephyr offers a scalable RTOS supporting dozens of hardware platforms with advanced scheduling, power management, and networking stacks. Master interrupt handling, peripheral driver development, memory-constrained design patterns, and deterministic task scheduling for reliable embedded applications.",
      url: "https://docs.espressif.com/projects/esp-idf/en/latest/esp32/",
    },
    {
      id: "step-10",
      label: "Digital Twins",
      tool: "Azure Digital Twins",
      description: "Create virtual representations of physical devices and systems for simulation, monitoring, and predictive maintenance. Digital twins synchronize real-time telemetry from IoT devices with cloud-based models that maintain current state, historical context, and behavioral predictions. Use graph-based twin models to represent complex relationships between assets, build what-if simulations to optimize operations, and trigger automated actions based on twin state changes.",
      url: "https://azure.microsoft.com/en-us/products/digital-twins/",
    },
    {
      id: "step-11",
      label: "OTA Updates",
      tool: "Fleet Provisioning",
      description: "Deploy firmware updates and configuration changes to distributed device fleets without physical access. Over-the-air update systems must handle differential patching, rollback safety, bandwidth-constrained delivery, and concurrent updates across thousands of devices. Implement staged rollout strategies, cryptographic firmware verification, health checks before finalization, and automated provisioning using claim certificates to onboard new devices securely at scale.",
      url: "https://docs.aws.amazon.com/iot/latest/developerguide/iot-device-management.html",
    },
    {
      id: "step-12",
      label: "Scalability",
      tool: "Kubernetes / Terraform",
      description: "Design IoT architectures that handle millions of devices, petabytes of telemetry, and global distribution without degradation. Horizontal scaling of cloud ingest endpoints, partitioned time-series databases, and geo-replicated message brokers ensure consistent performance as fleet sizes grow. Apply infrastructure-as-code with Terraform, container orchestration with Kubernetes, and auto-scaling policies to maintain availability, manage costs, and support multi-region device deployments with unified management planes.",
      url: "https://kubernetes.io/docs/home/",
    },
  ],
};
