import { Roadmap } from "../types/roadmap";

export const itProjectManagerRoadmap: Roadmap = {
  id: "it-project-manager",
  title: "IT Project Manager",
  description: "Plan, execute, and deliver IT projects on time and within budget.",
  introduction: "IT project management delivers technology projects on time and within budget. Learn Scrum, planning, risk management, communication, and budgeting.",
  icon: "📋",
  category: "Business",
  difficulty: "Beginner",
  estimatedTime: "3-5 months",
  steps: [
    {
      id: "step-1",
      label: "Project Methodologies",
      tool: "Scrum",
      description: "Master Agile and Scrum frameworks to structure iterative project delivery. Understand sprints, daily standups, sprint reviews, and retrospectives as core ceremonies. Learn when Waterfall, Scrum, or Kanban best fits a given project based on team size, complexity, and stakeholder needs.",
      url: "https://www.scrum.org/resources/what-is-scrum",
    },
    {
      id: "step-2",
      label: "Planning",
      tool: "Gantt Charts",
      description: "Build detailed project plans using Gantt charts to visualize timelines, dependencies, and critical paths. Define clear scope statements, milestones, and deliverables to set stakeholder expectations. Learn to break down large initiatives into manageable work packages with realistic effort estimates.",
      url: "https://www.projectmanager.com/blog/how-to-create-gantt-chart",
    },
    {
      id: "step-3",
      label: "Risk Management",
      tool: "Risk Register",
      description: "Identify potential threats and opportunities early using systematic risk assessment techniques. Maintain a risk register to track probability, impact, and mitigation strategies throughout the project lifecycle. Develop contingency plans so your team can respond swiftly when issues materialize.",
      url: "https://www.projectmanager.com/blog/project-risk-management",
    },
    {
      id: "step-4",
      label: "Communication",
      tool: "Stakeholder Maps",
      description: "Map stakeholders by influence and interest to tailor communication frequency and detail. Run effective meetings with clear agendas, action items, and follow-ups to keep everyone aligned. Use status reports, dashboards, and informal check-ins to maintain transparency across all levels of the organization.",
      url: "https://www.pmi.org/learning/library/effective-stakeholder-communication",
    },
    {
      id: "step-5",
      label: "Budgeting",
      tool: "Cost Tracking",
      description: "Estimate project costs accurately using bottom-up, analogous, and parametric estimation techniques. Track actual spending against budgeted amounts with variance analysis to catch overruns early. Present financial updates to leadership with clear explanations of variances and corrective actions.",
      url: "https://www.investopedia.com/terms/b/budget.asp",
    },
    {
      id: "step-6",
      label: "Tools",
      tool: "Jira",
      description: "Configure Jira projects, workflows, and boards to match your team's delivery process. Use backlogs, epics, and story points to break work into sprint-ready tasks. Generate burndown charts and velocity reports to measure team performance and forecast delivery dates.",
      url: "https://support.atlassian.com/jira/",
    },
    {
      id: "step-7",
      label: "Quality Management",
      tool: "QA Checklists",
      description: "Define quality standards and acceptance criteria before development begins to prevent rework. Implement peer reviews, automated testing, and quality gates as checkpoints throughout the delivery pipeline. Track defect trends and root causes to drive continuous improvement in your team's output quality.",
      url: "https://asq.org/quality-resources/quality-management",
    },
    {
      id: "step-8",
      label: "Change Management",
      tool: "Change Control Board",
      description: "Establish a formal change request process to evaluate scope, cost, and timeline impacts of proposed changes. Present change requests with clear trade-off analysis so stakeholders can make informed go-or-no-go decisions. Document approved changes and communicate them to the entire team to keep plans current and aligned.",
      url: "https://www.pmi.org/learning/library/change-management-practices-702",
    },
    {
      id: "step-9",
      label: "Leadership",
      tool: "Team Charter",
      description: "Build a high-performing team by establishing shared goals, roles, and working agreements through a team charter. Resolve conflicts constructively using active listening, empathy, and collaborative problem-solving approaches. Inspire and motivate team members through servant leadership that removes blockers and empowers autonomy.",
      url: "https://hbr.org/topic/subject/leadership",
    },
    {
      id: "step-10",
      label: "Vendor Management",
      tool: "SLA Tracking",
      description: "Evaluate vendors using weighted criteria covering cost, quality, reliability, and cultural fit. Negotiate contracts that define service level agreements, penalties, and escalation paths to protect project interests. Monitor vendor performance against SLAs regularly and address gaps promptly to maintain delivery timelines.",
      url: "https://www.pmi.org/learning/library/successful-vendor-management-101",
    },
    {
      id: "step-11",
      label: "Reporting",
      tool: "Executive Dashboards",
      description: "Create executive dashboards that translate raw project data into actionable insights for decision-makers. Track key performance indicators such as schedule variance, cost performance index, and burn rate across projects. Deliver timely, concise reports that highlight risks, progress, and recommended next steps without overwhelming stakeholders with detail.",
      url: "https://www.projectmanager.com/blog/project-reporting",
    },
    {
      id: "step-12",
      label: "Lessons Learned",
      tool: "Retrospective Workshop",
      description: "Conduct structured retrospectives at project milestones to capture what worked, what failed, and what to improve. Build a shared knowledge base so future projects can leverage past experiences instead of repeating mistakes. Foster a blameless culture where honest reflection leads to meaningful process improvements across the organization.",
      url: "https://www.pmi.org/learning/library/lessons-learned-effective-project-management",
    },
  ],
};
