import { Roadmap } from "../types/roadmap";

export const itSupportRoadmap: Roadmap = {
  id: "it-support",
  title: "IT Support",
  description: "Provide technical assistance and troubleshoot hardware and software issues.",
  introduction: "IT support provides technical assistance for hardware and software issues. Master operating systems, networking, ticketing systems, remote support, and Active Directory.",
  icon: "🎧",
  category: "Infrastructure",
  difficulty: "Beginner",
  estimatedTime: "2-4 months",
  steps: [
    {
      id: "step-1",
      label: "Operating Systems",
      tool: "Windows/Linux",
      description: "Navigate, configure, and troubleshoot desktop operating systems. Learn file system structures, user account management, system settings, and common error resolution across Windows and Linux distributions. A solid OS foundation is essential for diagnosing virtually any technical issue that users report.",
      url: "https://support.microsoft.com/en-us/windows",
    },
    {
      id: "step-2",
      label: "Hardware Basics",
      tool: "PC Components",
      description: "Diagnose and replace faulty hardware components like RAM, hard drives, power supplies, and motherboards. Understand how to identify failing parts using diagnostics and perform physical replacements safely. Hardware literacy separates effective technicians from those who can only handle software problems.",
      url: "https://www.ifixit.com/",
    },
    {
      id: "step-3",
      label: "Networking",
      tool: "TCP/IP",
      description: "Troubleshoot connectivity issues, DNS resolution, DHCP configuration, and Wi-Fi problems. Understand IP addressing, subnetting, routing basics, and how to use tools like ping, traceroute, and ipconfig to isolate network faults. Most help desk tickets involve some form of network connectivity problem.",
      url: "https://www.cloudflare.com/learning/networking/",
    },
    {
      id: "step-4",
      label: "Ticketing Systems",
      tool: "Zendesk",
      description: "Log, prioritize, and resolve support tickets efficiently using ITSM platforms. Learn SLA tracking, categorization, escalation procedures, and how to write clear resolution notes. Proper ticketing discipline ensures nothing falls through the cracks and management can measure support performance.",
      url: "https://support.zendesk.com/hc/en-us",
    },
    {
      id: "step-5",
      label: "Remote Support",
      tool: "TeamViewer",
      description: "Diagnose and fix issues on remote user machines without on-site visits. Master remote desktop tools, screen sharing, and unattended access to resolve problems quickly regardless of location. Remote support capability dramatically expands your reach and reduces downtime for distributed teams.",
      url: "https://www.teamviewer.com/en/help/",
    },
    {
      id: "step-6",
      label: "Active Directory",
      tool: "Microsoft AD",
      description: "Manage user accounts, groups, organizational units, and domain policies within enterprise environments. Learn to create and reset passwords, assign group memberships, enforce Group Policy settings, and troubleshoot authentication failures. Active Directory is the backbone of identity management in most corporate IT environments.",
      url: "https://learn.microsoft.com/en-us/windows-server/identity/ad-ds/",
    },
    {
      id: "step-7",
      label: "Customer Service Skills",
      tool: "Communication",
      description: "Develop clear communication, active listening, and empathy when interacting with non-technical users. Practice translating complex technical concepts into plain language and managing frustrated customers calmly. Technical skill alone is insufficient — how you make people feel matters just as much as the fix itself.",
      url: "https://www.coursera.org/learn/wharton-customer-analytics",
    },
    {
      id: "step-8",
      label: "Security Basics",
      tool: "Cybersecurity",
      description: "Understand password policies, phishing awareness, endpoint protection, and basic access control principles. Learn to identify common security threats and educate users on safe computing practices. IT support staff are often the first line of defense against social engineering attacks.",
      url: "https://www.comptia.org/certifications/security",
    },
    {
      id: "step-9",
      label: "Mobile Device Management",
      tool: "MDM",
      description: "Configure and manage smartphones, tablets, and laptops across an organization using MDM solutions. Learn to enforce security policies, deploy applications, and remotely wipe lost or stolen devices. The rise of remote work and BYOD policies makes MDM skills increasingly critical for IT support teams.",
      url: "https://learn.microsoft.com/en-us/mem/intune/",
    },
    {
      id: "step-10",
      label: "Backup & Recovery",
      tool: "Veeam",
      description: "Implement and manage data backup strategies to protect against data loss from hardware failure, ransomware, or human error. Understand full, incremental, and differential backups, and practice restoring systems and files from backup media. A technician who can recover lost data quickly becomes indispensable to the organization.",
      url: "https://helpcenter.veeam.com/",
    },
    {
      id: "step-11",
      label: "Documentation",
      tool: "Confluence",
      description: "Write clear knowledge base articles, troubleshooting guides, and standard operating procedures. Learn to document recurring issues, solutions, and configuration steps so that both users and other technicians can resolve problems independently. Good documentation reduces ticket volume and accelerates onboarding for new support staff.",
      url: "https://www.atlassian.com/software/confluence",
    },
    {
      id: "step-12",
      label: "ITIL Framework",
      tool: "ITIL",
      description: "Study IT service management best practices covering incident management, problem management, change management, and service level agreements. Understand how structured processes improve service delivery and align IT operations with business goals. ITIL knowledge distinguishes senior support professionals and opens doors to management roles.",
      url: "https://www.axelos.com/certifications/itil-certifications",
    },
  ],
};
