import { Roadmap } from "../types/roadmap";

export const machineLearningEngineerRoadmap: Roadmap = {
  id: "machine-learning-engineer",
  title: "Machine Learning Engineer",
  description: "Build, train, and deploy production machine learning models at scale.",
  introduction: "Machine learning engineering builds and deploys production AI systems. You'll learn deep learning with PyTorch, feature engineering, MLOps, and model serving at scale.",
  icon: "🧠",
  category: "Data & AI",
  difficulty: "Advanced",
  estimatedTime: "6-10 months",
  steps: [
    {
      id: "step-1",
      label: "Python & Math Foundations",
      tool: "Python / NumPy",
      description: "Master Python's scientific stack including NumPy for vectorized computation and Pandas for data manipulation. Build a solid grounding in linear algebra, calculus, probability, and statistics—the mathematical pillars that underpin every machine learning algorithm. Strong foundations here make every subsequent step dramatically easier.",
      url: "https://www.python.org/doc/",
    },
    {
      id: "step-2",
      label: "Classical Machine Learning",
      tool: "Scikit-learn",
      description: "Implement regression, classification, clustering, and ensemble methods such as Random Forests and Gradient Boosted Trees using Scikit-learn. Learn to evaluate models with cross-validation, confusion matrices, ROC curves, and proper train/validation/test splits. Understand trade-offs between model complexity, interpretability, and generalization.",
      url: "https://scikit-learn.org/stable/",
    },
    {
      id: "step-3",
      label: "Deep Learning",
      tool: "PyTorch",
      description: "Build and train neural networks with PyTorch, leveraging GPU acceleration for efficient computation. Master backpropagation, activation functions, loss landscapes, and optimization algorithms like Adam and SGD with learning rate scheduling. Implement techniques such as dropout, batch normalization, and early stopping to prevent overfitting.",
      url: "https://pytorch.org/",
    },
    {
      id: "step-4",
      label: "CNNs & Computer Vision",
      tool: "PyTorch Vision",
      description: "Architect convolutional neural networks for image classification, object detection, and segmentation tasks. Study convolution layers, pooling strategies, and modern architectures like ResNet, EfficientNet, and Vision Transformers. Fine-tune pre-trained models on custom datasets using transfer learning to achieve strong results with limited data.",
      url: "https://pytorch.org/vision/stable/index.html",
    },
    {
      id: "step-5",
      label: "Feature Engineering",
      tool: "Featuretools / Pandas",
      description: "Transform raw, messy data into meaningful features that directly improve model performance. Apply techniques such as encoding categorical variables, scaling numerical features, extracting time-based patterns, and creating interaction terms. Master automated feature engineering with tools like Featuretools and learn feature selection methods to reduce dimensionality and noise.",
      url: "https://featuretools.alteryx.com/",
    },
    {
      id: "step-6",
      label: "Model Optimization",
      tool: "Optuna / Hyperopt",
      description: "Automate hyperparameter tuning using Bayesian optimization frameworks like Optuna and Hyperopt instead of manual grid search. Define search spaces intelligently and leverage pruning to terminate unpromising trials early, saving compute resources. Compare strategies including random search, TPE, and multi-objective optimization to find the best trade-off between accuracy, latency, and model size.",
      url: "https://optuna.org/",
    },
    {
      id: "step-7",
      label: "Distributed Training",
      tool: "PyTorch DDP",
      description: "Scale model training across multiple GPUs and machines using PyTorch's Distributed Data Parallel (DDP) and Fully Sharded Data Parallel (FSDP) strategies. Understand data parallelism versus model parallelism, gradient synchronization, and communication backends like NCCL. Handle mixed-precision training with automatic loss scaling to maximize throughput without sacrificing model quality.",
      url: "https://pytorch.org/tutorials/intermediate/ddp_tutorial.html",
    },
    {
      id: "step-8",
      label: "Data Pipelines",
      tool: "Apache Spark / Airflow",
      description: "Design robust data ingestion and transformation pipelines that feed models with clean, consistent training data at scale. Orchestrate complex workflows with Apache Airflow or Prefect, and process large datasets with Spark or Polars for distributed ETL. Implement data validation with Great Expectations to catch schema drift and quality issues before they corrupt your training runs.",
      url: "https://spark.apache.org/docs/latest/api/python/index.html",
    },
    {
      id: "step-9",
      label: "Experiment Tracking & MLOps",
      tool: "MLflow / Weights & Biases",
      description: "Log experiments, track metrics, and version models systematically using MLflow or Weights & Biases. Create reproducible ML pipelines that record data versions, code versions, and hyperparameters for every run. Build a model registry to manage staging, approval, and rollback of models as they progress from experimentation to production.",
      url: "https://mlflow.org/docs/latest/index.html",
    },
    {
      id: "step-10",
      label: "Model Serving",
      tool: "TorchServe / Triton",
      description: "Deploy trained models as scalable, low-latency inference services using TorchServe or NVIDIA Triton Inference Server. Implement dynamic batching, model versioning, and health checks to ensure reliable serving under varying load. Optimize inference with quantization, TensorRT acceleration, and ONNX export for production-grade throughput and latency.",
      url: "https://pytorch.org/serve/",
    },
    {
      id: "step-11",
      label: "Monitoring & Drift Detection",
      tool: "Evidently / Grafana",
      description: "Set up continuous monitoring of deployed models to detect data drift, concept drift, and performance degradation in real time. Use tools like Evidently AI or NannyML to generate drift reports and trigger alerts when input distributions shift. Build dashboards with Grafana or Prometheus to visualize model health metrics and establish retraining triggers.",
      url: "https://www.evidentlyai.com/",
    },
    {
      id: "step-12",
      label: "Deployment & Infrastructure",
      tool: "Docker / Kubernetes",
      description: "Containerize ML applications with Docker to ensure consistent environments across development, staging, and production. Orchestrate deployment at scale on Kubernetes, managing auto-scaling, rolling updates, and service mesh configuration. Implement CI/CD pipelines with GitHub Actions or GitLab CI to automate testing, packaging, and deployment of ML models end-to-end.",
      url: "https://docs.docker.com/",
    },
  ],
};
