import { Roadmap } from "../types/roadmap";

export const marketingManagerRoadmap: Roadmap = {
  id: "marketing-manager",
  title: "Marketing Manager",
  description: "Lead marketing strategies, manage campaigns, and drive brand growth across channels.",
  introduction: "Marketing management orchestrates strategy, execution, and measurement across all channels. Master market research, brand strategy, digital marketing, analytics, automation, and team leadership to drive sustainable growth.",
  icon: "📊",
  category: "Business",
  difficulty: "Intermediate",
  estimatedTime: "4-6 months",
  steps: [
    {
      id: "step-1",
      label: "Marketing Fundamentals",
      tool: "Marketing Mix",
      description: "Master the 4Ps of marketing — Product, Price, Place, and Promotion — and understand how they shape every strategic decision. Learn to develop buyer personas, map the customer journey from awareness to advocacy, and position products effectively in competitive markets. These foundational principles guide every channel, campaign, and budget allocation throughout your marketing career.",
      url: "https://www.investopedia.com/terms/f/four-ps.asp",
    },
    {
      id: "step-2",
      label: "Market Research",
      tool: "SurveyMonkey",
      description: "Market research reveals customer needs, competitive dynamics, and emerging opportunities that inform every marketing initiative. Conduct primary research through surveys, interviews, and focus groups while leveraging secondary sources like industry reports and census data to build a complete market picture. Learn to analyze research findings, identify actionable insights, and translate data into strategic recommendations that reduce risk and maximize campaign effectiveness.",
      url: "https://www.surveymonkey.com/",
    },
    {
      id: "step-3",
      label: "Brand Strategy",
      tool: "Brand Positioning",
      description: "Brand strategy defines how your company is perceived in the market, encompassing mission, values, visual identity, and competitive positioning. Develop a comprehensive brand style guide, craft compelling brand narratives, and ensure consistency across every customer touchpoint from website to packaging. A strong brand strategy builds long-term loyalty and creates differentiation that competitors find difficult to replicate.",
      url: "https://www.interbrand.com/",
    },
    {
      id: "step-4",
      label: "Digital Marketing",
      tool: "HubSpot",
      description: "Digital marketing integrates online channels including search, social, email, and display to reach audiences where they spend their time. Learn to build integrated digital strategies that coordinate messaging across platforms while optimizing for each channel's unique strengths. Understand how to allocate digital budgets effectively, set KPIs for each channel, and measure cross-channel performance to drive cohesive growth.",
      url: "https://www.hubspot.com/",
    },
    {
      id: "step-5",
      label: "Content Marketing",
      tool: "WordPress",
      description: "Content marketing attracts and retains customers by creating valuable, relevant content that solves their problems and builds trust. Develop skills across blogging, video production, podcasting, and infographic design while learning editorial planning and content distribution strategies. Build a content engine that generates organic traffic, nurtures leads through the funnel, and establishes your brand as an industry thought leader.",
      url: "https://wordpress.org/",
    },
    {
      id: "step-6",
      label: "Social Media Marketing",
      tool: "Meta Business Suite",
      description: "Social media platforms offer powerful ways to build brand awareness, engage communities, and drive direct sales through organic and paid strategies. Learn to create platform-specific content strategies for Facebook, Instagram, LinkedIn, and TikTok while using management tools to schedule posts and analyze audience insights. Develop skills in community management, social listening, and crisis communication to maintain a positive brand presence across all social channels.",
      url: "https://business.facebook.com/",
    },
    {
      id: "step-7",
      label: "Email Marketing",
      tool: "Mailchimp",
      description: "Email marketing remains one of the highest-ROI channels available, delivering direct access to audiences who have opted in to hear from your brand. Build subscriber lists using lead magnets and opt-in forms, then segment your audience to send personalized, relevant content that drives engagement. Automate welcome sequences, nurture campaigns, and re-engagement flows to maintain relationships with leads and customers throughout their lifecycle.",
      url: "https://mailchimp.com/",
    },
    {
      id: "step-8",
      label: "SEO & SEM",
      tool: "Google Search Console",
      description: "Search Engine Optimization and Search Engine Marketing work together to capture high-intent traffic from users actively searching for your products or services. Master keyword research, on-page optimization, technical SEO, and link-building strategies for organic visibility, while learning Google Ads for paid search campaigns. Track rankings, monitor click-through rates, and analyze competitor strategies to build a comprehensive search presence that balances short-term wins with long-term authority.",
      url: "https://search.google.com/search-console",
    },
    {
      id: "step-9",
      label: "Marketing Analytics",
      tool: "Google Analytics",
      description: "Marketing analytics transforms raw data into actionable insights that inform strategic decisions and prove ROI to stakeholders. Learn to set up tracking infrastructure, interpret user behavior reports, build custom dashboards, and calculate key metrics like customer acquisition cost and lifetime value. Master tools like Google Analytics and Looker Studio to monitor campaign performance, identify trends, and make data-driven optimizations that compound growth over time.",
      url: "https://analytics.google.com/",
    },
    {
      id: "step-10",
      label: "Paid Advertising",
      tool: "Google Ads",
      description: "Paid advertising accelerates growth by placing your brand in front of targeted audiences across search, social, display, and video platforms. Learn to structure campaigns, set budgets, write compelling ad copy, and optimize bidding strategies to maximize return on ad spend. Track conversions, calculate cost-per-acquisition, and run A/B tests to continuously improve campaign performance and ensure every advertising dollar drives measurable business results.",
      url: "https://ads.google.com/",
    },
    {
      id: "step-11",
      label: "Customer Journey Mapping",
      tool: "Miro",
      description: "Customer journey mapping visualizes every interaction a customer has with your brand, from initial awareness through purchase and advocacy. Identify touchpoints, friction points, and moments of delight across the entire lifecycle to optimize the experience at each stage. Use journey maps to align marketing, sales, and customer success efforts around a shared understanding of how customers discover, evaluate, choose, and remain loyal to your brand.",
      url: "https://miro.com/",
    },
    {
      id: "step-12",
      label: "Marketing Automation",
      tool: "HubSpot",
      description: "Marketing automation streamlines repetitive tasks and delivers the right message to the right person at the right time across email, social, and web channels. Set up automated workflows for lead scoring, email nurturing, social posting, and CRM updates to free your team for strategic initiatives. Platforms like HubSpot and ActiveCampaign help you align marketing and sales while scaling personalized customer experiences that drive conversions and retention.",
      url: "https://www.hubspot.com/products/marketing",
    },
    {
      id: "step-13",
      label: "Team Leadership",
      tool: "Asana",
      description: "Marketing team leadership requires balancing strategic vision with operational excellence to deliver campaigns that drive business results. Learn to hire and develop talent, set clear goals and KPIs, manage cross-functional projects, and foster a culture of creativity and accountability. Develop skills in budget management, stakeholder communication, and performance reviews to lead your team with confidence while adapting to the rapidly evolving marketing landscape.",
      url: "https://asana.com/",
    },
  ],
};
