import { Roadmap } from "../types/roadmap";

export const materialsScientistRoadmap: Roadmap = {
  id: "materials-scientist",
  title: "Materials Scientist",
  description: "Design, develop, and characterize advanced materials for cutting-edge applications.",
  introduction: "Materials science explores the relationship between the structure, processing, properties, and performance of matter. Learn crystallography, thermodynamics, mechanical behavior, characterization techniques, computational modeling, and materials design to develop next-generation materials.",
  icon: "⚛️",
  category: "Science",
  difficulty: "Advanced",
  estimatedTime: "18-30 months",
  steps: [
    { id: "step-1", label: "Materials Science Fundamentals", tool: "MIT OCW", description: "Build a strong foundation in the core principles of materials science, including atomic bonding, crystal structures, microstructure, and the structure-property-processing-performance paradigm. Understand how electrons, atoms, and microstructural features collectively determine the macroscopic behavior of metals, ceramics, polymers, and composites. Master concepts such as phase diagrams, diffusion kinetics, and solid-state transformations that govern material behavior under various conditions.", url: "https://ocw.mit.edu/" },
    { id: "step-2", label: "Crystallography", tool: "VESTA", description: "Study the arrangement of atoms in crystalline solids using Bragg's law, Miller indices, and space group symmetry to predict material properties from atomic-scale structure. Learn to interpret X-ray diffraction patterns and electron diffraction data to identify phases, measure lattice parameters, and determine crystal orientations. Use visualization tools like VESTA to build, manipulate, and analyze crystal structures for research and design applications.", url: "https://jp-minerals.org/vesta/" },
    { id: "step-3", label: "Thermodynamics of Materials", tool: "Thermo-Calc", description: "Apply the laws of thermodynamics to predict phase stability, chemical reactions, and equilibrium conditions in materials systems ranging from simple binary alloys to complex multi-component systems. Master Gibbs free energy calculations, phase rule analysis, and CALPHAD methods to construct and interpret phase diagrams for designing new alloys and ceramics. Understand how thermodynamic driving forces influence phase transformations, nucleation, and growth during material processing and service.", url: "https://www.thermocalc.com/" },
    { id: "step-4", label: "Mechanical Properties", tool: "ANSYS", description: "Analyze how materials respond to external forces by studying stress-strain behavior, elastic and plastic deformation, fracture mechanics, and fatigue under cyclic loading. Learn to measure and predict properties such as yield strength, ultimate tensile strength, hardness, and fracture toughness using both analytical models and finite element simulations. Understand the mechanisms of creep, wear, and failure analysis to design materials that perform reliably under extreme mechanical conditions.", url: "https://www.ansys.com/" },
    { id: "step-5", label: "Electronic Materials", tool: "COMSOL", description: "Explore materials used in electronics and photonics, including semiconductors, superconductors, dielectrics, and magnetic materials for devices ranging from transistors to solar cells. Study band theory, carrier transport, doping strategies, and thin-film deposition techniques that enable the fabrication of integrated circuits and optoelectronic devices. Simulate electronic and optical properties using tools like COMSOL Multiphysics to optimize device performance before experimental fabrication.", url: "https://www.comsol.com/" },
    { id: "step-6", label: "Polymers & Composites", tool: "Digimat", description: "Learn the synthesis, processing, and characterization of polymer-based materials including thermoplastics, thermosets, elastomers, and fiber-reinforced composites. Understand polymer chain architecture, molecular weight distribution, crystallinity, and glass transition temperature to tailor material properties for specific applications. Study composite mechanics using micromechanical models and simulation tools like Digimat to predict stiffness, strength, and failure modes in layered and particulate composite systems.", url: "https://www.esc-group.com/products/digimat" },
    { id: "step-7", label: "Ceramics", tool: "FactSage", description: "Study the unique properties and processing routes of ceramic materials, including oxide and non-oxide ceramics, glass-ceramics, and advanced structural and functional ceramics. Understand sintering kinetics, grain growth, and densification mechanisms to control microstructure and optimize mechanical, thermal, and electrical performance. Use thermodynamic databases like FactSage to predict phase equilibria and chemical stability of ceramic systems at high temperatures.", url: "https://www.factsage.com/" },
    { id: "step-8", label: "Materials Characterization", tool: "SEM/TEM/XRD", description: "Master a comprehensive suite of experimental techniques to probe material structure and composition from the atomic to macroscopic scale. Learn to operate and interpret data from scanning electron microscopy (SEM), transmission electron microscopy (TEM), X-ray diffraction (XRD), energy-dispersive X-ray spectroscopy (EDS), and atomic force microscopy (AFM). Combine characterization methods with statistical analysis to build complete structure-property relationships that validate theoretical predictions and guide material optimization.", url: "https://www.thermofisher.com/" },
    { id: "step-9", label: "Computational Materials Science", tool: "ASE/VASP", description: "Use density functional theory (DFT) and molecular dynamics (MD) simulations to predict material properties from first principles without experimental fabrication. Learn to set up and run quantum mechanical calculations using tools like VASP and Quantum ESPRESSO to determine electronic structures, total energies, and phonon spectra. Leverage the Atomic Simulation Environment (ASE) to automate high-throughput screening of candidate materials for targeted property optimization.", url: "https://wiki.fysik.dtu.dk/ase/" },
    { id: "step-10", label: "Nanomaterials", tool: "MATLAB", description: "Explore the synthesis, assembly, and characterization of materials with at least one dimension below 100 nanometers, including nanoparticles, nanowires, nanotubes, and 2D materials like graphene. Understand quantum confinement effects, surface energy contributions, and size-dependent properties that make nanomaterials fundamentally different from their bulk counterparts. Apply computational and statistical tools such as MATLAB to model nanoparticle interactions, size distributions, and self-assembly processes for nanotechnology applications.", url: "https://www.mathworks.com/" },
    { id: "step-11", label: "Biomaterials", tool: "COMSOL", description: "Design materials that interact with biological systems for medical implants, tissue engineering scaffolds, drug delivery vehicles, and biosensors. Study biocompatibility, biodegradation, and host-tissue response to engineer materials that support cell adhesion, proliferation, and differentiation while minimizing immune rejection. Use multi-physics simulation tools like COMSOL to model fluid-structure interactions, mass transport, and mechanical loading in biological environments before prototype fabrication.", url: "https://www.comsol.com/" },
    { id: "step-12", label: "Energy Materials", tool: "Materials Project", description: "Develop materials for energy harvesting, storage, and conversion applications including lithium-ion and solid-state batteries, fuel cells, photovoltaics, and thermoelectric devices. Study electrochemical principles, charge transport mechanisms, and degradation pathways to improve the efficiency, cycle life, and safety of energy storage and conversion systems. Access high-throughput databases like the Materials Project to screen thousands of candidate compositions and identify promising materials for next-generation energy technologies.", url: "https://materialsproject.org/" },
    { id: "step-13", label: "Materials Selection & Design", tool: "CES EduPack", description: "Integrate knowledge from all previous steps to systematically select, design, and optimize materials for real-world engineering applications using Ashby methodology and materials property charts. Learn to balance competing performance requirements, cost constraints, environmental impact, and manufacturing feasibility during the material selection process. Use software tools like Granta CES EduPack to compare material candidates across hundreds of properties and make data-driven decisions that satisfy both technical specifications and sustainability goals.", url: "https://www.elsevier.com/products/ces-edupack" },
  ],
};
