import { Roadmap } from "../types/roadmap";

export const mechanicalEngineerRoadmap: Roadmap = {
  id: "mechanical-engineer",
  title: "Mechanical Engineer",
  description: "Design, analyze, and manufacture mechanical systems and components.",
  introduction: "Mechanical engineering designs and analyzes physical systems and components. Learn CAD, thermodynamics, FEA, fluid mechanics, and manufacturing.",
  icon: "⚙️",
  category: "Engineering",
  difficulty: "Advanced",
  estimatedTime: "8-12 months",
  steps: [
    {
      id: "step-1",
      label: "Engineering Drawing",
      tool: "SolidWorks",
      description: "Engineering drawing is the foundational skill for communicating design intent through precise 2D and 3D representations. Master drafting standards, dimensioning conventions, and geometric tolerancing to create production-ready drawings. Learn to use SolidWorks or AutoCAD to build parametric models that can be easily modified and iterated upon.",
      url: "https://www.solidworks.com/solution/3dexperience-solidworks-offers",
    },
    {
      id: "step-2",
      label: "Thermodynamics",
      tool: "Heat Transfer",
      description: "Thermodynamics governs the behavior of energy systems, heat engines, and thermal processes in mechanical design. Study the laws of thermodynamics, Carnot cycles, and entropy to analyze the efficiency of power plants, refrigeration systems, and HVAC equipment. Understanding heat transfer mechanisms—conduction, convection, and radiation—is essential for designing components that operate under extreme temperature conditions.",
      url: "https://www.thermopedia.com/",
    },
    {
      id: "step-3",
      label: "Mechanics",
      tool: "FEA",
      description: "Mechanics is the study of forces, stresses, and deformations in solid bodies under load. Learn statics, dynamics, and strength of materials to predict how structures respond to mechanical forces. Finite Element Analysis (FEA) tools like ANSYS or Abaqus allow you to simulate complex stress distributions, fatigue life, and failure modes before a part is ever manufactured.",
      url: "https://www.ansys.com/",
    },
    {
      id: "step-4",
      label: "Fluid Mechanics",
      tool: "CFD",
      description: "Fluid mechanics deals with the behavior of liquids and gases at rest and in motion across a wide range of engineering applications. Study Bernoulli's equation, Navier-Stokes equations, and boundary layer theory to understand pressure drops, turbulence, and flow separation. Computational Fluid Dynamics (CFD) software enables you to simulate airflow over airfoils, water flow through pipes, and thermal management in electronics cooling.",
      url: "https://www.ansys.com/products/fluids",
    },
    {
      id: "step-5",
      label: "Manufacturing",
      tool: "CNC",
      description: "Manufacturing is the process of transforming raw materials into functional components and assemblies through various production methods. Learn CNC machining, sheet metal fabrication, injection molding, and additive manufacturing to select the right process for each application. Understanding Design for Manufacturability (DFM) principles ensures your designs can be produced efficiently at scale while minimizing cost and waste.",
      url: "https://www.haascnc.com/",
    },
    {
      id: "step-6",
      label: "Robotics",
      tool: "Kinematics",
      description: "Robotics integrates mechanical design with electronics and software to create machines capable of autonomous or semi-autonomous tasks. Study forward and inverse kinematics to design robot arms that follow precise trajectories in manufacturing environments. Learn about actuators, sensors, and motion planning to build systems that can pick, place, weld, or assemble components with high repeatability.",
      url: "https://www.fanucamerica.com/",
    },
    {
      id: "step-7",
      label: "Materials Science",
      tool: "Material Properties",
      description: "Materials science explores the relationship between the structure, properties, and performance of engineering materials. Study metallurgy, polymers, ceramics, and composites to select the optimal material for a given mechanical application based on strength, weight, corrosion resistance, and cost. Understanding phase diagrams, heat treatment processes, and material fatigue behavior is critical for ensuring long-term reliability of mechanical components.",
      url: "https://www.matweb.com/",
    },
    {
      id: "step-8",
      label: "Control Systems",
      tool: "MATLAB/Simulink",
      description: "Control systems engineering deals with modeling dynamic systems and designing feedback loops to achieve desired behavior. Learn PID controllers, transfer functions, and state-space representation to regulate speed, position, temperature, and pressure in mechanical systems. MATLAB and Simulink provide powerful tools for simulating control strategies and tuning parameters before deploying them on physical hardware.",
      url: "https://www.mathworks.com/products/simulink.html",
    },
    {
      id: "step-9",
      label: "Mechatronics",
      tool: "Arduino/PLC",
      description: "Mechatronics is the interdisciplinary field that combines mechanical engineering, electronics, computer science, and control theory into integrated systems. Design electromechanical assemblies that use microcontrollers like Arduino or industrial PLCs to sense their environment and respond to inputs. This skill set is essential for developing smart products, automated machinery, and Internet of Things (IoT) devices that bridge the physical and digital worlds.",
      url: "https://www.arduino.cc/",
    },
    {
      id: "step-10",
      label: "Product Design",
      tool: "Design Thinking",
      description: "Product design transforms user needs and market requirements into tangible mechanical solutions through a structured creative process. Apply design thinking methodologies—empathize, define, ideate, prototype, and test—to develop products that are functional, manufacturable, and aesthetically appealing. Consider ergonomics, sustainability, and cost constraints early in the design phase to avoid costly redesigns later in the development cycle.",
      url: "https://wwwIDEO.org/",
    },
    {
      id: "step-11",
      label: "Prototyping",
      tool: "3D Printing",
      description: "Prototyping is the rapid creation of physical models to validate design concepts, test functionality, and gather stakeholder feedback before committing to full production. Use FDM, SLA, or SLS 3D printing technologies to quickly iterate on form, fit, and function of mechanical parts. Iterate rapidly between digital models and physical prototypes to identify and resolve design flaws early, reducing development time and cost.",
      url: "https://www.ultimaker.com/",
    },
    {
      id: "step-12",
      label: "Project Management",
      tool: "Agile/Waterfall",
      description: "Project management provides the framework for planning, executing, and delivering engineering projects on time and within budget. Learn to define project scope, create work breakdown structures, and manage resources using tools like Gantt charts and Agile sprints. Effective communication with cross-functional teams—including electrical engineers, software developers, and manufacturing partners—is critical for coordinating complex product development efforts.",
      url: "https://www.pmi.org/",
    },
  ],
};
