import { Roadmap } from "../types/roadmap";

export const mentalHealthCounselorRoadmap: Roadmap = {
  id: "mental-health-counselor",
  title: "Mental Health Counselor",
  description: "A comprehensive roadmap to becoming a licensed mental health counselor, covering foundational psychology, therapeutic techniques, and professional practice.",
  introduction: "Mental health counseling is a rewarding career dedicated to helping individuals navigate psychological challenges and improve their well-being. This roadmap guides you from foundational psychology concepts through advanced clinical practice, preparing you to provide effective, ethical, and culturally competent care to diverse populations.",
  icon: "🧠",
  category: "Healthcare",
  difficulty: "Intermediate",
  estimatedTime: "2-4 years",
  steps: [
    {
      id: "step-1",
      label: "Psychology Foundations",
      tool: "Core Psychology",
      description: "Begin with the fundamental principles of psychology, including major psychological theories, research methods, and the biological bases of behavior. Understand key concepts like learning, memory, perception, motivation, and emotion that form the bedrock of human behavior. These foundational principles inform every aspect of clinical practice and therapeutic intervention.",
      url: "https://www.apa.org/education-career/k1/what-is-psychology",
    },
    {
      id: "step-2",
      label: "Human Development",
      tool: "Developmental Psychology",
      description: "Study the physical, cognitive, and socioemotional changes that occur across the lifespan from infancy through old age. Master key developmental theorists including Piaget, Erikson, Vygotsky, and Bowlby, and understand their frameworks for development. This knowledge helps you assess clients' developmental appropriateness and anticipate challenges at each life stage.",
      url: "https://www.simplypsychology.org/developmental-psychology.html",
    },
    {
      id: "step-3",
      label: "Theories of Counseling",
      tool: "Counseling Theories",
      description: "Explore the major theoretical orientations including psychodynamic, humanistic, cognitive-behavioral, existential, and family systems approaches. Understand the philosophical underpinnings, historical development, and practical applications of each theory. Learning multiple orientations gives you flexibility to adapt your approach to each client's unique needs and preferences.",
      url: "https://www.simplypsychology.org/counseling-theories.html",
    },
    {
      id: "step-4",
      label: "Psychopathology",
      tool: "Diagnostic Classification",
      description: "Study the classification, etiology, and presentation of mental health disorders using the DSM-5-TR and ICD-11 diagnostic systems. Understand diagnostic criteria, differential diagnosis, and the interplay between biological, psychological, and social factors in mental illness. This knowledge is essential for accurate assessment and effective treatment planning.",
      url: "https://www.psychiatry.org/psychiatrists/practice/dsm",
    },
    {
      id: "step-5",
      label: "Assessment & Diagnosis",
      tool: "Clinical Assessment",
      description: "Develop skills in conducting comprehensive clinical interviews, administering standardized psychological assessments, and interpreting results. Learn to use assessment tools such as the MMPI, Beck Depression Inventory, and GAD-7 to inform diagnosis and treatment planning. Proficiency in assessment ensures you can accurately identify client needs and track progress throughout therapy.",
      url: "https://www.apa.org/assessment/interview",
    },
    {
      id: "step-6",
      label: "Therapeutic Approaches",
      tool: "CBT & DBT",
      description: "Master Cognitive Behavioral Therapy (CBT) and Dialectical Behavior Therapy (DBT) as evidence-based interventions for a wide range of conditions. Learn core CBT techniques including cognitive restructuring, behavioral activation, and exposure therapy. Study DBT skills such as mindfulness, distress tolerance, emotion regulation, and interpersonal effectiveness for clients with emotional dysregulation.",
      url: "https://beckinstitute.org/cognitive-behavioral-therapy/",
    },
    {
      id: "step-7",
      label: "Trauma-Informed Care",
      tool: "Trauma Therapy",
      description: "Understand the neurobiological impact of trauma and adopt a trauma-informed framework that prioritizes safety, trustworthiness, and client empowerment. Learn evidence-based trauma therapies including EMDR, Somatic Experiencing, and Prolonged Exposure therapy. Trauma-informed care recognizes the widespread impact of trauma and integrates this knowledge into every aspect of service delivery.",
      url: "https://www.samhsa.gov/trauma-violence",
    },
    {
      id: "step-8",
      label: "Substance Abuse",
      tool: "Addiction Counseling",
      description: "Study the biopsychosocial model of addiction, diagnostic criteria for substance use disorders, and evidence-based treatment modalities. Learn motivational interviewing, relapse prevention strategies, and how to integrate co-occurring mental health disorders into treatment planning. Understanding addiction is critical as substance use disorders frequently co-occur with other mental health conditions.",
      url: "https://www.samhsa.gov/find-help/national-helpline",
    },
    {
      id: "step-9",
      label: "Ethics & Legal Issues",
      tool: "Professional Ethics",
      description: "Master the ethical codes and standards set by organizations like the American Counseling Association (ACA) and state licensing boards. Understand confidentiality, informed consent, mandated reporting, duty to warn, boundary issues, and documentation requirements. Ethical practice is the foundation of client trust and professional integrity in mental health counseling.",
      url: "https://www.counseling.org/resources/ethics",
    },
    {
      id: "step-10",
      label: "Cultural Competence",
      tool: "Diverse Populations",
      description: "Develop the ability to work effectively with clients from diverse cultural, racial, ethnic, socioeconomic, and LGBTQ+ backgrounds. Study multicultural counseling competencies, implicit bias, intersectionality, and culturally adapted interventions. Cultural competence goes beyond awareness to include skills and knowledge that enable respectful and effective care for all populations.",
      url: "https://www.div17.org/",
    },
    {
      id: "step-11",
      label: "Crisis Intervention",
      tool: "Crisis Response",
      description: "Learn to assess and respond to mental health crises including suicidal ideation, self-harm, psychosis, and acute trauma. Master de-escalation techniques, safety planning, and coordination with emergency services and psychiatric resources. Effective crisis intervention can be life-saving and is a critical competency for any practicing mental health professional.",
      url: "https://988lifeline.org/",
    },
    {
      id: "step-12",
      label: "Professional Practice",
      tool: "Clinical Practice",
      description: "Gain supervised clinical experience through practicum and internship placements to apply theoretical knowledge in real-world settings. Develop skills in case conceptualization, treatment planning, progress documentation, and interdisciplinary collaboration. This hands-on experience is essential for licensure and builds the confidence needed to practice independently as a mental health counselor.",
      url: "https://www.cacrep.org/",
    },
    {
      id: "step-13",
      label: "Licensure & Continuing Education",
      tool: "License Preparation",
      description: "Complete the requirements for state licensure, which typically include a master's degree, supervised clinical hours, and passing the National Counselor Examination (NCE). Maintain your license through continuing education credits and stay current with evolving research and best practices. Lifelong learning ensures you provide the highest quality care throughout your career.",
      url: "https://www.nbcc.org/",
    },
  ],
};
