import { Roadmap } from "../types/roadmap";

export const mobileDeveloperRoadmap: Roadmap = {
  id: "mobile-developer",
  title: "Mobile Developer",
  description: "Build native and cross-platform mobile applications for iOS and Android.",
  introduction: "Mobile development creates native apps for iOS and Android platforms. Learn Kotlin, Jetpack Compose, Flutter, and app architecture to build high-performance mobile experiences.",
  icon: "📲",
  category: "Engineering",
  difficulty: "Intermediate",
  estimatedTime: "4-8 months",
  steps: [
    {
      id: "step-1",
      label: "Programming Language",
      tool: "Kotlin",
      description: "Master a modern language for Android development. Learn null safety, coroutines, extension functions, and sealed classes. Kotlin is Google's recommended language for Android — it's concise, safe, and interoperable with Java.",
      url: "https://developer.android.com/kotlin",
    },
    {
      id: "step-2",
      label: "UI Toolkit",
      tool: "Jetpack Compose",
      description: "Build declarative, reactive Android UIs with composable functions. Learn state management, animations, theming, and Material Design 3 components. Compose is the future of Android UI — it eliminates XML layouts and boilerplate.",
      url: "https://developer.android.com/jetpack/compose",
    },
    {
      id: "step-3",
      label: "App Architecture",
      tool: "MVVM",
      description: "Structure apps with clear separation of concerns using Model-View-ViewModel. Learn about unidirectional data flow, repository pattern, and dependency injection with Hilt. Good architecture makes apps testable, maintainable, and scalable.",
      url: "https://developer.android.com/topic/architecture",
    },
    {
      id: "step-4",
      label: "Navigation",
      tool: "Navigation Compose",
      description: "Implement screen navigation with the Navigation component. Handle deep linking, nested navigation graphs, and argument passing. Navigation is one of the most complex parts of mobile apps — getting it right early saves headaches later.",
      url: "https://developer.android.com/jetpack/compose/navigation",
    },
    {
      id: "step-5",
      label: "Networking",
      tool: "Retrofit",
      description: "Make HTTP requests and consume REST APIs from mobile apps. Learn request/response interceptors, authentication headers, and error handling. Retrofit is the standard for HTTP clients on Android — it handles serialization and type safety.",
      url: "https://square.github.io/retrofit/",
    },
    {
      id: "step-6",
      label: "Local Storage",
      tool: "Room",
      description: "Persist data locally with an SQLite abstraction layer. Learn entities, DAOs, migrations, and reactive queries with Flow. Room provides compile-time verification of SQL queries — catching database bugs before they reach production.",
      url: "https://developer.android.com/training/data-storage/room",
    },
    {
      id: "step-7",
      label: "Background Work",
      tool: "WorkManager",
      description: "Schedule deferrable, guaranteed background work like syncing data, uploading logs, or sending notifications. Learn about constraints, chaining, and retry policies. Background work is battery-sensitive — WorkManager respects system constraints.",
      url: "https://developer.android.com/topic/libraries/architecture/workmanager",
    },
    {
      id: "step-8",
      label: "State Management",
      tool: "StateFlow",
      description: "Manage UI state with Kotlin coroutines and Flow. Learn StateFlow, SharedFlow, and how to handle loading, success, and error states. Proper state management prevents bugs like stale UI, race conditions, and memory leaks.",
      url: "https://developer.android.com/kotlin/flow",
    },
    {
      id: "step-9",
      label: "Testing",
      tool: "Espresso",
      description: "Write unit tests with JUnit, UI tests with Espresso, and screenshot tests with Paparazzi. Test ViewModels with Turbine for Flow. Mobile testing is harder than web testing — device fragmentation makes automated tests essential.",
      url: "https://developer.android.com/training/testing/espresso",
    },
    {
      id: "step-10",
      label: "Cross-Platform",
      tool: "Flutter",
      description: "Build iOS and Android apps from a single Dart codebase with Flutter's widget system. Learn hot reload, custom widgets, and platform channels. Flutter is the fastest way to ship to both platforms without maintaining two codebases.",
      url: "https://docs.flutter.dev/",
    },
    {
      id: "step-11",
      label: "Performance",
      tool: "Android Profiler",
      description: "Profile CPU, memory, network, and battery usage. Identify jank, memory leaks, and excessive battery drain. Mobile users are ruthless about performance — a laggy app gets uninstalled in seconds.",
      url: "https://developer.android.com/studio/profile",
    },
    {
      id: "step-12",
      label: "Security",
      tool: "EncryptedSharedPreferences",
      description: "Store sensitive data with encryption, use network security configurations, and implement certificate pinning. Apply ProGuard/R8 for code obfuscation. Mobile apps run on untrusted devices — security can't be an afterthought.",
      url: "https://developer.android.com/topic/security/data",
    },
    {
      id: "step-13",
      label: "Publishing",
      tool: "Google Play Console",
      description: "Release apps with proper signing, versioning, store listings, and staged rollouts. Understand review policies, crash reporting, and user feedback. Publishing is where your app meets the real world — store optimization matters.",
      url: "https://developer.android.com/distribute/console",
    },
  ],
};
