import { Roadmap } from "../types/roadmap";

export const qaTestEngineerRoadmap: Roadmap = {
  id: "qa-test-engineer",
  title: "QA Test Engineer",
  description: "Design and execute comprehensive test strategies to ensure software quality, reliability, and user satisfaction.",
  introduction: "QA engineering ensures software quality through systematic testing strategies. Learn test planning, manual and exploratory testing, automation with Playwright, API testing with Postman, performance testing with k6, security testing, mobile testing, CI/CD integration, test reporting, and accessibility testing.",
  icon: "🧪",
  category: "Engineering",
  difficulty: "Intermediate",
  estimatedTime: "4-8 months",
  steps: [
    { id: "step-1", label: "Testing Fundamentals", tool: "ISTQB", description: "Learn core testing concepts including test levels, test types, and the software testing lifecycle. Understand defect life cycles, boundary value analysis, equivalence partitioning, and risk-based testing approaches. Master test design techniques such as decision tables, state transitions, and use case testing.", url: "https://www.istqb.org/certifications/ctfl.html" },
    { id: "step-2", label: "Test Planning", tool: "Test Cases", description: "Write comprehensive test plans that define scope, objectives, resources, and schedules for testing efforts. Create detailed test cases with clear preconditions, steps, and expected results that are easy to maintain and reuse. Learn to estimate testing effort and prioritize test cases based on risk and business impact.", url: "https://www.guru99.com/test-plan.html" },
    { id: "step-3", label: "Manual Testing", tool: "Browsers", description: "Perform hands-on testing to verify functionality, usability, and visual correctness of applications. Practice functional testing workflows including smoke tests, regression tests, and end-to-end scenario validation. Develop strong observation skills and attention to detail to catch issues that automated tests might miss.", url: "https://www.ministryoftesting.com/" },
    { id: "step-4", label: "Exploratory Testing", tool: "Tour Techniques", description: "Discover bugs through creative, ad-hoc testing that combines learning, test design, and test execution simultaneously. Apply session-based test management to structure exploratory sessions and document charter-based investigations. Use heuristic models like SFDPOT (Structure, Function, Data, Platform, Operations, Time) to guide systematic exploration.", url: "https://www.ministryoftesting.com/dojo/classes/exploratory-testing" },
    { id: "step-5", label: "Test Automation", tool: "Playwright", description: "Write reliable end-to-end browser tests using Playwright's modern APIs and cross-browser support. Master page object models, fixtures, and test hooks to build maintainable and scalable test suites. Run tests in parallel across Chromium, Firefox, and WebKit to catch browser-specific issues early.", url: "https://playwright.dev/docs/intro" },
    { id: "step-6", label: "API Testing", tool: "Postman", description: "Validate REST and GraphQL APIs by crafting requests and writing automated test scripts for responses. Build reusable collections, environments, and data-driven tests to cover edge cases and error handling scenarios. Use Postman's Newman CLI to integrate API tests into automated pipelines for continuous validation.", url: "https://learning.postman.com/docs/" },
    { id: "step-7", label: "Performance Testing", tool: "k6", description: "Load test applications to measure throughput, response times, and stability under varying levels of user traffic. Write k6 scripts to simulate realistic user journeys and identify performance bottlenecks before production. Analyze results using thresholds, SLA metrics, and trend data to make data-driven optimization decisions.", url: "https://k6.io/docs/" },
    { id: "step-8", label: "Security Testing", tool: "OWASP ZAP", description: "Identify common vulnerabilities such as SQL injection, cross-site scripting, and insecure authentication flows. Learn to use OWASP ZAP for automated scanning and manual security assessment of web applications. Understand the OWASP Top 10 and integrate security checks into your testing workflow to prevent critical exploits.", url: "https://www.zaproxy.org/docs/" },
    { id: "step-9", label: "Mobile Testing", tool: "Appium", description: "Test native and hybrid mobile applications across Android and iOS platforms using Appium's cross-platform framework. Write automated mobile tests that handle gestures, device rotations, and app lifecycle events reliably. Use cloud device farms to validate functionality on a wide range of real devices and OS versions.", url: "https://appium.io/docs/en/about-appium/intro/" },
    { id: "step-10", label: "CI/CD Integration", tool: "GitHub Actions", description: "Configure automated test suites to run on every pull request and merge to catch regressions early in the development cycle. Set up test environments, manage secrets, and parallelize test execution for fast and reliable feedback. Use pipeline orchestration to gate deployments based on test pass rates and quality metrics.", url: "https://docs.github.com/en/actions" },
    { id: "step-11", label: "Test Reporting", tool: "Allure", description: "Generate detailed test reports with Allure to visualize pass rates, failure trends, and flaky test patterns over time. Create dashboards that provide stakeholders with clear insights into test coverage, defect distribution, and risk areas. Use historical reporting to track quality improvements and identify regression hotspots across releases.", url: "https://allurereport.org/docs/" },
    { id: "step-12", label: "Accessibility Testing", tool: "axe-core", description: "Audit applications against WCAG 2.1 guidelines to ensure usability for people with disabilities including screen readers and keyboard navigation. Integrate axe-core and Lighthouse into automated test suites to catch accessibility violations early. Combine automated scanning with manual testing to address issues that automated tools cannot detect.", url: "https://www.deque.com/axe/" },
  ],
};
