import { Roadmap } from "../types/roadmap";

export const quantumComputingResearcherRoadmap: Roadmap = {
  id: "quantum-computing-researcher",
  title: "Quantum Computing Researcher",
  description: "Explore quantum algorithms, circuits, and hardware for next-generation computing.",
  introduction: "Quantum computing research explores algorithms and hardware for next-generation computing. Master linear algebra, quantum mechanics, Qiskit, and error correction.",
  icon: "⚛️",
  category: "Science",
  difficulty: "Expert",
  estimatedTime: "12-18 months",
  steps: [
    {
      id: "step-1",
      label: "Linear Algebra",
      tool: "Linear Algebra",
      description: "Master vector spaces, eigenvalues, and tensor products. Linear algebra forms the mathematical backbone of quantum computing, providing the language to describe quantum states and transformations. Develop fluency with matrices, complex numbers, and Hilbert spaces to reason about quantum circuits rigorously.",
      url: "https://www.khanacademy.org/math/linear-algebra",
    },
    {
      id: "step-2",
      label: "Quantum Mechanics",
      tool: "Quantum Mechanics",
      description: "Understand superposition, entanglement, and measurement. Quantum mechanics introduces the probabilistic nature of reality at the subatomic scale, which quantum computers exploit for computational advantage. Study wave functions, the Schrödinger equation, and the measurement postulate to build physical intuition.",
      url: "https://www.quantum.country/",
    },
    {
      id: "step-3",
      label: "Quantum Gates",
      tool: "Qiskit",
      description: "Build quantum circuits with Hadamard, CNOT, and Toffoli gates. Quantum gates are the building blocks of quantum algorithms, manipulating qubits through unitary transformations. Practice composing gates in Qiskit to create complex multi-qubit circuits and visualize their effects on quantum states.",
      url: "https://qiskit.org/learn/",
    },
    {
      id: "step-4",
      label: "Algorithms",
      tool: "Shor/Grover",
      description: "Implement quantum algorithms for factoring and search. Study Shor's algorithm for integer factorization and Grover's algorithm for unstructured search to understand quantum speedup mechanisms. These landmark algorithms demonstrate how quantum parallelism and interference can solve problems exponentially faster than classical approaches.",
      url: "https://qiskit.org/learn/algorithms",
    },
    {
      id: "step-5",
      label: "Error Correction",
      tool: "Surface Codes",
      description: "Protect quantum information from decoherence and noise. Quantum error correction is essential for building fault-tolerant quantum computers that can survive real-world noise. Learn surface codes, the stabilizer formalism, and fault-tolerant thresholds to understand how logical qubits are encoded in noisy physical qubits.",
      url: "https://docs.quantum.ibm.com/",
    },
    {
      id: "step-6",
      label: "Simulation",
      tool: "Qiskit Aer",
      description: "Simulate quantum circuits on classical hardware. Quantum simulators allow you to test and debug algorithms before deploying them on real quantum processors. Use Qiskit Aer to run noiseless and noisy simulations, benchmark circuit performance, and verify theoretical predictions against simulated results.",
      url: "https://qiskit.org/documentation/",
    },
    {
      id: "step-7",
      label: "Hardware",
      tool: "IBM Quantum",
      description: "Run circuits on real quantum processors and interpret results. Understanding quantum hardware architectures—transmon qubits, ion traps, and photonic systems—helps you design algorithms that work within physical constraints. Access IBM Quantum systems to experience real device noise, connectivity limitations, and calibration variability firsthand.",
      url: "https://quantum.ibm.com/",
    },
    {
      id: "step-8",
      label: "Quantum Information Theory",
      tool: "Textbooks & Papers",
      description: "Study the theoretical limits of quantum information processing. Quantum information theory formalizes concepts like von Neumann entropy, channel capacity, and quantum data compression. This foundation is critical for understanding the fundamental advantages quantum systems offer over classical communication and computation.",
      url: "https://qiskit.org/learn/introduction-to-quantum-computing",
    },
    {
      id: "step-9",
      label: "Quantum Cryptography",
      tool: "QKD Protocols",
      description: "Explore quantum key distribution and post-quantum cryptography. Quantum cryptography leverages the no-cloning theorem and quantum measurement disturbance to create provably secure communication channels. Study BB84, E91, and modern post-quantum standards to understand how quantum technology reshapes the security landscape.",
      url: "https://qiskit.org/learn/programming-quantum-computers",
    },
    {
      id: "step-10",
      label: "Quantum Machine Learning",
      tool: "PennyLane / QML",
      description: "Apply quantum circuits to machine learning and optimization tasks. Quantum machine learning explores variational quantum eigensolvers, quantum kernel methods, and quantum neural networks for pattern recognition. Investigate hybrid classical-quantum architectures where quantum layers enhance expressivity in classical ML pipelines.",
      url: "https://pennylane.ai/qml/",
    },
    {
      id: "step-11",
      label: "Quantum Chemistry",
      tool: "OpenFermion / Qiskit Nature",
      description: "Simulate molecular systems and chemical reactions on quantum hardware. Quantum chemistry is one of the most promising near-term applications of quantum computing, enabling accurate modeling of electron correlation and reaction dynamics. Use variational algorithms to compute ground state energies of molecules beyond classical tractability limits.",
      url: "https://qiskit.org/ecosystem/nature/",
    },
    {
      id: "step-12",
      label: "Research Methods",
      tool: "ArXiv / Journals",
      description: "Develop skills to read, design, and publish quantum computing research. Stay current with breakthroughs on arXiv, review journals like Physical Review X and Quantum, and learn to formulate rigorous research questions. Master experimental design, statistical analysis, and peer review processes to contribute original findings to the field.",
      url: "https://arxiv.org/list/quant-ph/recent",
    },
  ],
};
