import { Roadmap } from "../types/roadmap";

export const quantitativeAnalystRoadmap: Roadmap = {
  id: "quantitative-analyst",
  title: "Quantitative Analyst",
  description: "Design and implement mathematical models for pricing, risk management, and algorithmic trading.",
  introduction: "Quantitative analysts sit at the intersection of mathematics, finance, and computer science. They build the models that drive pricing, hedging, and trading decisions at top financial institutions. This roadmap takes you from foundational statistics through to production-grade trading systems, equipping you with every skill needed to thrive in quant finance.",
  icon: "📈",
  category: "Finance",
  difficulty: "Expert",
  estimatedTime: "12-18 months",
  steps: [
    {
      id: "step-1",
      label: "Mathematical Statistics",
      tool: "Probability",
      description: "Build a rock-solid foundation in probability theory, hypothesis testing, maximum likelihood estimation, and Bayesian inference. Understand distributions — normal, log-normal, Poisson, and fat-tailed variants like Student's t — and know when each applies to financial data. Statistical literacy is the bedrock of every quant model; without it, you are curve-fitting noise and calling it alpha.",
      url: "https://www.investopedia.com/terms/s/statistics.asp",
    },
    {
      id: "step-2",
      label: "Financial Theory",
      tool: "Economics",
      description: "Master the Capital Asset Pricing Model (CAPM), Arbitrage Pricing Theory (APT), the Efficient Market Hypothesis, and core fixed-income concepts like term structure and duration. Learn how markets price risk, how interest rates propagate through asset classes, and why no-arbitrage arguments constrain pricing models. These theories are the conceptual scaffolding that gives quantitative models their economic meaning.",
      url: "https://www.investopedia.com/terms/c/capm.asp",
    },
    {
      id: "step-3",
      label: "Programming (Python/C++)",
      tool: "Python",
      description: "Become proficient in Python for rapid prototyping, data analysis, and scientific computing with NumPy, SciPy, and Pandas. Simultaneously develop strong C++ skills for building low-latency trading systems, pricing engines, and production-grade libraries where performance is non-negotiable. The dual-language fluency lets you prototype in Python and deploy in C++ — the standard workflow at every serious quant desk.",
      url: "https://www.python.org/doc/",
    },
    {
      id: "step-4",
      label: "Stochastic Calculus",
      tool: "Mathematics",
      description: "Dive into Brownian motion, Itô's lemma, geometric Brownian motion, and the Black-Scholes-Merton framework. Understand how stochastic differential equations model asset dynamics and how risk-neutral pricing transforms real-world dynamics into tradable prices. Stochastic calculus is the mathematical language of derivatives pricing — it separates those who can price exotic payoffs from those who can only use a spreadsheet.",
      url: "https://www.investopedia.com/terms/b/brownian-motion.asp",
    },
    {
      id: "step-5",
      label: "Time Series Analysis",
      tool: "Statistics",
      description: "Analyze financial time series using ARIMA, GARCH, cointegration, and state-space models. Learn to detect regime changes, estimate volatility clusters, and build forecasting models that respect the serial correlation structure of asset returns. Financial data is inherently temporal — naive cross-sectional methods will miss autocorrelation, volatility clustering, and mean reversion that drive real trading signals.",
      url: "https://www.investopedia.com/terms/a/arma.asp",
    },
    {
      id: "step-6",
      label: "Machine Learning for Finance",
      tool: "ML",
      description: "Apply supervised learning (random forests, gradient boosting, neural networks) and unsupervised techniques (PCA, clustering) to alpha generation, factor selection, and signal construction. Understand overfitting deeply — cross-validation, regularization, and out-of-sample testing are not optional in finance where data is scarce and regimes shift. Machine learning amplifies your edge, but only if you respect the unique pitfalls of financial data.",
      url: "https://www.investopedia.com/terms/m/machine-learning.asp",
    },
    {
      id: "step-7",
      label: "Risk Modeling",
      tool: "VaR",
      description: "Build Value-at-Risk (VaR), Conditional VaR, and Expected Shortfall models using historical simulation, Monte Carlo methods, and variance-covariance approaches. Develop stress testing frameworks that capture tail risk and correlation breakdown during market crises. Risk models protect capital — getting them wrong doesn't just lose money, it can bring down an entire firm, so rigor and humility are essential.",
      url: "https://www.investopedia.com/terms/v/var.asp",
    },
    {
      id: "step-8",
      label: "Portfolio Optimization",
      tool: "Optimization",
      description: "Implement mean-variance optimization, Black-Litterman models, and risk parity frameworks to construct portfolios that maximize risk-adjusted returns. Handle practical constraints like transaction costs, turnover limits, and long-short positioning in your optimization formulations. Modern portfolio theory is elegant in textbooks — making it work with real-world constraints, estimation error, and market frictions is where the real skill lies.",
      url: "https://www.investopedia.com/terms/m/meanvarianceanalysis.asp",
    },
    {
      id: "step-9",
      label: "Backtesting",
      tool: "Testing",
      description: "Design rigorous backtesting frameworks that avoid overfitting, survivorship bias, and lookahead bias. Implement walk-forward validation, slippage modeling, and realistic transaction cost assumptions to evaluate strategy performance under conditions that approximate live trading. A backtest that lies is worse than no backtest at all — the entire purpose is to discover your strategy's weaknesses before the market does.",
      url: "https://www.investopedia.com/terms/b/backtesting.asp",
    },
    {
      id: "step-10",
      label: "Derivatives Pricing",
      tool: "Pricing",
      description: "Price European and American options, barrier options, and interest rate derivatives using Black-Scholes, binomial trees, Monte Carlo simulation, and finite difference methods. Implement Greeks calculation and understand hedging replication strategies for managing option book risk. Derivatives pricing is where stochastic calculus meets market reality — every model is wrong, but some are wrong in ways you can hedge.",
      url: "https://www.investopedia.com/terms/o/option-pricing-theory.asp",
    },
    {
      id: "step-11",
      label: "Data Engineering",
      tool: "Infrastructure",
      description: "Build robust data pipelines that ingest, clean, and serve tick-level and bar-level market data with low latency. Work with time series databases, message queues (Kafka), and streaming architectures to ensure your models always have access to fresh, accurate data. The best model in the world is worthless if it's running on stale data — data engineering is the invisible backbone of quant trading.",
      url: "https://www.investopedia.com/terms/d/data-engineering.asp",
    },
    {
      id: "step-12",
      label: "Performance Monitoring",
      tool: "DevOps",
      description: "Implement live monitoring dashboards that track model predictions versus realized P&L, factor exposures, drawdown metrics, and regime indicators. Set up automated alerts for model degradation, data quality issues, and execution anomalies that deviate from expected behavior. Quantitative strategies drift and decay — continuous monitoring is how you catch problems before they become losses.",
      url: "https://www.investopedia.com/terms/p/performance-monitoring.asp",
    },
  ],
};
