import { Roadmap } from "../types/roadmap";

export const researchScientistRoadmap: Roadmap = {
  id: "research-scientist",
  title: "Research Scientist",
  description: "Conduct original research, publish findings, and advance scientific knowledge.",
  introduction: "Research science conducts original investigations to advance scientific knowledge. Learn research methods, statistics, programming, experiment design, and publishing.",
  icon: "🔬",
  category: "Science",
  difficulty: "Advanced",
  estimatedTime: "12-24 months",
  steps: [
    { id: "step-1", label: "Research Methods", tool: "Scientific Method", description: "Master the foundational principles of the scientific method, including hypothesis formulation, systematic observation, and evidence-based reasoning. Learn to distinguish between qualitative and quantitative approaches, understand the importance of controls, and apply critical thinking to evaluate research questions. These skills form the bedrock of all credible scientific inquiry.", url: "https://www.nature.com/articles/d41586-019-01579-x" },
    { id: "step-2", label: "Statistics", tool: "R", description: "Develop proficiency in statistical analysis using R, covering descriptive statistics, hypothesis testing, regression modeling, and Bayesian methods. Master data visualization with ggplot2 to communicate findings clearly and identify patterns in complex datasets. Understanding statistical power, effect sizes, and confidence intervals is essential for drawing valid conclusions from your research.", url: "https://www.r-project.org/" },
    { id: "step-3", label: "Programming", tool: "Python", description: "Learn Python programming for scientific computing, including libraries such as NumPy, pandas, SciPy, and scikit-learn for data manipulation and analysis. Build reproducible workflows with version control and modular code design to handle large-scale datasets efficiently. Programming skills enable automation of repetitive tasks and the development of custom analysis pipelines tailored to your research needs.", url: "https://www.python.org/doc/" },
    { id: "step-4", label: "Literature Review", tool: "Google Scholar", description: "Conduct comprehensive literature reviews using databases like Google Scholar, PubMed, and Web of Science to map the current state of knowledge in your field. Learn to critically appraise published studies for methodology, validity, and relevance to your own research questions. A thorough review helps you identify gaps in existing knowledge and position your work to make meaningful contributions.", url: "https://scholar.google.com/" },
    { id: "step-5", label: "Experiment Design", tool: "A/B Testing", description: "Design rigorous experiments with proper controls, randomization, and blinding to minimize bias and maximize internal validity. Understand concepts such as sample size estimation, counterbalancing, and factorial designs to address multiple variables simultaneously. Well-designed experiments produce reliable, interpretable results that can withstand scrutiny during peer review.", url: "https://www.optimizely.com/optimization-glossary/ab-testing/" },
    { id: "step-6", label: "Publishing", tool: "LaTeX", description: "Write and format research papers for peer-reviewed journals using LaTeX for professional-quality typesetting and consistent formatting. Learn the conventions of scientific writing, including abstracts, introduction structures, methods sections, and discussion formats. Understanding journal submission processes, cover letters, and response-to-reviewer protocols significantly increases your chances of successful publication.", url: "https://www.latex-project.org/" },
    { id: "step-7", label: "Collaboration", tool: "GitHub", description: "Use GitHub for version control, collaborative coding, and transparent sharing of research data and analysis scripts with your team. Learn best practices for branching strategies, pull requests, and issue tracking to manage multi-contributor projects effectively. Open collaboration accelerates scientific progress by enabling others to build upon, verify, and extend your work.", url: "https://github.com/" },
    { id: "step-8", label: "Grant Writing", tool: "Funding Portals", description: "Master the art of writing compelling grant proposals that clearly articulate your research vision, methodology, and expected impact. Learn to navigate funding agencies such as NIH, NSF, and ERC, understanding their specific requirements and review criteria. Securing external funding is often essential for sustaining a research program and accessing the resources needed for ambitious projects.", url: "https://www.grants.gov/" },
    { id: "step-9", label: "Data Management", tool: "DVC", description: "Implement robust data management practices including proper storage, organization, backup strategies, and adherence to FAIR principles (Findable, Accessible, Interoperable, Reusable). Learn to use tools like DVC for data versioning and metadata documentation to track how datasets evolve throughout a project. Good data management ensures the long-term value of your research assets and facilitates data sharing with collaborators and the broader community.", url: "https://dvc.org/" },
    { id: "step-10", label: "Reproducible Research", tool: "Jupyter Notebooks", description: "Build reproducible research pipelines using Jupyter notebooks, containerization with Docker, and automated workflows to ensure your results can be independently verified. Document every step of your analysis from raw data to final figures so that other researchers can follow and replicate your methods. Reproducibility is a cornerstone of scientific integrity and is increasingly mandated by journals and funding agencies.", url: "https://jupyter.org/" },
    { id: "step-11", label: "Peer Review", tool: "Reviewer Guidelines", description: "Develop the skills to provide constructive, thorough peer reviews for journal submissions and conference papers. Learn to evaluate manuscripts for methodological rigor, novelty, clarity of presentation, and appropriate citation of prior work. Participating in peer review not only strengthens the scientific literature but also deepens your own understanding of research standards and best practices.", url: "https://www.elsevier.com/reviewer/how-to-review" },
    { id: "step-12", label: "Science Communication", tool: "Public Speaking", description: "Communicate your research findings effectively to both specialist and non-specialist audiences through presentations, publications, and public outreach. Develop skills in visual storytelling, data visualization, and narrative construction to make complex concepts accessible and engaging. Strong science communication amplifies the impact of your research and helps build public trust in scientific institutions.", url: "https://www.computer.org/" },
  ],
};
