import { Roadmap } from "../types/roadmap";

export const roboticsEngineerRoadmap: Roadmap = {
  id: "robotics-engineer",
  title: "Robotics Engineer",
  description: "Build autonomous robots with perception, planning, and control systems.",
  introduction: "Robotics engineering combines mechanical design, electronics, and software to create intelligent machines. Master C++, ROS 2, kinematics, computer vision, and path planning to build robots that perceive, decide, and act autonomously.",
  icon: "🤖",
  category: "Engineering",
  difficulty: "Advanced",
  estimatedTime: "12-18 months",
  steps: [
    {
      id: "step-1",
      label: "Mechanics & Actuators",
      tool: "CAD / 3D Printing",
      description: "Understand the mechanical principles behind robotic joints, linkages, gear trains, and structural frames. Learn to select and work with stepper motors, servo motors, and DC motors based on torque, speed, and precision requirements. Gain proficiency in CAD tools like Fusion 360 or SolidWorks to design and prototype robot chassis and custom mechanical components.",
      url: "https://www.autodesk.com/products/fusion-360/overview",
    },
    {
      id: "step-2",
      label: "Electronics & Sensors",
      tool: "PCB Design / Soldering",
      description: "Learn to design circuits, read schematics, and work with microcontrollers such as Arduino and ESP32 to interface with the physical world. Understand sensors including LiDAR, IMUs, ultrasonic rangefinders, and encoders that provide robots with environmental awareness. Build skills in signal conditioning, ADC conversion, and communication protocols like I2C, SPI, and UART to connect sensor data to higher-level systems.",
      url: "https://www.arduino.cc/",
    },
    {
      id: "step-3",
      label: "C++ Programming",
      tool: "C++ / STL",
      description: "Master C++ as the primary language for performance-critical robotics software where deterministic timing and memory control are essential. Learn smart pointers, RAII, templates, and multithreading with std::thread and mutexes to build robust concurrent systems. Practice object-oriented and generic programming patterns commonly used in robotics frameworks and libraries.",
      url: "https://isocpp.org/get-started",
    },
    {
      id: "step-4",
      label: "ROS (Robot Operating System)",
      tool: "ROS 2 Humble / Jazzy",
      description: "Build modular, distributed robot software using the Robot Operating System 2 publish-subscribe messaging framework. Learn topics, services, actions, and parameter management to create composable nodes that handle perception, planning, and control. Understand DDS middleware and quality-of-service policies for reliable real-time communication between heterogeneous robot subsystems.",
      url: "https://docs.ros.org/",
    },
    {
      id: "step-5",
      label: "Computer Vision",
      tool: "OpenCV / PCL",
      description: "Detect objects, track features, and segment scenes using camera-based perception pipelines built with OpenCV and depth sensors. Learn image filtering, edge detection, feature matching, and deep learning-based object detection for real-time robot vision. Implement visual servoing and camera calibration to enable robots to interact with their environment using visual feedback.",
      url: "https://docs.opencv.org/4.x/d6/d00/tutorial_py_root.html",
    },
    {
      id: "step-6",
      label: "Motion Planning",
      tool: "MoveIt 2 / Nav2",
      description: "Plan collision-free trajectories for robotic manipulators and mobile robots using sampling-based planners like RRT and PRM. Use MoveIt 2 for high-dimensional manipulation tasks and Nav2 for mobile robot navigation through mapped environments. Integrate grasping, pick-and-place, and obstacle avoidance to enable autonomous operation in dynamic spaces.",
      url: "https://moveit.picknik.ai/",
    },
    {
      id: "step-7",
      label: "Control Theory",
      tool: "PID / MPC",
      description: "Stabilize motion and track trajectories using PID controllers and modern control techniques like model-predictive control. Tune proportional, integral, and derivative gains to achieve desired transient response, steady-state accuracy, and disturbance rejection. Extend to cascaded control loops, feedforward terms, and state-space methods for complex multi-axis robotic systems.",
      url: "https://www.piddigital.com/",
    },
    {
      id: "step-8",
      label: "SLAM",
      tool: "Cartographer / RTAB-Map",
      description: "Build maps of unknown environments while simultaneously localizing the robot within them using SLAM algorithms. Implement lidar-based SLAM with Cartographer or visual SLAM with RTAB-Map for robust mapping in diverse indoor and outdoor conditions. Handle loop closure detection, map optimization, and multi-session mapping to maintain consistency over long-duration missions.",
      url: "https://google-cartographer.readthedocs.io/",
    },
    {
      id: "step-9",
      label: "Sensor Fusion",
      tool: "Kalman Filter / TF2",
      description: "Combine data from LiDAR, IMU, cameras, and wheel encoders to produce accurate state estimates using Kalman filters and particle filters. Fuse complementary sensor modalities to overcome individual limitations such as noise, drift, and occlusion. Use TF2 in ROS 2 to manage coordinate frames and ensure temporal alignment between heterogeneous sensor streams.",
      url: "https://docs.ros.org/en/humble/Tutorials/Intermediate/Tf2/Introduction-To-Tf2.html",
    },
    {
      id: "step-10",
      label: "Machine Learning for Robotics",
      tool: "PyTorch / TensorFlow",
      description: "Apply reinforcement learning, imitation learning, and neural network perception to enable robots to learn behaviors from data and experience. Train models for object recognition, pose estimation, and policy learning that operate in real-time on embedded platforms. Understand sim-to-real transfer techniques that allow policies trained in simulation to generalize to physical robots.",
      url: "https://pytorch.org/",
    },
    {
      id: "step-11",
      label: "Simulation",
      tool: "Gazebo / Isaac Sim",
      description: "Test and validate robot software in realistic simulated environments using Gazebo, Ignition Gazebo, or NVIDIA Isaac Sim. Build virtual worlds with accurate physics, sensor models, and terrain to accelerate development cycles and reduce hardware risk. Integrate ROS 2 with simulation to debug perception and control pipelines before deploying on physical hardware in production.",
      url: "https://gazebosim.org/",
    },
    {
      id: "step-12",
      label: "Hardware Integration",
      tool: "Embedded / Real-Time",
      description: "Interface high-level software with physical hardware by bridging ROS 2 nodes to motor drivers, sensors, and real-time controllers. Understand communication protocols like CAN, EtherCAT, and DDS for reliable data exchange between computing boards and actuators. Design power distribution systems, select components, and manage cabling to meet payload, speed, and endurance requirements.",
      url: "https://docs.ros.org/en/humble/Tutorials/Intermediate/Realtime-Programming/Intro.html",
    },
    {
      id: "step-13",
      label: "Safety & Testing",
      tool: "ISO 10218 / CI/CD",
      description: "Design safety-critical robot systems by applying standards like ISO 10218 for industrial robots and ISO 13482 for personal care robots. Implement emergency stop mechanisms, collision detection, force limiting, and redundant sensors to protect humans sharing workspace with robots. Build automated test suites, continuous integration pipelines, and hardware-in-the-loop testing to validate robot behavior before real-world deployment.",
      url: "https://www.iso.org/standard/51330.html",
    },
  ],
};
