import { Roadmap } from "../types/roadmap";

export const salesEngineerRoadmap: Roadmap = {
  id: "sales-engineer",
  title: "Sales Engineer",
  description: "Technical sales support that bridges product capabilities with customer needs.",
  introduction: "Sales engineering bridges technical product capabilities with customer needs. Master solution selling, demo skills, RFP responses, and CRM.",
  icon: "💼",
  category: "Business",
  difficulty: "Intermediate",
  estimatedTime: "3-6 months",
  steps: [
    {
      id: "step-1",
      label: "Technical Sales",
      tool: "Solution Selling",
      description: "Master the art of translating complex technical features into clear business value for prospects. Build discovery frameworks that uncover root pain points and map your product's capabilities directly to measurable outcomes. Learn to quantify ROI and articulate value in language that resonates with both technical evaluators and C-suite executives.",
      url: "https://www.sandler.com/training/solution-selling",
    },
    {
      id: "step-2",
      label: "Demo Skills",
      tool: "Presentation",
      description: "Design and deliver compelling product demonstrations tailored to each stakeholder's priorities and technical depth. Practice storytelling techniques that guide prospects through a narrative arc from problem to solution. Develop the ability to handle live objections during demos and adapt on the fly when things don't go as planned.",
      url: "https://www.duarte.com/presentation-skills-resources/",
    },
    {
      id: "step-3",
      label: "Product Knowledge",
      tool: "Technical Docs",
      description: "Develop deep expertise in your product's architecture, APIs, integrations, and technical limitations. Study internal documentation, attend engineering standups, and shadow support tickets to understand real-world edge cases. Become the trusted advisor who can answer the toughest technical questions without deferring back to engineering.",
      url: "https://www.writethedocs.org/",
    },
    {
      id: "step-4",
      label: "RFP Response",
      tool: "Proposal Writing",
      description: "Build a repeatable process for responding to technical questionnaires, security reviews, and bid documents under tight deadlines. Create a living library of reusable answers and customize them with prospect-specific context and proof points. Balance thoroughness with conciseness to ensure evaluators find exactly what they need quickly.",
      url: "https://www.rfp360.com/blog/rfp-response-process/",
    },
    {
      id: "step-5",
      label: "CRM",
      tool: "Salesforce",
      description: "Use Salesforce or similar CRM platforms to track deal progress, forecast pipeline accurately, and manage customer relationships at scale. Log technical discovery notes, demo outcomes, and next steps so the entire sales team stays aligned. Leverage CRM data and dashboards to identify at-risk deals and double down on high-value opportunities.",
      url: "https://trailhead.salesforce.com/",
    },
    {
      id: "step-6",
      label: "Industry Knowledge",
      tool: "Vertical Expertise",
      description: "Study the regulatory landscape, operational workflows, and technology stack common to your target verticals. Build domain expertise so you can speak credibly about industry-specific challenges and benchmark against competitors. Maintain a library of vertical case studies and success stories to reference during prospect conversations.",
      url: "https://www.gartner.com/en/industries",
    },
    {
      id: "step-7",
      label: "Competitive Analysis",
      tool: "Battle Cards",
      description: "Research competitor products, pricing models, and positioning to prepare battle cards for every deal. Identify your product's key differentiators and develop concise responses to common objections. Update competitive intelligence regularly and share insights across sales and product teams to keep your positioning sharp.",
      url: "https://www.gong.io/blog/competitive-intelligence/",
    },
    {
      id: "step-8",
      label: "Solution Architecture",
      tool: "System Design",
      description: "Design end-to-end solution architectures that show prospects exactly how your product fits into their existing infrastructure and workflows. Create integration diagrams, data flow maps, and deployment topologies that demonstrate technical feasibility. Collaborate with solutions architects and engineers to ensure proposed designs are realistic and scalable.",
      url: "https://www.pluralsight.com/courses/architecture-system-design-fundamentals",
    },
    {
      id: "step-9",
      label: "Negotiation",
      tool: "Deal Structuring",
      description: "Learn to negotiate technical terms, licensing models, and implementation timelines without eroding product value or margins. Develop strategies for handling procurement teams who focus solely on price rather than outcomes. Understand when to concede, when to hold firm, and how to create win-win structures that accelerate deal closure.",
      url: "https://www.hbs.edu/faculty/Pages/item.aspx?num=5284",
    },
    {
      id: "step-10",
      label: "Customer Relationship Management",
      tool: "Account Management",
      description: "Build lasting relationships with technical contacts and champions who will advocate for your solution internally. Maintain regular touchpoints with stakeholders beyond the initial deal to drive adoption and expansion opportunities. Track customer health signals like usage patterns and support tickets to proactively address risks before they threaten retention.",
      url: "https://www.hubspot.com/resources/crm/customer-relationship-management",
    },
    {
      id: "step-11",
      label: "Technical Communication",
      tool: "Writing & Docs",
      description: "Produce clear technical documentation including solution briefs, integration guides, and architecture overviews that prospects can share with their teams. Develop concise written responses that break down complex concepts for non-technical decision-makers. Use visual aids, diagrams, and structured formats to make technical content scannable and persuasive.",
      url: "https://www.writethedocs.org/guide/",
    },
    {
      id: "step-12",
      label: "Post-Sales Support",
      tool: "Customer Success",
      description: "Hand off technical context from the sales cycle to implementation and customer success teams to ensure a smooth onboarding experience. Monitor early deployment phases and address technical blockers that could derail time-to-value. Serve as a technical escalation point during the first 90 days to reinforce buyer confidence and reduce churn risk.",
      url: "https://www.gainsight.com/customer-success-resources/",
    },
  ],
};
