import { Roadmap } from "../types/roadmap";

export const softwareEngineerRoadmap: Roadmap = {
  id: "software-engineer",
  title: "Software Engineer",
  description: "Build reliable, scalable software systems using core engineering principles.",
  introduction: "Software engineering applies systematic approaches to building reliable, scalable systems. This roadmap covers data structures, system design, testing, and cloud deployment for production-grade software.",
  icon: "💻",
  category: "Engineering",
  difficulty: "Advanced",
  estimatedTime: "6-12 months",
  steps: [
    {
      id: "step-1",
      label: "Programming Language",
      tool: "Python",
      description: "Master a versatile language with strong ecosystem support. Learn data structures, algorithms, OOP, functional programming, and concurrency. The language matters less than the concepts — choose one and go deep.",
      url: "https://www.python.org/doc/",
    },
    {
      id: "step-2",
      label: "Data Structures",
      tool: "Algorithms",
      description: "Implement arrays, linked lists, stacks, queues, trees, graphs, hash maps, and heaps. Understand Big-O notation for time and space complexity. Data structures are the building blocks of efficient software — interviews test them for a reason.",
      url: "https://www.geeksforgeeks.org/data-structures/",
    },
    {
      id: "step-3",
      label: "Algorithms",
      tool: "LeetCode",
      description: "Practice sorting, searching, dynamic programming, graph traversal (BFS/DFS), and greedy algorithms. Learn to identify problem patterns and choose the right approach. Algorithmic thinking separates senior engineers from juniors.",
      url: "https://leetcode.com/",
    },
    {
      id: "step-4",
      label: "System Design",
      tool: "System Design",
      description: "Architect scalable systems with load balancing, caching, database sharding, message queues, and microservices. Learn to make trade-offs between consistency, availability, and partition tolerance. System design is the most important skill for senior roles.",
      url: "https://github.com/donnemartin/system-design-primer",
    },
    {
      id: "step-5",
      label: "Design Patterns",
      tool: "Gang of Four",
      description: "Learn creational (Singleton, Factory), structural (Adapter, Decorator), and behavioral (Observer, Strategy) patterns. Patterns are proven solutions to recurring problems — understanding them gives you a shared vocabulary with other engineers.",
      url: "https://refactoring.guru/design-patterns",
    },
    {
      id: "step-6",
      label: "Version Control",
      tool: "Git",
      description: "Master branching strategies, interactive rebase, cherry-picking, bisect, and worktrees. Use Git hooks for automated checks and conventional commits for changelog generation. Git proficiency separates productive engineers from frustrated ones.",
      url: "https://git-scm.com/doc",
    },
    {
      id: "step-7",
      label: "Testing",
      tool: "pytest",
      description: "Write unit tests, integration tests, contract tests, and property-based tests. Learn test-driven development (TDD), mocking, and test coverage analysis. Testing is not optional for production software — it's how you ship with confidence.",
      url: "https://docs.pytest.org/",
    },
    {
      id: "step-8",
      label: "Databases",
      tool: "PostgreSQL",
      description: "Design schemas with normalization, indexing, and query optimization. Learn about ACID transactions, isolation levels, and connection pooling. Every application needs data persistence — understanding databases deeply is non-negotiable.",
      url: "https://www.postgresql.org/docs/",
    },
    {
      id: "step-9",
      label: "API Design",
      tool: "REST",
      description: "Design RESTful APIs with proper resource naming, HTTP methods, status codes, pagination, filtering, and versioning. Learn API documentation with OpenAPI/Swagger. A well-designed API is intuitive, consistent, and backwards-compatible.",
      url: "https://restfulapi.net/",
    },
    {
      id: "step-10",
      label: "Concurrency",
      tool: "asyncio",
      description: "Write concurrent code with threads, processes, and async/await. Understand race conditions, deadlocks, and the GIL. Concurrency is how you handle thousands of simultaneous requests — it's essential for scalable systems.",
      url: "https://docs.python.org/3/library/asyncio.html",
    },
    {
      id: "step-11",
      label: "CI/CD",
      tool: "GitHub Actions",
      description: "Automate build, test, lint, and deployment pipelines. Implement branch protection, required reviews, and automated releases. CI/CD is the factory floor of software delivery — it's how teams ship reliably.",
      url: "https://docs.github.com/en/actions",
    },
    {
      id: "step-12",
      label: "Cloud Deployment",
      tool: "AWS",
      description: "Deploy applications with proper networking, security groups, auto-scaling, and monitoring. Understand the trade-offs between containers, serverless, and traditional VMs. Cloud deployment is where code meets reality.",
      url: "https://docs.aws.amazon.com/gettingstarted/latest/welcome/",
    },
    {
      id: "step-13",
      label: "Code Quality",
      tool: "SonarQube",
      description: "Enforce code quality with linters (ESLint, Ruff), formatters (Prettier, Black), and static analysis. Track technical debt, code smells, and duplication. Clean code is easier to maintain, debug, and extend.",
      url: "https://www.sonarsource.com/products/sonarqube/",
    },
    {
      id: "step-14",
      label: "Documentation",
      tool: "MkDocs",
      description: "Write technical documentation, architecture decision records (ADRs), and README files. Document APIs, runbooks, and onboarding guides. Documentation is how knowledge survives beyond the people who built the system.",
      url: "https://www.mkdocs.org/",
    },
  ],
};
