import { Roadmap } from "../types/roadmap";

export const supplyChainAnalystRoadmap: Roadmap = {
  id: "supply-chain-analyst",
  title: "Supply Chain Analyst",
  description: "Optimize logistics, inventory, and procurement through data analysis.",
  introduction: "Supply chain analysis optimizes logistics, inventory, and procurement. Master demand planning, ERP systems, visualization, and optimization.",
  icon: "📦",
  category: "Business",
  difficulty: "Intermediate",
  estimatedTime: "3-6 months",
  steps: [
    {
      id: "step-1",
      label: "Supply Chain Basics",
      tool: "SCM Principles",
      description: "Understand the core pillars of supply chain management including procurement, production, and distribution flows. Learn how raw materials transform into finished goods and reach end consumers through integrated networks. Study the bullwhip effect, just-in-time manufacturing, and lean principles that drive efficient supply chain operations.",
      url: "https://www.apics.org/",
    },
    {
      id: "step-2",
      label: "Excel & Analytics",
      tool: "Excel",
      description: "Master advanced Excel functions such as VLOOKUP, pivot tables, and conditional formatting for supply chain data analysis. Analyze inventory levels, lead times, and demand forecasts using statistical functions and data visualization tools. Build automated dashboards and scenario models to support procurement and logistics decision-making.",
      url: "https://support.microsoft.com/en-us/office/excel-video-training-9bc053dc-87d4-4146-8e93-f37e57dad873",
    },
    {
      id: "step-3",
      label: "Demand Planning",
      tool: "Forecasting",
      description: "Predict future demand using statistical models, time series analysis, and historical sales data. Learn techniques such as moving averages, exponential smoothing, and regression analysis to generate accurate forecasts. Collaborate with sales and marketing teams to incorporate market intelligence into demand plans and reduce forecast error.",
      url: "https://otexts.com/fpp3/",
    },
    {
      id: "step-4",
      label: "ERP Systems",
      tool: "SAP",
      description: "Navigate enterprise resource planning systems to manage procurement, inventory, and production scheduling in real time. SAP and similar platforms centralize data across the supply chain, enabling end-to-end visibility and streamlined workflows. Learn master data management, purchase order processing, and materials requirement planning within an ERP environment.",
      url: "https://help.sap.com/docs/SAP_S4HANA_ON-PREMISE",
    },
    {
      id: "step-5",
      label: "Visualization",
      tool: "Power BI",
      description: "Build interactive supply chain dashboards that surface real-time KPIs such as fill rates, cycle times, and transportation costs. Power BI and similar tools connect to multiple data sources to create unified views of procurement, inventory, and logistics performance. Design drill-down reports that help stakeholders identify bottlenecks, track supplier performance, and monitor on-time delivery metrics.",
      url: "https://learn.microsoft.com/en-us/power-bi/",
    },
    {
      id: "step-6",
      label: "Optimization",
      tool: "Linear Programming",
      description: "Apply mathematical optimization techniques such as linear programming and mixed-integer programming to solve complex supply chain problems. Optimize transportation routes, warehouse allocation, and production scheduling to minimize cost while meeting service level targets. Use solvers and simulation tools to evaluate trade-offs between inventory carrying costs, transportation expenses, and customer satisfaction.",
      url: "https://www.coursera.org/learn/discrete-optimization",
    },
    {
      id: "step-7",
      label: "Inventory Management",
      tool: "Inventory Control",
      description: "Implement inventory control strategies including safety stock calculations, ABC analysis, and economic order quantity models. Balance the tension between holding costs and stockout risks to maintain optimal inventory levels across the supply chain. Track inventory turnover, days of supply, and reorder points to ensure product availability while minimizing waste and obsolescence.",
      url: "https://www.apics.org/",
    },
    {
      id: "step-8",
      label: "Procurement",
      tool: "Strategic Sourcing",
      description: "Develop sourcing strategies that balance cost, quality, and supplier reliability to build a resilient supply base. Evaluate suppliers using scorecards, negotiate contracts, and manage purchase orders to secure materials at competitive terms. Understand supplier relationship management, total cost of ownership, and the impact of procurement decisions on overall supply chain performance.",
      url: "https://www.cips.org/",
    },
    {
      id: "step-9",
      label: "Logistics",
      tool: "Transportation Management",
      description: "Manage the movement of goods across inbound and outbound logistics networks using freight, warehousing, and distribution strategies. Analyze transportation modes, carrier performance, and shipping costs to design efficient delivery routes and reduce lead times. Study last-mile delivery, cross-docking, and freight consolidation techniques that improve service levels while controlling logistics expenses.",
      url: "https://www.cscmp.org/",
    },
    {
      id: "step-10",
      label: "Risk Management",
      tool: "Supply Chain Resilience",
      description: "Identify and mitigate risks such as supplier failures, geopolitical disruptions, natural disasters, and demand volatility across the supply chain. Develop business continuity plans, diversify sourcing strategies, and build buffer capacity to absorb unexpected shocks. Use risk assessment frameworks and scenario planning to quantify exposure and prioritize mitigation investments.",
      url: "https://www.rims.org/",
    },
    {
      id: "step-11",
      label: "Sustainability",
      tool: "Green Supply Chain",
      description: "Integrate environmental and social responsibility into supply chain operations through sustainable sourcing and carbon footprint reduction. Measure and report Scope 3 emissions, implement circular economy practices, and evaluate suppliers on sustainability criteria. Align supply chain strategies with ESG goals and regulatory requirements to build long-term resilience and brand value.",
      url: "https://www.spglobal.com/esg/insights/",
    },
    {
      id: "step-12",
      label: "Supply Chain Technology",
      tool: "Digital Supply Chain",
      description: "Leverage emerging technologies such as AI, blockchain, IoT, and digital twins to transform supply chain visibility and decision-making. Implement predictive analytics for demand sensing, automate warehouse operations with robotics, and use real-time tracking for shipment visibility. Evaluate technology adoption strategies that align digital investments with business objectives and operational maturity.",
      url: "https://www.gartner.com/en/supply-chain",
    },
  ],
};
