import { Roadmap } from "../types/roadmap";

export const systemAdministratorRoadmap: Roadmap = {
  id: "system-administrator",
  title: "System Administrator",
  description: "Manage servers, users, and infrastructure to keep systems running smoothly.",
  introduction: "System administration keeps servers and infrastructure running smoothly. Learn Linux, shell scripting, user management, virtualization, and monitoring.",
  icon: "🖥️",
  category: "Infrastructure",
  difficulty: "Intermediate",
  estimatedTime: "4-7 months",
  steps: [
    { id: "step-1", label: "Linux Administration", tool: "Ubuntu", description: "Learn to install, configure, and manage Linux server distributions such as Ubuntu, CentOS, and Debian. Understand package management, service control, and system boot processes. Master file permissions, disk partitioning, and log management to maintain stable server environments.", url: "https://ubuntu.com/tutorials" },
    { id: "step-2", label: "Shell Scripting", tool: "Bash", description: "Automate repetitive tasks and system maintenance using Bash scripts. Write scripts to handle backups, user provisioning, log rotation, and system health checks. Learn control structures, functions, and error handling to build reliable automation workflows.", url: "https://www.gnu.org/software/bash/manual/" },
    { id: "step-3", label: "User Management", tool: "LDAP", description: "Manage user accounts, groups, and permissions across local and centralized systems. Configure LDAP directory services for scalable authentication and access control. Implement password policies, sudo configurations, and audit trails to enforce the principle of least privilege.", url: "https://www.openldap.org/" },
    { id: "step-4", label: "Networking", tool: "TCP/IP", description: "Understand TCP/IP fundamentals including IP addressing, subnetting, routing, and firewall rules. Configure network interfaces, DNS resolution, and DHCP services to ensure reliable connectivity. Troubleshoot network issues using tools like ping, traceroute, netstat, and tcpdump.", url: "https://www.cloudflare.com/learning/networking/" },
    { id: "step-5", label: "Backup & Recovery", tool: "Bacula", description: "Design and implement backup strategies covering full, incremental, and differential backups. Set up automated backup schedules and off-site storage for disaster recovery readiness. Test restoration procedures regularly to verify data integrity and minimize downtime during failures.", url: "https://www.bacula.org/manuals/en/" },
    { id: "step-6", label: "Virtualization", tool: "Proxmox", description: "Deploy and manage virtual machines and containers on a single physical host using Proxmox VE. Configure virtual networking, storage pools, and resource allocation for optimal performance. Learn live migration, snapshots, and high availability clustering for production environments.", url: "https://pve.proxmox.com/pve-docs/" },
    { id: "step-7", label: "Monitoring", tool: "Zabbix", description: "Track system metrics, application performance, and network health using Zabbix. Set up agents, templates, and alert rules to detect issues before they impact users. Build dashboards and reports for capacity planning and trend analysis across your infrastructure.", url: "https://www.zabbix.com/documentation/" },
    { id: "step-8", label: "Security Hardening", tool: "SELinux", description: "Apply security hardening techniques to reduce the attack surface of servers and services. Configure SELinux, firewall rules, SSH restrictions, and kernel parameters following industry best practices. Perform regular vulnerability scans and patch management to maintain compliance and protect against threats.", url: "https://www.redhat.com/en/topics/linux/what-is-selinux" },
    { id: "step-9", label: "Configuration Management", tool: "Ansible", description: "Automate infrastructure provisioning and configuration using Ansible playbooks and roles. Define repeatable, idempotent workflows to deploy software, manage configurations, and enforce desired state. Integrate with version control to track changes and collaborate across operations teams.", url: "https://www.ansible.com/" },
    { id: "step-10", label: "Containerization", tool: "Docker", description: "Package applications and their dependencies into portable containers using Docker. Build, ship, and run containers consistently across development, staging, and production environments. Manage container orchestration, networking, and persistent storage for scalable microservices architectures.", url: "https://www.docker.com/" },
    { id: "step-11", label: "DNS & DHCP", tool: "BIND", description: "Configure and manage DNS resolution using BIND or other authoritative DNS servers. Set up zones, records, and forwarding to ensure reliable name resolution across your network. Deploy and manage DHCP services to automate IP address assignment and streamline network onboarding.", url: "https://www.isc.org/bind/" },
    { id: "step-12", label: "Documentation", tool: "Wiki", description: "Create and maintain comprehensive documentation for systems, procedures, and troubleshooting guides. Use wikis or knowledge bases to share institutional knowledge and onboarding materials with the team. Keep runbooks, architecture diagrams, and change logs up to date to ensure operational continuity.", url: "https://www.mediawiki.org/" },
  ],
};
