import { Roadmap } from "../types/roadmap";

export const technicalWriterRoadmap: Roadmap = {
  id: "technical-writer",
  title: "Technical Writer",
  description: "Create clear documentation, guides, and knowledge bases for software products.",
  introduction: "Technical writing bridges the gap between complex software and the people who use it. A skilled technical writer transforms intricate systems into clear, actionable documentation that empowers users, reduces support burden, and accelerates product adoption. This roadmap guides you through the essential skills, tools, and practices that distinguish professional documentation from informal notes.",
  icon: "📝",
  category: "Business",
  difficulty: "Beginner",
  estimatedTime: "2-4 months",
  steps: [
    { id: "step-1", label: "Writing Fundamentals", tool: "Plain Language", description: "Master the core principles of clear, concise technical writing that prioritizes readability over complexity. Learn to structure information using inverted pyramid and task-oriented approaches so readers find answers quickly. Develop the habit of editing ruthlessly, removing jargon, and replacing ambiguity with precise language that leaves no room for misinterpretation.", url: "https://www.plainlanguage.gov/" },
    { id: "step-2", label: "Markdown", tool: "Markdown", description: "Adopt Markdown as the universal lightweight markup language for writing and publishing documentation across platforms. Understand how to structure content with headings, lists, code blocks, tables, and links to create well-organized pages. Explore extended Markdown flavors used in static site generators and learn how consistent formatting improves both readability and maintainability.", url: "https://www.markdownguide.org/" },
    { id: "step-3", label: "API Documentation", tool: "OpenAPI", description: "Document RESTful and GraphQL APIs using the OpenAPI (Swagger) specification to produce interactive reference materials. Learn how to describe endpoints, parameters, request bodies, and response schemas in a machine-readable format that tools can parse. Use interactive consoles and auto-generated client SDKs to validate accuracy and ensure developers can integrate with your API on the first attempt.", url: "https://swagger.io/docs/" },
    { id: "step-4", label: "Documentation Tools", tool: "Docusaurus", description: "Evaluate and deploy documentation frameworks like Docusaurus and MkDocs to build fast, searchable documentation websites from Markdown sources. Understand how these tools handle versioning, sidebar navigation, and theming to create a professional documentation experience. Configure search integration, deployment pipelines, and analytics to keep your documentation discoverable, current, and aligned with user needs.", url: "https://docusaurus.io/docs" },
    { id: "step-5", label: "Diagrams", tool: "Mermaid", description: "Communicate complex workflows, architectures, and sequences visually using Mermaid diagrams embedded directly in Markdown files. Learn the syntax for flowcharts, sequence diagrams, class diagrams, and state machines to represent system behavior without leaving your documentation. Maintain diagrams as text so they stay in sync with code changes, eliminating the drift that plagues screenshot-based documentation.", url: "https://mermaid.js.org/" },
    { id: "step-6", label: "Version Control", tool: "Git", description: "Use Git to track every change to your documentation, enabling collaboration, rollback, and audit trails alongside your codebase. Learn branching strategies that support documentation review cycles, including pull requests, content approvals, and release tagging. Leverage Git history to understand when and why documentation was updated, providing context that static files alone cannot preserve.", url: "https://git-scm.com/doc" },
    { id: "step-7", label: "Style Guides", tool: "Google Developer Documentation Style Guide", description: "Adopt established style guides to enforce consistency in terminology, tone, grammar, and formatting across all documentation. Study popular guides such as the Google Developer Documentation Style Guide and Microsoft Style Guide to understand industry conventions. Create a project-specific style sheet that codifies decisions about capitalization, punctuation, voice, and word choice so every contributor produces uniform content.", url: "https://developers.google.com/style" },
    { id: "step-8", label: "Information Architecture", tool: "Navigation Design", description: "Organize and structure documentation so users can intuitively find the content they need without unnecessary searching. Design navigation hierarchies, breadcrumbs, and cross-references that reflect how users actually think about your product, not how your engineering team is organized. Apply principles of progressive disclosure to guide readers from overview concepts to detailed reference material in a logical flow.", url: "https://www.nngroup.com/articles/information-architecture/" },
    { id: "step-9", label: "Content Strategy", tool: "Documentation Planning", description: "Develop a long-term plan for creating, maintaining, and sunsetting documentation that aligns with product roadmaps and user needs. Identify audience personas, map their journeys, and prioritize content that addresses high-impact use cases first. Establish editorial calendars, ownership models, and quality gates that ensure documentation evolves alongside the product rather than decaying into outdated inaccuracies.", url: "https://www.contentstrategy.com/" },
    { id: "step-10", label: "Localization", tool: "i18n Frameworks", description: "Prepare documentation for translation by implementing internationalization patterns that separate translatable strings from layout and code. Learn to write source content that is culturally neutral and easy for translators to localize without breaking formatting or meaning. Integrate translation management systems and establish workflows for managing multiple language versions while keeping all variants synchronized with source updates.", url: "https://www.w3.org/International/" },
    { id: "step-11", label: "Docs-as-Code", tool: "CI/CD Pipelines", description: "Apply software engineering practices to documentation by storing docs in repositories, reviewing them through pull requests, and deploying them via automated pipelines. Integrate linting, link checking, and preview builds into continuous integration to catch errors before they reach production. Treat documentation as a first-class artifact in your delivery process, ensuring it ships with every release and remains in sync with the code it describes.", url: "https://www.docs-as-code.org/" },
    { id: "step-12", label: "Measuring Documentation Quality", tool: "Analytics & Feedback", description: "Implement metrics and feedback mechanisms to understand whether your documentation actually helps users accomplish their goals. Track quantitative signals like page views, search queries, time on page, and bounce rates to identify content gaps and pain points. Combine analytics with qualitative feedback from surveys, support tickets, and community forums to prioritize improvements that deliver measurable impact on user success.", url: "https://developers.google.com/style" },
  ],
};
