import { Roadmap } from "../types/roadmap";

export const veterinaryMedicineRoadmap: Roadmap = {
  id: "veterinary-medicine",
  title: "Veterinary Medicine",
  description: "Diagnose and treat animal diseases across companion and livestock species.",
  introduction: "Veterinary medicine diagnoses and treats animal diseases across species. Master animal anatomy, pathology, pharmacology, surgery, and diagnostic imaging.",
  icon: "🐾",
  category: "Science",
  difficulty: "Expert",
  estimatedTime: "12-18 months",
  steps: [
    {
      id: "step-1",
      label: "Animal Anatomy",
      tool: "Veterinary Anatomy",
      description: "Study the structural organization of animal bodies, including the skeletal, muscular, cardiovascular, and nervous systems across domestic and exotic species. Understand comparative anatomy to recognize how organ systems differ between species such as dogs, cats, horses, cattle, and birds. A solid foundation in anatomy is essential for accurate diagnosis, surgical planning, and radiographic interpretation throughout your veterinary career.",
      url: "https://www.britannica.com/science/veterinary-medicine",
    },
    {
      id: "step-2",
      label: "Pathology",
      tool: "Disease Diagnosis",
      description: "Identify the mechanisms of disease through gross and microscopic examination of tissues, cells, and fluids. Learn to correlate clinical signs with pathological findings to arrive at accurate diagnoses in both companion and farm animals. Pathology bridges clinical observation and laboratory science, forming the backbone of evidence-based veterinary practice.",
      url: "https://www.acvp.org/",
    },
    {
      id: "step-3",
      label: "Veterinary Pharmacology",
      tool: "Veterinary Drugs",
      description: "Understand drug mechanisms, dosages, contraindications, and species-specific metabolism to ensure safe and effective treatment of animal patients. Master pharmacokinetics and pharmacodynamics as they apply to various animal classes, including differences in drug tolerance between ruminants, equines, and small companion animals. Proper pharmacological knowledge prevents adverse reactions and optimizes therapeutic outcomes across diverse patient populations.",
      url: "https://www.plumbvets.com/",
    },
    {
      id: "step-4",
      label: "Veterinary Surgery",
      tool: "Veterinary Surgery",
      description: "Develop proficiency in soft tissue surgery, orthopedic procedures, and emergency surgical interventions for a wide range of animal species. Master aseptic technique, tissue handling, anesthesia protocols, and post-operative care to minimize complications and promote healing. Surgical competence requires both theoretical knowledge and extensive hands-on practice under experienced mentorship.",
      url: "https://www.acvs.org/",
    },
    {
      id: "step-5",
      label: "Internal Medicine",
      tool: "Clinical Diagnosis",
      description: "Diagnose and manage complex medical conditions affecting the cardiovascular, gastrointestinal, endocrine, respiratory, and renal systems in companion and large animals. Utilize history-taking, physical examination, and laboratory data to formulate differential diagnoses and evidence-based treatment plans. Internal medicine demands strong analytical skills and the ability to integrate findings from multiple diagnostic modalities.",
      url: "https://www.acvim.org/",
    },
    {
      id: "step-6",
      label: "Diagnostic Imaging",
      tool: "X-Ray/Ultrasound",
      description: "Interpret radiographs, ultrasounds, CT scans, and MRI studies to visualize internal structures and identify pathologies such as fractures, tumors, and organ abnormalities. Learn positioning techniques, image quality optimization, and systematic approaches to reading and reporting imaging findings. Diagnostic imaging is an indispensable tool that supports clinical decision-making and monitors treatment progress.",
      url: "https://www.acvr.org/",
    },
    {
      id: "step-7",
      label: "Emergency & Critical Care",
      tool: "Emergency Medicine",
      description: "Manage acute life-threatening conditions including trauma, poisoning, respiratory distress, and cardiovascular collapse with rapid assessment and intervention. Develop skills in triage, emergency stabilization, fluid therapy, pain management, and continuous patient monitoring in intensive care settings. Speed and precision are critical in emergency medicine, where timely decisions directly impact patient survival.",
      url: "https://www.svma.org/",
    },
    {
      id: "step-8",
      label: "Veterinary Nutrition",
      tool: "Animal Nutrition",
      description: "Design species-appropriate diets that meet the nutritional requirements of healthy animals and those with chronic or acute illnesses. Understand macronutrient and micronutrient roles, metabolic disorders related to diet, and the formulation of therapeutic diets for conditions such as renal disease, diabetes, and obesity. Nutritional management is a cornerstone of preventive care and significantly influences treatment outcomes.",
      url: "https://www.aafco.org/",
    },
    {
      id: "step-9",
      label: "Parasitology",
      tool: "Parasite Control",
      description: "Identify internal and external parasites including helminths, protozoa, ticks, fleas, and mites that affect domestic and wild animals. Learn diagnostic techniques such as fecal analysis, skin scrapings, and blood smears to detect parasitic infections and determine appropriate antiparasitic treatments. Understanding parasite life cycles and epidemiology is essential for implementing effective prevention and control programs.",
      url: "https://www.nadss.org/",
    },
    {
      id: "step-10",
      label: "Veterinary Dentistry",
      tool: "Dental Care",
      description: "Perform dental prophylaxis, extractions, and oral surgery while recognizing periodontal disease, tooth fractures, and oral tumors common in companion animals. Master dental radiography, anesthesia protocols for dental procedures, and client education on at-home oral hygiene practices. Oral health directly impacts overall systemic health, making dentistry a vital component of comprehensive veterinary care.",
      url: "https://www.avdc.org/",
    },
    {
      id: "step-11",
      label: "Animal Behavior",
      tool: "Behavioral Medicine",
      description: "Assess behavioral problems such as aggression, anxiety, compulsive disorders, and phobias in companion animals and develop evidence-based behavior modification plans. Understand the principles of learning theory, pharmacological interventions for behavioral disorders, and the role of environmental enrichment. Effective behavioral management strengthens the human-animal bond and improves welfare outcomes for both pets and their owners.",
      url: "https://www.dacvb.org/",
    },
    {
      id: "step-12",
      label: "Public Health",
      tool: "One Health",
      description: "Address zoonotic diseases, food safety, and the intersection of animal, human, and environmental health through the One Health framework. Participate in disease surveillance, outbreak response, and public health policy development to protect both animal and human populations. Veterinary public health professionals play a critical role in preventing the spread of infectious diseases and ensuring the safety of the global food supply.",
      url: "https://www.who.int/health-topics/zoonoses",
    },
    {
      id: "step-13",
      label: "Practice Management",
      tool: "Business Management",
      description: "Develop the business acumen necessary to run a successful veterinary practice, including financial planning, staff management, client communication, and marketing. Learn to implement efficient workflows, manage inventory, navigate regulatory compliance, and leverage technology to improve patient care and client satisfaction. Strong practice management ensures long-term sustainability while allowing veterinarians to focus on delivering excellent clinical care.",
      url: "https://www.avma.org/practice-practice-management",
    },
  ],
};
