import { Roadmap } from "../types/roadmap";

export const webDevelopmentRoadmap: Roadmap = {
  id: "web-development",
  title: "Web Development",
  description: "Build modern websites and web applications from frontend to backend.",
  introduction: "Web development is the foundation of the modern internet. This roadmap takes you from writing your first HTML tag to deploying full-stack applications, covering the tools and frameworks used by professional developers worldwide.",
  icon: "🌐",
  category: "Engineering",
  difficulty: "Beginner",
  estimatedTime: "3-6 months",
  steps: [
    {
      id: "step-1",
      label: "HTML Fundamentals",
      tool: "HTML5",
      description: "Learn semantic HTML elements like header, nav, main, article, and footer. Understand forms, inputs, tables, and how to structure content for accessibility. HTML is the skeleton of every web page — everything else builds on top of it.",
      url: "https://developer.mozilla.org/en-US/docs/Learn/HTML",
    },
    {
      id: "step-2",
      label: "CSS Styling",
      tool: "CSS3",
      description: "Master the box model, Flexbox, and CSS Grid for layouts. Learn responsive design with media queries, CSS variables for theming, and animations. CSS transforms plain HTML into visually compelling pages.",
      url: "https://developer.mozilla.org/en-US/docs/Learn/CSS",
    },
    {
      id: "step-3",
      label: "JavaScript Basics",
      tool: "JavaScript",
      description: "Understand variables, functions, loops, arrays, objects, and DOM manipulation. Learn ES6+ features like arrow functions, destructuring, template literals, and async/await. JavaScript brings your pages to life with interactivity.",
      url: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide",
    },
    {
      id: "step-4",
      label: "Version Control",
      tool: "Git",
      description: "Track code changes with commits, branches, and merges. Learn to collaborate using pull requests on GitHub. Version control is non-negotiable for any real project — it's your safety net and collaboration backbone.",
      url: "https://git-scm.com/doc",
    },
    {
      id: "step-5",
      label: "CSS Framework",
      tool: "Tailwind CSS",
      description: "Rapidly build consistent UIs with utility-first CSS classes. Tailwind eliminates repetitive custom CSS and enforces a design system through its constrained utility palette. It's the standard for modern frontend development.",
      url: "https://tailwindcss.com/docs/installation",
    },
    {
      id: "step-6",
      label: "React",
      tool: "React",
      description: "Build reusable UI components with JSX, hooks (useState, useEffect, useRef), and component lifecycle. React's component model makes complex UIs manageable by breaking them into small, testable pieces.",
      url: "https://react.dev/learn",
    },
    {
      id: "step-7",
      label: "Package Management",
      tool: "npm",
      description: "Install, update, and manage project dependencies. Understand package.json, semantic versioning, and how to create your own packages. npm is the gateway to the JavaScript ecosystem's vast library of tools.",
      url: "https://docs.npmjs.com/cli",
    },
    {
      id: "step-8",
      label: "Backend with Node.js",
      tool: "Node.js",
      description: "Run JavaScript on the server to build APIs and handle HTTP requests. Node.js extends your JS skills to the backend, letting you use one language across the entire stack. Learn the event loop and non-blocking I/O model.",
      url: "https://nodejs.org/en/docs",
    },
    {
      id: "step-9",
      label: "API Design",
      tool: "Express.js",
      description: "Build RESTful APIs with routing, middleware, error handling, and authentication. Express is the most widely used Node.js framework — understanding it teaches you patterns that apply to any backend framework.",
      url: "https://expressjs.com/en/guide/routing.html",
    },
    {
      id: "step-10",
      label: "Databases",
      tool: "PostgreSQL",
      description: "Model relational data with tables, foreign keys, and indexes. Write SQL queries with JOINs, aggregations, and subqueries. Every dynamic application needs persistent storage — PostgreSQL is the gold standard for relational data.",
      url: "https://www.postgresql.org/docs/",
    },
    {
      id: "step-11",
      label: "Authentication",
      tool: "NextAuth.js",
      description: "Implement secure user login with sessions, JWT tokens, or OAuth providers like Google and GitHub. Authentication is one of the first real-world features you'll add to any application that has users.",
      url: "https://next-auth.js.org/",
    },
    {
      id: "step-12",
      label: "TypeScript",
      tool: "TypeScript",
      description: "Add static type checking to JavaScript. Catch bugs at compile time instead of runtime with interfaces, generics, and type annotations. TypeScript is now the industry standard — most new projects use it by default.",
      url: "https://www.typescriptlang.org/docs/",
    },
    {
      id: "step-13",
      label: "Testing",
      tool: "Vitest",
      description: "Write unit tests, integration tests, and component tests to verify your code works correctly. Good tests give you confidence to refactor and ship new features without breaking existing functionality.",
      url: "https://vitest.dev/guide/",
    },
    {
      id: "step-14",
      label: "Deployment",
      tool: "Vercel",
      description: "Deploy your application to production with continuous deployment, preview environments, and custom domains. Vercel integrates with Git for automatic deployments on every push.",
      url: "https://vercel.com/docs",
    },
  ],
};
